### ISSUE TITLE
Insert Newline

### ISSUE THREAD

**Issue by Drevarr** [Nyyrazzilyss/NyyLIB#1]
Couldn't post to the Mudlet forum so I thought I would post here and my Soj forum accounts point to nonexistent email accounts these days.

The snippet below works for inserting a newline when `echo tested on:
< 794h/794H 910p/910P 106v/106V P: std > You are 0 XP (0.00%) away from your next level.

````Lua
if moveCursor(string.find(line, ">")+#(">")-1, getLineNumber()) then
  insertText("\n")
end
````

**Comment by Nyyrazzilyss** [comment]
Thank you! I hadn't noticed this, and was just back to trying to fix this earlier today.

It works!

**Comment by Drevarr** [comment]
Glad it works for you.  Sorry I forgot to re-post on the forums once they
were fixed.


Drevarr


On Mon, Dec 14, 2015 at 10:13 PM, Nyyrazzilyss <notifications@github.com>
wrote:

> Thank you! I hadn't noticed this, and was just back to trying to fix this
> earlier today.
>
> It works!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nyyrazzilyss/NyyLIB/issues/1#issuecomment-164631873>.
>



--
