### ISSUE TITLE
Rogue starttrain tank - If assassinate is on a cooldown not captured by mudlet I don't manually backstab the 1st mob in train

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#10]
Scenario:
If Rogue's assassinate skill is on cooldown that is not known to mudlet the train breaks.  If in exp train and assassinate is on cooldown can the rogue then backstab the same assassinate target?

Log
< 622h/440H 120v/130V P: std > 

[Reached train station: (87263) gambler]

A Calimport gambler is in an excellent condition. (Medium)

< 622h/440H 121v/130V P: std > 
You group-say '[Attacking: Gambler]'

< 620h/440H 122v/130V P: std >

Assassination requires intense preparation.
You may only attempt to assassinate someone once a day!

< 620h/440H 122v/130V P: std > 
BS gambler
Severely weakened, a Calimport gambler falls to his knees!
Your massive pierce barely wounds a Calimport gambler.

< 604h/440H 130v/130V T: Ezdad TC: excellent E: gambler EC: few scratches EP: knl P: std >

**Comment by Nyyrazzilyss** [comment]
Might be fixed in 011dev 07-17. Completely untested :)
