### ISSUE TITLE
Enchanter Script should allow for @set to define a custom list of haste targets

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#102]
As a user, I would like to be able to use @set to define a custom list of haste targets.

This will be beneficial for:

- Dual Khanjari rogues
- Fighter types without linked mail
- Will prevent unnecessary hasting: of targets wearing perm haste, rangers that don't have linked mail but use archery,
- Non-zone impacting but still fun: silly anon types in xp trains, extra skill prac in xp trains by being able to haste everyone

**Comment by Gyrx** [comment]
The custom @set list could also be re-purposed for other common scenarios for spells in zones:

- Split auto-res targets between clerics in tiamat
- Split vit targets
- Custom globe targets (good aligned fighter/rogues in tiamat top grid)

**Comment by Nyyrazzilyss** [comment]
As to when would be another question, but at some point in time i'm going to change the spell counters in the group window to be selectable buttons to enable/disable specific spells on individual targets.

As such, while what you described is certainly doable (by someone else), I won't be.
