### ISSUE TITLE
Ranger Problems

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#104]
randomly just wont use abilities. just stops. reinstalled. turned off and on. been doing this for over a month. usually restarting client fixes.. not anymore. also if u have a trigger to swap from bow to melee or vise versa it will confuse sweeping strike and knockdown shot. knockdown shot will be on bar when melee and sweeping strike when ranged.

< 478h/478H 110v/110V **|3|3|3|0|** T: Relith TC: few scratches E: chultean EC: few wounds EP: std P: std > 
[Sweeping Strike]
The Chultean slaver looks strong again.
You sweep attack the Chultean slaver with unbound fury, knocking him off balance!

< 478h/478H 110v/110V |3|3|3|0| T: Relith TC: few scratches E: chultean EC: few wounds EP: rcl P: std > 

Your massive bludgeon barely wounds the Chultean slaver.
Your massive slash barely wounds the Chultean slaver.
Your massive bludgeon barely wounds the Chultean slaver.
Relith barely wounds the Chultean slaver with his massive slash.
Relith barely wounds the Chultean slaver with his massive icy slash.
Relith barely wounds the Chultean slaver with his massive slash.
Relith barely wounds the Chultean slaver with his massive icy slash.
Relith barely wounds the Chultean slaver with his massive slash.
The Chultean slaver misses Relith with his hit.
The Chultean slaver misses Relith with his hit.

< 478h/478H 110v/110V |3|3|3|0| T: Relith TC: excellent E: chultean EC: nasty wounds EP: rcl P: std > 

The Chultean slaver closes the gap in his defenses.

< 478h/478H 110v/110V |3|3|3|0| T: Relith TC: excellent E: chultean EC: nasty wounds EP: rcl P: std > 
[Eviscerate]
You swing your weapons in lethal arcs, dousing the area with the Chultean slaver's blood.
The Chultean slaver is weakened!

< 478h/478H 110v/110V |3|3|3|0| T: Relith TC: excellent E: chultean EC: nasty wounds EP: rcl P: std > 

Your massive bludgeon barely wounds the Chultean slaver.
Your massive slash slightly wounds the Chultean slaver.
You miss the Chultean slaver with your bludgeon.
Your massive bludgeon slightly wounds the Chultean slaver.
Relith slightly wounds the Chultean slaver with his massive slash.
Relith slightly wounds the Chultean slaver with his massive icy slash.
Relith slightly wounds the Chultean slaver with his massive slash.
Relith slightly wounds the Chultean slaver with his massive icy slash.
The Chultean slaver misses Relith with his hit.
The Chultean slaver misses Relith with his hit.

< 478h/478H 110v/110V **|3|3|3|0|** T: Relith TC: excellent E: chultean EC: pretty hurt EP: rcl P: std > 

You miss the Chultean slaver with your bludgeon.
You miss the Chultean slaver with your slash.
You miss the Chultean slaver with your bludgeon.
Relith badly wounds the Chultean slaver with his massive slash.
Relith slightly wounds the Chultean slaver with his massive icy slash.
Relith severely wounds the Chultean slaver with his massive slash.
Relith slightly wounds the Chultean slaver with his massive icy slash.
Relith badly wounds the Chultean slaver with his massive slash.
Relith slightly wounds the Chultean slaver with his massive slash.
The Chultean slaver misses Relith with his hit.
The Chultean slaver misses Relith with his hit.
The Chultean slaver clambers to his feet.
[Sweeping Strike]

< 478h/478H 110v/110V |3|3|3|0| T: Relith TC: excellent E: chultean EC: pretty hurt EP: std P: std >

**Comment by Nyyrazzilyss** [comment]
Version? From the format of '[Sweeping Strike]' etc from the log, this is an old version

**Comment by i982** [comment]
i figured out the problem, it does it in newest version as well. if you have auto heal turned on it disables the casting of all the other spells. not sure if its because im not high enough level to the entire prompt unlocked or what.

**Comment by Nyyrazzilyss** [comment]
I'll take a look, but it shouldn't. Autoheal does however reserve 1 spell in circles with healing spells. If you only have 1 spell in that circle, it would prevent casting any damage spells for that circle.

**Comment by Nyyrazzilyss** [comment]
Attempted to duplicate had some other people try also, couldn't duplicate
