### ISSUE TITLE
ranged melee to ranged

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#106]
once i swap from melee to ranged the bar still thinks im using a bow and will now be confused and when i go back to bow it stays with sweeping strikes. back to melee it swaps to knockdown shot on the bar.

also if you notice.. its still not using 1st tier spells. it just stops. i dont know what log to post to show you but it just stops using first circle spells altogether. been about 10 minutes in seelie now and still not 1 fist first circle spell. and yes it is turned on on the bar.

Rrissun completes his spell...

< 924h/924H 110v/110V |3|1|0|1|0| P: std > 
Lilabipple starts casting a spell called 'Globe of Invulnerability'

< 924h/924H 110v/110V |3|1|0|1|0| P: std > 

Lilabipple completes her spell...
You begin to shimmer.
@melee
rem bow;wield scepter;wield moonblade;wield moonblade;put bow portable

[Vitality has expired on Ithax.]
< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You stop using the rune-covered fiery warbow of hellish fury.[Setting autocast to true]
[Setting rescuetype to off]

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You wield the mighty scepter of valhalla.[Setting autocast to true]
[Setting rescuetype to off]

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You do not seem to have the 'moonblade'.

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You do not seem to have the 'moonblade'.

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You put the rune-covered fiery warbow of hellish fury into a portable hole on your person.
Ithax group-says '[[ VIT OUT ]]'
[Vitality has expired on Ithax.]

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You are not using it.

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You do not seem to have the 'scepter'.

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You wield a rune graven adamantine longsword.[Setting autocast to true]
[Setting rescuetype to off]
Rrissun starts casting a spell called 'Vitality'

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

You don't have the bow.

< 924h/924H 110v/110V |3|1|0|1|0| P: std >

**Comment by i982** [comment]
well now now it believes im stuck in ranged even with melee weapons...

They have to be standing up for you to do that!

[Splintering Shot] SP

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std >

Rrissun barely wounds a young faerie acolyte with his average bludgeon.
Rrissun is burned severely as he hits a young faerie acolyte!
Agaerot is burned severely as he hits a young faerie acolyte!
Manorak's attack only grazes a young faerie acolyte as he dodges aside!
Manorak's attack only grazes a young faerie acolyte as he dodges aside!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
Your attack only grazes a young faerie acolyte as he dodges aside!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
A young faerie acolyte misses a gray slaad with his nip.
A young faerie acolyte misses a gray slaad with his nip.
A young faerie acolyte misses a gray slaad with his nip.
A gray slaad misses a young faerie acolyte with its strike.
A gray slaad misses a young faerie acolyte with its strike.
You need to wield a bow to do that.

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std > 

Vomig completes his spell...
Vomig summons the spirits of his ancestors to protect the group.
A shimmering spiritual shield hovers over you.
Manorak attacks a young faerie acolyte with both weapons, landing twin precision strikes.

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std > 
Agaerot starts casting an offensive spell called 'Creeping Doom'

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std > 
Manorak starts casting a spell called 'Blades of Fire'

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std > 
Azhel completes his spell...
Azhel utters the words, 'baizgpahhzf'.
Azhel's magic collides with a young faerie acolyte's body, causing bones to weaken and crack!

ss
< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std >

Manorak completes his spell...
Manorak's weapons burst into searing white-hot flames.
They have to be standing up for you to do that!

ss
< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: few wounds E: acolyte EC: nasty wounds EP: sit P: std >

They have to be standing up for you to do that!

[Concussive Shot] CN

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: small wounds E: acolyte EC: nasty wounds EP: sit P: std >

You need to wield a bow to do that.

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: small wounds E: acolyte EC: nasty wounds EP: sit P: std > 

Agaerot sends out an almost endless carpet of arachnoids and insects to kill a young faerie acolyte.
Rrissun starts casting an offensive spell called 'Unholy Word'

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: small wounds E: acolyte EC: nasty wounds EP: sit P: std > 

[Triple Shot] TR
Rrissun completes his spell...
Rrissun sends a young faerie acolyte reeling with an unholy word.
You need to wield a bow to do that.

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: small wounds E: acolyte EC: nasty wounds EP: sit P: std > 
Your magic armor fades away.

< 924h/924H 110v/110V |3|0|3|0|2| T: gray TC: small wounds E: acolyte EC: nasty wounds EP: sit P: std >

A gray slaad looks really sick, and shivers uncomfortably.
Rrissun is burned severely as he hits a young faerie acolyte!
Manorak's attack only grazes a young faerie acolyte as he dodges aside!
Manorak slightly wounds a young faerie acolyte with his massive flame-enshrouded slash.
Manorak slightly wounds a young faerie acolyte with his massive flame-enshrouded slash.
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault!
The globe around your body flares as it bears the brunt of a young faerie acolyte's assault


You are using:
<worn as a badge>    the badge of the Knights of Volheru (damaged)
<worn on head>       iron crown of the fire giant warlords (damaged)
<worn on eyes>       blazing yellow eyes (illuminating) (damaged)
<worn in ear>        a tiny earring of congealed blood (damaged)
<worn in ear>        a tiny earring of congealed blood (damaged)
<worn on face>       the mask of the scorpion (damaged)
<worn around neck>   a burnished iron necklace covered in runes (damaged)
<worn around neck>   a burnished iron necklace covered in runes (damaged)
<worn on body>       a suit of ancient banded steel armor (damaged)
<worn about body>    a mantle of interlocking silversaan plates (damaged)
<worn as quiver>     an ancient tooled dragonhide quiver (damaged)
<worn about waist>   a thick girdle of silver dragonhide with adamantine bolsters (damaged)
<worn on arms>       some blood-stained leather sleeves with mithril studs (damaged)
<worn around wrist>  a darkwood bracer covered in glowing sigils (damaged)
<worn around wrist>  a darkwood bracer covered in glowing sigils (damaged)
<worn on hands>      a pair of razor ridged green dragonscale gauntlets (damaged)
<worn on finger>     a flaming ring of the efreeti (damaged)
<worn on finger>     a flaming ring of the efreeti (damaged)
<primary weapon>     the mighty scepter of valhalla (glowing) (damaged)
<secondary weapon>   a rune graven adamantine longsword (glowing) (damaged)
<worn on legs>       a pair of djinn battle greaves (damaged)
<worn on feet>       a pair of taut red leather boots with adamantine buckles (damaged)

< 924h/924H 110v/110V |3|0|3|0|2| T: Amenae TC: few wounds E: sysoria EC: few wounds EP: rcl P: std > 

**[Hail of Arrows] HA**

Rrissun starts casting a spell called 'Healing Aura'

< 924h/924H 110v/110V |3|0|3|0|2| T: Amenae TC: few wounds E: sysoria EC: few wounds EP: rcl P: std >

**You need to wield a bow to do that.**
Manorak spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Manorak rains a series of deadly blows on the faerie Princess, Sysoria!

< 924h/924H 110v/110V |3|0|3|0|2| T: Amenae TC: few wounds E: sysoria EC: few wounds EP: rcl P: std >

**Comment by Nyyrazzilyss** [comment]
It's the (damaged) after the item name, will fix

**Comment by i982** [comment]
ahh ok. yeah i made a alias based off of your log in check. which is more or less a refresh button.

**Comment by Nyyrazzilyss** [comment]
1/20 dev
