### ISSUE TITLE
Add to existing trigger - skill messages when mob leaves room to restart train

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#108]
The XP Train recovers when ranger powers don't find a mob in the room, but need other messages added for when other skills are attempted to be used on a mob that has left the room.

**Existing Trigger name:**
(.*) is dead! R.I.P. ^Your blood freezes as you hear the rattling death cry of (.*)[.]

**Add to Trigger off of:**
Bash: 
- They're not here!

Kill: 
- I don't see that person here.

Backstab/Circle/Trip/Headbutt: 
- You don't see them here!

**Comment by Nyyrazzilyss** [comment]
1/20 dev
