### ISSUE TITLE
Ashstone Train - Insane Man interrupted fwalk and broke train

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#11]
Log:
You group-say '[Moving to: Gambler (87263)  <.sw2n4wsws>]'
< 1151h/440H 122v/130V P: std > 
#fwalk 87263
[Path: .sw2n4wsws]
s
w
n
n
w
w
w
w
s
w
s
Along the Edge of the Market
   Ashstone's market starts here and sprawls to the south running near the
river bank.  This particular part of the market sees a lot of traffic from
people coming from here to there.  To the west lies the road leading out of
the market.  To the north lies the sturdy and stately building that houses
Ashstone's Depository.  To the east lies the river that marks the city's
eastern boundary, and office to many a hopeful fisher.
Exits: - North - East  - South - West                  [87414] 
An insane man is standing here, cowering.
Dizag enters from the north.
Zissar flies in from the north.

< 1147h/440H 122v/130V P: std >

An insane man misses you with his hit.
Sorry, you aren't allowed to do that in combat.

< 1146h/440H 122v/130V T: Ezdad TC: excellent E: insane EC: excellent EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 1145h/440H 122v/130V T: Ezdad TC: excellent E: insane EC: excellent EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 1145h/440H 122v/130V T: Ezdad TC: excellent E: insane EC: excellent EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 1144h/440H 122v/130V T: Ezdad TC: excellent E: insane EC: excellent EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 1143h/440H 122v/130V T: Ezdad TC: excellent E: insane EC: excellent EP: std P: std >

You score a CRITICAL HIT!
An insane man slumps to the ground.
You successfully pierce an insane man, his lifeless body falls to the ground.
an insane man is dead! R.I.P.
An insane man slumps to the ground.
You receive 1 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of an insane man.[Current room not expected]
87414

87263

#fwalk 87263
[Can't fwalk while in combat]
On the Edge of the Marketplace
   Stones have been laid here on this north-south road leading to and from the
market.  The stones are just enough to provide for a single wagon to pass in
each directions without becoming bogged down in the mud.  No such luxury exist
for pedestrians.  A stone path extends out from a tower to the west,
perfectly fitted and joining with the wagon tracks.  The stone tower is the
perfect phallic symbol of the power it represents.
Exits: - North - East  - South - West                  [87394] 
Somebody's revolting little child is standing here.
Dizag enters from the east.
Zissar flies in from the east.

< 1142h/440H 122v/130V P: std >

On the Path to the Forbidden Tower
   White marble stones have been laid down here leading from the 
street west into an enormous tower.  The path has been flanked 
on either side by flower gardens.  Decorative fences protect the 
flowers from errant steps and guide visitors toward the tower.  
The tower's gleaming surface helps light to find the path making 
< 1141h/440H 121v/130V P: std >

Alas, you cannot go that way. . . .

< 1140h/440H 121v/130V P: std >

Entrance to the Forbidden Tower
   Called the forbidden tower it is home to Ashstone's high mage.  The 
light in the tower seems to be coming from everywhere but nowhere in 
particular.  Finely polished to a mirror finish the marble floor gleams in 
the light.  This large entry hall exists as a meeting area for guests to 
the tower.  Velvet lined seats line the walls providing a place to sit 
down.
Exits: - North - East  - West          [87396] 
Dizag enters from the east.
Zissar flies in from the east.

< 1139h/440H 120v/130V P: std >

Alas, you cannot go that way. . . .

< 1139h/440H 120v/130V P: std >

Who do you want to trip?

< 1138h/440H 121v/130V P: std >

You do not see or have the corpse.

< 1138h/440H 121v/130V P: std >

Entrance to the Forbidden Tower
Exits: - North - East  - West          [87396] 
Zissar  (Yuan-Ti) stands in mid-air here.
Dizag  (Drow Elf) stands here.

< 1137h/440H 121v/130V P: std > 

gsay hah
You group-say 'hah'
l

< 1004h/440H 130v/130V P: std >

**Comment by Nyyrazzilyss** [comment]
Might be fixed in 011dev 07-17. Completely untested. Re-open a new ticket if persists.
