### ISSUE TITLE
Regex not recognizing time present in prompt

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#112]
Toggling on and off the "Bless" button for Harmonious Blessing autobless and no affect is observed other than the button highlighting and un-highligting.

Spammy log below. In the times I'm typing score and status i'm toggling the Bless button on and off.

I took a look at the code and everything looks to be okay, but it might be hooked to some other now dead code (or something?).

Log:

< 1132h/1052H 187p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: std P: std Sat Dec
30 22:12:04 2017 >

You feel less in tune with your body!

< 1132h/1052H 187p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: std P: std Sat Dec
30 22:12:05 2017 >

Lilabipple completes her spell...
Lilabipple sends a shimmering swarm of needles ripping into a githyanki priest!
A githyanki priest is mortally wounded, and will die soon, if not aided.
A githyanki priest slumps to the ground.
Lilabipple's swarm of needles tears a githyanki priest's body apart, leaving a lifeless heap.
a githyanki priest is dead! R.I.P.
A githyanki priest slumps to the ground.
You receive 30,796 XP (0.10%) experience.
Your blood freezes as you hear the rattling death cry of a githyanki priest.

< 1131h/1052H 188p/493P 132v/132V P: std Sat Dec 30 22:12:06 2017 >

Illandriel gets a small pile of coins from corpse of a githyanki priest.
The corpse of a githyanki priest does not contain the coins.

< 1131h/1052H 188p/493P 132v/132V P: std Sat Dec 30 22:12:06 2017 >

Adud slightly wounds a red dragon with his massive bludgeon. (x3)
Huzaz springs from the ground like a leopard, coming up into a fighting stance!
A githyanki priest clambers to his feet.

< 1131h/1052H 188p/493P 132v/132V P: std Sat Dec 30 22:12:07 2017 >

Pidibeple completes his spell...
Pidibeple summons a fearsome meteor swarm!
Pidibeple crushes a githyanki priest with his swarm of fiery meteors.
Pidibeple crushes a red dragon with his swarm of fiery meteors.
You assist Lilabipple heroically.
Your attack glances harmlessly off of a red dragon's scales!

< 1131h/1052H 188p/493P 132v/132V T: Adud TC: small wounds E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:07 2017 >

< 1131h/1052H 188p/493P 132v/132V T: Adud TC: small wounds E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:07 2017 >
Vomig completes his spell...
Vomig summons a healing light that surround the entire group.

< 1130h/1052H 188p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:08 2017 >
Pirekoble staggers about, but manages to get to his feet.

< 1130h/1052H 188p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:08 2017 >
Lilabipple starts casting an offensive spell called 'Feeblemind'

< 1130h/1052H 189p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:08 2017 >

Pidibeple starts casting an offensive spell called 'Force Missiles'

< 1130h/1052H 189p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:10 2017 >

< 1129h/1052H 189p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:10 2017 >
Risor does an acrobatic maneuver in battle, and trips up a githyanki priest!

< 1129h/1052H 189p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: knl P: std
Sat Dec 30 22:12:10 2017 >

Risor slightly wounds a githyanki priest with his massive pierce. (x2)
Your attack glances harmlessly off of a red dragon's scales!
As Fisig draws his whip back it hisses and takes on a bright red aura.
With lightning speed the three heads streek toward a red dragon and dig
deeply into its flesh leaving steaming black lacerations.
Fisig slightly wounds a red dragon with his awesome slash. (x3)
Adud slightly wounds a red dragon with his massive bludgeon. (x2)
Adud's shield glows brightly as it steals some lifeforce
from a red dragon.
Adud blocks a red dragon's attack with his shield!
A red dragon rises to its feet.
Huzaz blocks a githyanki priest's attack with his shield!

< 1129h/1052H 189p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: std P: std
Sat Dec 30 22:12:11 2017 >

< 1129h/1052H 190p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: std P: std
Sat Dec 30 22:12:12 2017 >

Pirekoble's senses seem to clear again!
Huzaz's senses seem to clear again!
Lilabipple completes her spell...

< 1129h/1052H 190p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: pretty hurt EP: std P: std
Sat Dec 30 22:12:12 2017 >

Pidibeple completes his spell...
Pidibeple sends a powerful force missile slamming into a red dragon, who staggers in pain! (x3)

< 1128h/1052H 190p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:13 2017 >

Pirekoble starts casting an offensive spell called 'Incendiary Cloud'

< 1128h/1052H 190p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:14 2017 >
[Adud : the mystical circlet of the coiled serpent]
Adud badly wounds a red dragon with his awesome bludgeon.

< 1128h/1052H 190p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:14 2017 >
< 1128h/1052H 191p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:15 2017 >
Risor slightly wounds a githyanki priest with his massive pierce. (x4)
Your powerful pierce slightly wounds a red dragon.
Fisig severely wounds a red dragon with his massive slash. (x4)
Huzaz slightly wounds a githyanki priest with his massive bludgeon.
Adud wounds a red dragon harshly with his massive bludgeon.
Adud badly wounds a red dragon with his powerful bludgeon. (x2)
Adud blocks a red dragon's attack with his shield!
Huzaz blocks a githyanki priest's attack with his shield!
A githyanki priest barely wounds Huzaz with his weak bludgeon.

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:15 2017 >

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:15 2017 >
Pidibeple starts casting an offensive spell called 'Force Missiles'

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: few scratches E: dragon EC: awful EP: std P: std Sat
Dec 30 22:12:16 2017 >

sco
You finish a verse of the song of healing.

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:16 2017 >
Score information for Tronik

Level: 50 Race: Half-Orc Class: Battlechanter
Hit points: 1127(1052) PSP's: 191(493) Moves: 132(132)
Experience Progress: 1057 %
Coins carried: 76 platinum 122 gold 32 silver 7 copper
Coins in bags: 5849 platinum 1718 gold 590 silver 553 copper
Coins in bank: 4540 platinum 3903 gold 3214 silver 4968 copper
Prestige: 7292 Acheron Kill Count: 0
Citizen of: Baldur's Gate
Outcast from: Leuthilspar
Playing time: 25 days / 11 hours / 15 minutes
Title:
Group Name: Lilabipple and Company
Group Leader: Lilabipple
Status: Standing, fighting a red dragon.
Singing
Detecting: Invisible Life Heat
Enchantments: No Charm No Summon

Active Powers:
Vitality

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:16 2017 >

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:17 2017 >
Lilabipple starts casting a spell called 'Energy Shield'

< 1127h/1052H 191p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:17 2017 >

att
[Fisig : the mystical circlet of the coiled serpent]
Fisig brutally wounds a red dragon with his massive slash. (x2)
Fisig severely wounds a red dragon with his powerful slash.
A red dragon staggers from Fisig's massive slash!
Fisig severely wounds a red dragon with his average slash.

< 1126h/1052H 192p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:18 2017 >
Character attributes for Tronik

Level: 50 Race: Half-Orc Class: Battlechanter
Age: 55 yrs / 11 mths Size: Medium
STR: 98 AGI: 112 DEX: 92 CON: 74
POW: 70 INT: 70 WIS: 70 CHA: 104
Armor Class: -54 (100 to -100) Agility Bonus: -25
Magic Resistance: 0 percent
Hitroll: 31 Damroll: 66
Alignment: Chaotic Neutral
Saving Throws: PAR[-2] ROD[0] PET[0] BRE[-2] SPE[0]
Wimpy: 300
Load carried: Light
Damage Resistance:
Unarmd: 0% Slash : 3% Bludgn: 3% Pierce: 3% Range : 3%
Spells: 0% Fire : 25% Cold : 20% Elect : 15% Acid : 25%
Sonic : 0% Poison: 10% Pos : 0% Neg : 0% Psi : 0%
Mental: 0% Good : 0% Evil : 0% Law : 0% Chaos : 0%
Force : 0%

< 1126h/1052H 192p/493P 132v/132V T: Adud TC: excellent E: dragon EC: awful EP: std P: std Sat Dec
30 22:12:18 2017 >
Pidibeple completes his spell...
Pidibeple sends a powerful force missile slamming into a red dragon, who staggers in pain!
Pidibeple's powerful force missile impacts a red dragon and rips its body in half!
a red dragon is dead! R.I.P.
You receive 18,583 XP (0.06%) experience.
Your blood freezes as you hear the rattling death cry of a red dragon.
A githyanki priest stops following a red dragon.

< 1126h/1052H 192p/493P 132v/132V P: std Sat Dec 30 22:12:19 2017 >
Risor slightly wounds a githyanki priest with his massive pierce. (x3)
status me
Risor slightly wounds a githyanki priest with his massive pierce.
A githyanki priest clambers to his feet.
Fisig gets a small pile of coins from corpse of a red dragon.
The corpse of a red dragon does not contain the coins.
Risor clambers to his feet.

< 1126h/1052H 192p/493P 132v/132V P: std Sat Dec 30 22:12:19 2017 >
Status of Tronik
Effects
detect invisible infravision no charm
no summon protection from evil sense life
sneak

Spells
Vitality ( 5:23)
Risor does an acrobatic maneuver in battle, and trips up a githyanki priest!

< 1126h/1052H 192p/493P 132v/132V P: std Sat Dec 30 22:12:20 2017 >

Fisig assists Huzaz heroically.
Fisig slightly wounds a githyanki priest with his massive slash.
You assist Huzaz heroically.

< 1126h/1052H 192p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: rcl P: std Sat Dec
30 22:12:20 2017 >
Pirekoble completes his spell...
Billowing clouds of incendiary gases pour from Pirekoble's fingertips!
Pirekoble cackles as his incendiary cloud torches a githyanki priest!
Lilabipple completes her spell...

< 1126h/1052H 192p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: rcl P: std Sat Dec
30 22:12:20 2017 >

< 1125h/1052H 192p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: rcl P: std Sat Dec
30 22:12:20 2017 >

Pidibeple starts casting an offensive spell called 'Force Missiles'

< 1125h/1052H 193p/493P 132v/132V T: Huzaz TC: excellent E: priest EC: awful EP: rcl P: std Sat Dec
30 22:12:22 2017 >
hbl

Your massive pierce wounds a githyanki priest harshly.
Fisig wounds a githyanki priest harshly with his massive slash. (x2)
Fisig's a battleaxe dripping with fresh blood starts humming louder and louder. Suddenly
the axehead reshapes into a powerful maw and bites a githyanki priest in the throat. Blood flows
between the canine jaws and spills to the ground and a githyanki priest howls in pain. With
a satisfied grin, the maw reverts back to an axehead.
Fisig brutally wounds a githyanki priest with his massive slash.
Fisig critically wounds a githyanki priest with a massive slash!
Fisig enshrouds a githyanki priest in a mist of blood with his massive slash!
Risor critically wounds a githyanki priest with a powerful pierce!
Risor pierces a githyanki priest, whose body falls lifeless to the ground.
a githyanki priest is dead! R.I.P.
You receive 30,047 XP (0.10%) experience.
Your blood freezes as you hear the rattling death cry of a githyanki priest.
Pidibeple stops invoking abruptly!

< 1124h/1052H 193p/493P 132v/132V P: std Sat Dec 30 22:12:23 2017 >
Pidibeple gets a small pile of coins from corpse of a githyanki priest.

< 1124h/1052H 193p/493P 132v/132V P: std Sat Dec 30 22:12:23 2017 >
That person is not fighting anyone.

< 1124h/1052H 193p/493P 132v/132V P: std Sat Dec 30 22:12:24 2017 >

< 1124h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:24 2017 >
< 1124h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:25 2017 >

You start chanting... [Casting: LOOK ()]

< 1124h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:25 2017 >

You're busy spellcasting! [command: LOOK]

< 1124h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:25 2017 >

You're busy spellcasting! [command: LOOK]

< 1124h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:25 2017 >

Lilabipple group-says 'memorization'

< 1123h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:26 2017 >
Lilabipple opens an ancient tome and begins studying it intently.

< 1123h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:26 2017 >
Illandriel sits down in a comfortable spot.

< 1123h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:27 2017 >
Fisig sits down in a comfortable spot.
Pidibeple opens an ancient tome and begins studying it intently.
Illandriel takes out his holy symbol and begins praying intently.

< 1123h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:27 2017 >
Casting: Harmonious Blessing
Fisig takes out his unholy symbol and begins praying intently.

< 1123h/1052H 194p/493P 132v/132V P: std Sat Dec 30 22:12:27 2017 >

You complete your spell... [Completed spell: LOOK ()]
Your body becomes more in tune with your mind!

< 1123h/1052H 195p/493P 132v/132V P: std Sat Dec 30 22:12:28 2017 >

You finish a verse of the song of healing.
Pirekoble sits down in a comfortable spot.

< 1122h/1052H 195p/493P 132v/132V P: std Sat Dec 30 22:12:28

**Comment by Nyyrazzilyss** [comment]
Time present in prompt is not being picked up with the regex

**Comment by Nyyrazzilyss** [comment]
< (?:(\d+)h)?\/?(?:(\d+)H)? ?(?:(\d+)p)?\/?(?:(\d+)P)? ?(?:(\d+)v)?\/?(?:(\d+)V)? ?[\|]?((?:[a-z]+ [0-9+]+\|)+)? ?[\|]?((?:[0-9 ]\|)+)? ?(?:T: ([A-Za-z ]+))? ?(?:TC: ([A-Za-z ]+))? ?(?:E: ([A-Za-z ]+))? ?(?:EC: ([A-Za-z ]+))? ?(?:EP: ([A-Za-z ]+))? (?:P: (.*)) .*>

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
