### ISSUE TITLE
Missing room: Northern Dock of the Luskan Ferry

### ISSUE THREAD

**Issue by Fisig** [Nyyrazzilyss/NyyLIB#113]
disem
You disembark this ship.
Northern Dock of the Luskan Ferry
Room size: Large (L:25 ft  W:50 ft  H:500 ft)
Exits: -S -W           [85159] 
The Mirar ferry rests on the river here. (illuminating)
A ferry guardsman stands here alertly watching for enemies.(Red Aura)
A ferry guardsman stands here alertly watching for enemies.(Red Aura)
A junior wizard of the Arcane Brotherhood stands here watching the land.(Red Aura)

< 650h/650H 120v/120V |3|3|3|3|1| P: std > 

[Searching... No matches found: Northern Dock of the Luskan Ferry]
scan

You scan south...
On the River Mirar (Water)
Room size: Very large (L:40 ft  W:80 ft  H:500 ft)
Exits: -N -S

You scan west...
Path Along the River Mirar
Room size: Large (L:30 ft  W:75 ft  H:500 ft)
Exits: -N -E
A caribou stands here searching for food on the barren tundra.

< 650h/650H 120v/120V |3|3|3|3|1| P: std > 
@find

[Searching... Solve scan failed. Multiple (0) matches found]
l
Northern Dock of the Luskan Ferry
Room size: Large (L:25 ft  W:50 ft  H:500 ft)
Exits: -S -W                [Map not in sync, type @find or scan to attempt resync] 
The Mirar ferry rests on the river here. (illuminating)
A ferry guardsman stands here alertly watching for enemies.(Red Aura)
A ferry guardsman stands here alertly watching for enemies.(Red Aura)
A junior wizard of the Arcane Brotherhood stands here watching the land.(Red Aura)

< 650h/650H 120v/120V |3|3|3|3|1| P: std >

**Comment by Nyyrazzilyss** [comment]
1/20 dev
