### ISSUE TITLE
Missing rooms: Jungle Village of the Batiri

### ISSUE THREAD

**Issue by Fisig** [Nyyrazzilyss/NyyLIB#115]
Near the Entrance to a Dark Tunnel
Room size: Large (L:50 ft  W:50 ft  H:50 ft)
Exits: -E -S -W        [47310] 

3 rooms west, 1 south (?, aggro to my newbling so not going to double check) missing.

**Comment by Nyyrazzilyss** [comment]
It is present, but because the rooms leading to it are all permanently dark the map likely has issues keeping sync
