### ISSUE TITLE
Poison for Rogues

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#116]
no idea.

Jibbi group-says '[Attacking: Elaith]'

< 741h/660H 111v/111V P: std > 
Jibbi places a ravenous dagger honed to a razor's edge in the back of Elaith Waterstill, resulting in some strange noises and some blood.
Jibbi places a red dragon fanged dagger in the back of Elaith Waterstill, resulting in some strange noises and some blood.
Elaith Waterstill misses Jibbi with his hit.

< 741h/660H 111v/111V P: std >

You can't carry any more.

< 741h/660H 111v/111V P: std >

You generously apply poison to an enchanted khanjari dagger.

< 741h/660H 111v/111V P: std >

Nuttel assists Jibbi heroically.
Nuttel misses Elaith Waterstill with his bludgeon.
You put a vial of black liquid into a portable hole on your person.

< 740h/660H 111v/111V P: std >

You get a vial of black liquid from a portable hole.

< 740h/660H 111v/111V P: std >

You generously apply poison to a red dragon fanged dagger.

< 740h/660H 111v/111V P: std >

You put a vial of black liquid into a portable hole on your person.

< 740h/660H 111v/111V P: std >

< 740h/660H 111v/111V P: std > 

Nuttel misses Elaith Waterstill with his bludgeon.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Jibbi barely wounds Elaith Waterstill with his awesome pierce.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Elaith Waterstill dodges Jibbi's attack.
Elaith Waterstill misses Jibbi with his hit.

< 739h/660H 111v/111V P: std >

You get a vial of black liquid from a portable hole.

< 739h/660H 111v/111V P: std >

That item has already been poisoned!

< 739h/660H 111v/111V P: std >

You put a vial of black liquid into a portable hole on your person.

< 739h/660H 111v/111V P: std >

You get a vial of black liquid from a portable hole.

< 739h/660H 111v/111V P: std >

That item has already been poisoned!

< 739h/660H 111v/111V P: std >

You put a vial of black liquid into a portable hole on your person.

< 739h/660H 111v/111V P: std >

< 739h/660H 111v/111V P: std > 

Jibbi does an acrobatic maneuver in battle, and trips up Elaith Waterstill!
[bs Waterstill]

< 738h/660H 111v/111V P: std >

You get a vial of black liquid from a portable hole.

< 738h/660H 111v/111V P: std >

Nuttel misses Elaith Waterstill with his bludgeon.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Jibbi's attack only grazes Elaith Waterstill as he dodges aside!
Jibbi barely wounds Elaith Waterstill with his awesome pierce.
Jibbi barely wounds Elaith Waterstill with his massive pierce.
Jibbi dodges Elaith Waterstill's attack.
That item has already been poisoned!

< 738h/660H 111v/111V P: std >

You put a vial of black liquid into a portable hole on your person.

< 737h/660H 111v/111V P: std >

You get a vial of black liquid from a portable hole.

< 737h/660H 111v/111V P: std >

That item has already been poisoned!

< 737h/660H 111v/111V P: std >

You put a vial of black liquid into a portable hole on your person.

< 737h/660H 111v/111V P: std >

< 809h/810H 111v/111V T: Jibbi TC: few scratches E: forell EC: nasty wounds EP: rcl P: std > 
[Attacking with circle]
You are carrying:
[9] a vial of black liquid
a portable hole (illuminating)

**Comment by Nyyrazzilyss** [comment]
Unfortunately, this doesn't surprise me. Rogue/A-P/poison is relatively incomplete.

**Comment by i982** [comment]
zmud used to have conditions that once met would stop triggers/aliases and then reactivate them after combat. dunno if mudlet has a similar style of condition settings or not. the way i solved this was to just made a trigger to poison weapons after combat.

**Comment by Nyyrazzilyss** [comment]
With the change allowing poison to be applied directly from a container, this is no longer an issue.
