### ISSUE TITLE
Add direction to tank countdown

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#117]
Helpful when map isn't up.

**Comment by Nyyrazzilyss** [comment]
You group-say '<5> to movement N'
You group-say '<4> to movement N'
You group-say '<3> to movement N'
You group-say '<2> to movement N'
You group-say '<1> to movement N'
You group-say '< ATTACKING Tiamat N! >'

**Comment by Nyyrazzilyss** [comment]
function countdown()
	NyyLIB.countdown = NyyLIB.countdown - 1

	if NyyLIB.countdown > 0 then
		mud:send("GSAY <" .. NyyLIB.countdown .. "> to movement" .. string.upper(tostring(NyyLIB.countdir)) )
		tempTimer(1, [[countdown()]])
	else
		mud:send("GSAY < ATTACKING " .. string.title(tostring(NyyLIB.target)) .. string.upper(tostring(NyyLIB.countdir)) .. "! >" )
		
		expandAlias("movea " .. NyyLIB.countdir, false)

		if NyyLIB.target ~= nil then
			mud:send("KILL " .. NyyLIB.target)
		else
			mud:send("HITALL all")
		end
	end
end

**Comment by CountVooku** [comment]
Thanks, I got mine to say the first number in the countdown but wouldn't continue.

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
