### ISSUE TITLE
Aborting at completion of every group heal

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#118]
Casting: Group Heal *

< 952h/1066H 136v/136V P: std > 

You complete your spell... [Completed spell: GH (Group Heal)]
abort
You summon a healing light that surrounds the entire group.
Your body warms as your wounds are healed.

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev

**Comment by Nyyrazzilyss** [comment]
ok wasn't, but fixed it again :)

**Comment by Nyyrazzilyss** [comment]
maybe fixed 2/3 dev
