### ISSUE TITLE
gagging automation reports eg: @gag [ or @gag ]

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#125]
does not erase line
erases it from the small capture window, but not main mud

short log:
< 675h/675H 110v/110V |0|1|1|1|1| T: Jazzez TC: few scratches E: noble EC: nasty wounds EP: sit P:
std > 
Jazzez group-says '[Ashstone Noble has nasty wounds!]'
< 675h/675H 110v/110V |0|1|1|1|1| T: Jazzez TC: few scratches E: noble EC: nasty wounds EP: sit P:
std > 
Usage:
 @gag text to gag
 #gag reset
Existing gags:
{
  "["
}

< 675h/675H 110v/110V |0|1|1|1|1| T: Jazzez TC: few scratches E: noble EC: pretty hurt EP: sit P:
std >

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
