### ISSUE TITLE
wormhole in dev

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#126]
wormhole tell triggers all disabled in dev
attempted to recreate them only to have
them disabled by something else

**Comment by i982** [comment]
yeah i noticed this as well. its ones thing to turn them off yourself or to only let your guild use them or whatever but to punish everyone who you push to download your script? thats just hurting the entire mud. you are now hurting zoning. leaders. people who trust you to install your script to their computers. creating your ui addon to help players i thought was the idea. but clearly it is no longer the case.

**Comment by zenevan** [comment]
I'm sure he didn't mean it.

**Comment by i982** [comment]
well he pushes his script like a drug to new players over the newbie help channel. i will make sure to also notify them that there is a hidden agenda behind it to hurt them later in the game.

**Comment by Nyyrazzilyss** [comment]
dev has bugs. If you can't accept that, don't use it.

**Comment by i982** [comment]
you making things not work deliberately because you are butthurt isnt a bug. you can see it in the script where you purposely made it not work. and i wont be anymore.

**Comment by Nyyrazzilyss** [comment]
Due to lack of understanding that the development script ISN'T STABLE and WILL HAVE BUGS, it's no longer being made available.

**Comment by i982** [comment]
good good thats great! cant wait to see the next version you make to hurt the playerbase! ill be sure to warm people as i see it.
