### ISSUE TITLE
exptrain - casting spells because combat is seen

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#127]
Gurks swings his weapons in lethal arcs, dousing the area with Seipora Rein's blood.
Seipora Rein is weakened!

< 549h/549H 121v/139V P: std > 

Seipora Rein dodges Gurks's attack.
Gurks barely wounds Seipora Rein with his massive flame-enshrouded slash.
Gurks barely wounds Seipora Rein with his massive flame-enshrouded bludgeon.
Seipora Rein misses Samem with her hit.
Samem barely wounds Seipora Rein with his massive bludgeon. (x3)

< 549h/549H 122v/139V P: std > 

[No longer moving. Spellcasting has resumed]

this prompts my chanter to blur my tank and get left, you're not checking to see if the combat is the group.

might just be an issue with your dev..

**Comment by zenevan** [comment]
The House of the Harp
   The House of the Harp has long been a fixture in Silverymoon,
recently reopened after a period of disuse.  A college for bards it is
often the scene of revels.  All forms of entertainers are welcome to
mingle here and demonstrate their craft.  When not engaged in revelry
master bard Forell Luckaun can be found here teaching younger bards
his craft.
Room size: Large (L:30 ft  W:30 ft  H:50 ft)
Exits: - West          [48850] 
Corpse of Forell Luckaun is lying here.
A broken lyre stands here.
Kamac  (Shield Dwarf) stands here.
Jeszad  (Drow Elf) stands here, fighting Forell Luckaun.(Red Aura)
Gurks  (Half-Orc) stands here, fighting Forell Luckaun.
Samem  (Half-Orc) stands here, fighting Forell Luckaun.
Forell Luckaun sits here, fighting Samem.
Jeszad starts casting an offensive spell called 'Bigbys Clenched Fist'

< 549h/549H 133v/139V P: std > 

Kamac group-says '[Moving to: Seipora Rein (48721)  <.w2s16w2neu>]'
[Spellqueue cleared.]

< 549h/549H 133v/139V P: std >

You are already standing.

< 549h/549H 133v/139V P: std > 
Samem barely wounds Forell Luckaun with his massive bludgeon.

< 549h/549H 133v/139V P: std > 

[No longer moving. Spellcasting has resumed]

Gurks barely wounds Forell Luckaun with his massive bludgeon.

**Comment by Nyyrazzilyss** [comment]
It should only trigger if the combat is a group member, will take a look since obviously it isn't.

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
