### ISSUE TITLE
Keeps trying to rest/pray when already praying when someone else prays....

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#128]
Vomicopol clambers to his feet.
Vomicopol, looking very frustrated, packs up his holy symbol.

< 360h/762H 111v/137V P: sit > 

Vomicopol takes out his holy symbol and begins praying intently.

[No longer moving. Spellcasting has resumed]

< 361h/762H 112v/137V P: sit > 
[Spellqueue cleared.]
You are already resting.

< 362h/762H 112v/137V P: sit >

You have memorized the following spells:

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
