### ISSUE TITLE
Missing rooms - The Necormancer's Laboratory

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#13]
Missing 8 rooms on one floor, both east and west off the following room #'s:

#88015
#88016
#88017
#88018

Missing 12 more rooms on the floor below, north and west off the following room #'s:

#88021
#88022
#88023
#88024
#88025
#88026

Suspect the remainder of the zone after #88031 is unmapped as I couldn't get a sync after that.

**Comment by Nyyrazzilyss** [comment]
added 7/23 dev
