### ISSUE TITLE
Ranger - Dual wielding, then bow, then dual wielding doesn't correctly utilize melee powers

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#130]
Steps:
1. Dual wield
2. Enter combat
3. Switch to bow
4. Use bow skills (maybe not necessary)
5. Switch to dual wield

Expected Result:
Script converts back to melee powers

Actual Result:
1. "Knockdown shot" button doesn't convert back to Sweeping Strike
2. Script attempts to use archery powers instead of melee (fires triple shot instead of twin strike)
3. "On" status of powers doesn't seem to be respected.  I have to toggle off and on the button for the script to use triple shot (instead of twin strike like it should)

Doesn't help Recovery:
1. I haven't been able to recovery by switching weapons sets
2. "equip" doesn't recover

Does Recover:
1. restarting mudlet
2. renting / logging back in

**Comment by Nyyrazzilyss** [comment]
Did a quick test on latest dev, couldn't duplicate. I wouldn't surprise me if there's problems with weapon switching, however, can you post a log with current dev?

**Comment by zenevan** [comment]
You removed dev?

**Comment by Gyrx** [comment]
Unable to repro on 2/3 dev.  Closing as 1/20 had the issue.
