### ISSUE TITLE
Map Error - Embay (Airy)

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#132]
Exits: -N -S [Error: mud 'A Narrow Tunnel Through the Rock' doesn't match mapper 'A Narrow Tunnel
 Through the Rock (Airy)' at '75163']            [75163] 

< 553h/551H 108v/109V |ss +|ap +|ev +|ts +|bs +| |3|3|3|3|2| P: std >

A Sleeping Area Deep Within the Shrine (Airy)
Exits: -N -S -U [Error: mud 'A Sleeping Area Deep Within the Shrine' doesn't match mapper 'A
 Sleeping Area Deep Within the Shrine (Airy)' at '75162']         [75162] 
A rough looking sea elf traveler relaxes here.
A sea elf researcher is sitting in deep contemplation over a book here.

< 553h/551H 107v/109V |ss +|ap +|ev +|ts +|bs +| |3|3|3|3|2| P: std > 
s
A Narrow Tunnel Through the Rock (Airy)
Exits: -N -S [Error: mud 'A Narrow Tunnel Through the Rock' doesn't match mapper 'A Narrow Tunnel
 Through the Rock (Airy)' at '75161']            [75161] 

< 553h/551H 106v/109V |ss +|ap +|ev +|ts +|bs +| |3|3|3|3|2| P: std > 
s
An Undersea Shrine Penetrated by Coral (Airy)
Exits: -N -D [Error: mud 'An Undersea Shrine Penetrated by Coral' doesn't match mapper 'An Undersea
 Shrine Penetrated by Coral (Airy)' at '75160']            [75160] 
A water elemental is here, flowing like a living current.

**Comment by Nyyrazzilyss** [comment]
should be fixed 1/31 dev
