### ISSUE TITLE
prompt not capturing anything when there are special characters in the enemy name

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#134]
< (?:(\d+)h)?\/?(?:(\d+)H)? ?(?:(\d+)p)?\/?(?:(\d+)P)? ?(?:(\d+)v)?\/?(?:(\d+)V)? ?[\|]?((?:[a-z]+ [0-9+]+\|)+)? ?[\|]?((?:[0-9 ]\|)+)? ?(?:T: ([A-Za-z ]+))? ?(?:TC: ([A-Za-z ]+))? ?(?:E: ([A-Za-z ]+))? ?(?:EC: ([A-Za-z ]+))? ?(?:EP: ([A-Za-z ]+))? (?:P: (.*)) >

inCombat does not fire on this when the prompt looks like this:
< 393h/501H 120v/120V |3|2|3|1| T: Dumisa TC: small wounds E: war-leader EC: pretty hurt EP: std P: std >

**Comment by zenevan** [comment]
had to hack it to:
< (?:(\d+)h)?\/?(?:(\d+)H)? ?(?:(\d+)p)?\/?(?:(\d+)P)? ?(?:(\d+)v)?\/?(?:(\d+)V)? ?[\|]?((?:[a-z]+ [0-9+]+\|)+)? ?[\|]?((?:[0-9 ]\|)+)? ?(?:T: ([A-Za-z ]+))? ?(?:TC: ([A-Za-z ]+))? ?(?:E: (.+))? ?(?:EC: ([A-Za-z ]+))? ?(?:EP: ([A-Za-z ]+))? (?:P: (.*)) >

**Comment by zenevan** [comment]
this of course breaks bash

**Comment by Nyyrazzilyss** [comment]
(?:E: ([A-Za-z '-]+)) is the capture to add a hyphen alone. Added an apostrophe also, not sure if there's anything else

**Comment by zenevan** [comment]
me either, i got it working by making a 2nd prompt capture that catches it for now, was freakin out lol :P

**Comment by Nyyrazzilyss** [comment]
should be fixed
