### ISSUE TITLE
Doesn't match mapper - Basin Wastes

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#136]
On the top grid of manscorps (mapper has it listed as The Basin Wastes) I encounter the following issue:

< 591h/591H 108v/225V |3|2|3|3|2| P: std > 
s
An Eroded Sandstone Ridge
   A heavily eroded sandstone ridge gently rises above the desert sands here.
The barren surface of the ridge is broken only by the cracks and holes which
decorate it.  The holes range in size from bare dimples to those that you could
drop a halfling down and never see him again.  The wind whipping over the ridge
keeps it largely clear of sand although some still accumulates in some of the
deeper holes.  The sandstone is of a dull red-brown color caused by years of
exposure to bleaching sun and rain.
Exits: - North - East  - South - West                  [72513] 

e
< 591h/591H 108v/225V |3|2|3|3|2| P: std >

A Sandstone Ridge Surrounded by Dunes
e
   A sandstone ridge rises up from the small rocky dunes of this region.  The
ridge only overtops the surrounding dunes by fifteen to twenty feet.  The
hillock amounts to barely more than a barren bleached red-brown mound.  No
vegetation grows there and the wind whistling over its surface keeps it mostly
free of sand.  Wind, water and sun have taken their toll on the surface of the
ridge with large cracks and holes making the surface of trecherous.
Exits: - North - East  - South - West                  [72526] 

< 591h/591H 107v/225V |3|2|3|3|2| P: std >

A Rocky Ridge in the Desert
e
   A ridge of granite runs north to south in the rocky region of the desert
which surrounds this area.  The hard granite surface of the ridge is lined with
quite a lot of cracks and jagged outcrops where pieces have broken away.  The
hardy desert grasses have seized the protection offered by the cracks and
outcrops and grow abundantly here in comparison with elsewhere in the deset.
The swirling, desert winds blow here with greater velocity than on the desert
floor but do not contain as much loose sand.
Exits: - North - East  - South - West                  [72529] 
A sand snake slithers around the rocky desert.

< 591h/591H 106v/225V |3|2|3|3|2| P: std >

The Rocky Desert
   Wind whips up sand as it swirls through the rocks of this barren area of the
desert.  The wind quickly covers any tracks that may have been made through
here.  There are several holes in the sand which indicate that there is animal
life of some description here, perhaps snakes, scorpions or some such creature.
There is no evidence of vegetation growing here apart from some dead grass.
Exits: - North - East  - South - West  [Error: mud 'The Rocky Desert' doesn't match mapper 'A Rocky
 Ridge in the Desert' at '72529']                  [72529] 
A jarbo hops around the desert on the hunt for scraps.

--------

**Comment by Nyyrazzilyss** [comment]
This should have been fixed a month or two ago - When's the last time you updated your mapfile?

type: @map update

**Comment by Nyyrazzilyss** [comment]
Guessing this was previously corrected - closing
