### ISSUE TITLE
Speed up XP train when soloing...

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#138]
I added this to the 'is dead' trigger that calls nexttrainstop...

if callNextTrain == nil then
			callNextTrain=true
			look:send()
			cecho("<red>\n\n[Calling function: NextTrainStop()]\n")
			if groupList:size() > 1 then
			   tempTimer(6, [[NextTrainStop()]])
			 else
			   tempTimer(3, [[NextTrainStop()]])
			 end	 
		end

**Comment by Nyyrazzilyss** [comment]
sounds reasonable

**Comment by Nyyrazzilyss** [comment]
02/11c dev
