### ISSUE TITLE
Added missing noble to Ashstone XP train

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#14]
{87257, "Ashstone noble"},
{87258, "Ashstone noble"},
{87253, "Ashstone noble"},
--{87314, "kindly priest"},
{87254, "Ashstone noble"},
{87251, "Ashstone noble"},
{87255, "Ashstone noble"},
{87249, "Ashstone noble"}

**Comment by Nyyrazzilyss** [comment]
added 7/23 dev
