### ISSUE TITLE
an astral-forged force whip - Causes powers info vit and other strangness to show when using EQ command

### ISSUE THREAD

**Issue by Fisig** [Nyyrazzilyss/NyyLIB#141]
< 715h/715H 123v/123V P: std > 
l

[ Que: L ][ Send: L ] L
An Elegant Home
Room size: Large (L:30 ft  W:30 ft  H:50 ft)
Exits: -S              [48605] 
Corpse of a graceful commoner is lying here.
Corpse of a lithe commoner is lying here.
[2] Corpse of a graceful commoner is lying here.

< 715h/715H 123v/123V P: std > 
eq

[ Que: EQ ][ Send: EQ ] EQ
You are using:
<worn as a badge>    a tattoo of three bolts of lightning over a cutlass (glowing)
<worn on head>       the mystical circlet of the facile chimera
<worn on eyes>       an eyepatch with the symbol of Ashstone
<worn in ear>        a gem studded earring of Bahamut
<worn in ear>        a ruby teardrop earring
<worn on face>       a magically wispy dwarven beard (glowing)
<worn around neck>   the starlight amulet of the moon guardian
<worn around neck>   the butterfly amulet of the faerie guardian
<worn on body>       a suit of spiked pure crystal armor
<worn about body>    a heavy cloak of dragonskin
<component bag>      a pouch with the symbol of Ashstone
<worn about waist>   a golden chain of wide links with a mother-of-pearl clasp
<worn on arms>       some mithril sleeves of Moradin
<held as shield>     a shield of otherplanar metal etched with swirling runes
<worn around wrist>  an unfettered manacle of thickly woven metallic mesh
<worn around wrist>  a writhing bracelet of eldritch flames
<worn on hands>      some gloves of flayed planetar hide
<worn on finger>     a ring of the hearth
<worn on finger>     a ring of the hearth
<primary weapon>     an astral-forged force whip

[ Que: powers info vit ][ Send: powers info vit ] 
powers info vit

[ Que: POWERS info vit ][ Send: POWERS info vit ] 
POWERS info vit
<worn on legs>       some leggings of chakra's power
<worn on feet>       a pair of cockatrice hide boots

< 715h/715H 123v/123V P: std >

< 715h/715H 123v/123V P: std > 

Name             : Vitality                 
Alias            : vt                       
Type             : Spell                    
Source           : Divine                   
Prepare          : Study                    
Target           : Character in room
Activation Time  : 6 seconds 
Related Skill    : spellcast healing
Restrictions     : Autofire, Garrote, Standing, Can Speak
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Target Effect    : Modify hitpoints by 202 for 6 minutes 3 seconds 2 pulses  
Target Effect    : Heal for 202 hit points                            

< 715h/715H 123v/123V P: std > 
rem whip
You stop using an astral-forged force whip.

< 715h/690H 123v/123V P: std > 
eq

[ Que: EQ ][ Send: EQ ] EQ
You are using:
<worn as a badge>    a tattoo of three bolts of lightning over a cutlass (glowing)
<worn on head>       the mystical circlet of the facile chimera
<worn on eyes>       an eyepatch with the symbol of Ashstone
<worn in ear>        a gem studded earring of Bahamut
<worn in ear>        a ruby teardrop earring
<worn on face>       a magically wispy dwarven beard (glowing)
<worn around neck>   the starlight amulet of the moon guardian
<worn around neck>   the butterfly amulet of the faerie guardian
<worn on body>       a suit of spiked pure crystal armor
<worn about body>    a heavy cloak of dragonskin
<component bag>      a pouch with the symbol of Ashstone
<worn about waist>   a golden chain of wide links with a mother-of-pearl clasp
<worn on arms>       some mithril sleeves of Moradin
<held as shield>     a shield of otherplanar metal etched with swirling runes
<worn around wrist>  an unfettered manacle of thickly woven metallic mesh
<worn around wrist>  a writhing bracelet of eldritch flames
<worn on hands>      some gloves of flayed planetar hide
<worn on finger>     a ring of the hearth
<worn on finger>     a ring of the hearth
<worn on legs>       some leggings of chakra's power
<worn on feet>       a pair of cockatrice hide boots

< 715h/690H 123v/123V P: std >

**Comment by Nyyrazzilyss** [comment]
This isn't specific to the force whip, it's because the powers info command gets sent for specific spells to confirm duration of them based on your +sf. Whenever 'equip' is typed. It should be gagged.

**Comment by Nyyrazzilyss** [comment]
The powers info command being sent was removed for now as at dev 3/23
