### ISSUE TITLE
Spell slots aren't reset when changing characters

### ISSUE THREAD

**Issue by karbas** [Nyyrazzilyss/NyyLIB#142]
Playing a level 50 paladin my spell slots are correctly: 3, 3, 3, 3, 2.
Switch to a level 30 ranger, spell slots from prompt are: 3, 3, 3, 1, 2.

When changing characters, the underlying data structure holding spell slots is not reset resulting in the lower level character attempting to cast spells they do not have access to. In the example above, the ranger's 5th level spells are set to 2 from the previous character's prompt, autoheal is on, when the character hits < 50% cloak of life is attempted to be cast every prompt.

**Comment by Nyyrazzilyss** [comment]
This was fixed in dev.

Add the following to early in the prompt trigger 'Capture Prompt'
spell:resetSlot()

If it doesn't exist, in the 'SpellSlots' script add

function spell:resetSlot()
	self.slots = {}
end
