### ISSUE TITLE
ice weird breaks warriors in ice plane

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#143]
weird utters the words, 'iuophwabraz'.
had to tick this

-- should be cleric only
--spell:setNext("sp weird")

locks up warriors

**Comment by Nyyrazzilyss** [comment]
Not sure why I never fixed that, and instead left a comment saying it needs to be fixed/ what the solution is

**Comment by Nyyrazzilyss** [comment]
fixed 2/27 dev
