### ISSUE TITLE
TiaOcular-on.png not found

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#147]
I logged into my battlechanter, and after switching back on multiple other characters I frequently see the following error printed to my screen:

[Error: file C:/Users/Classic Man/.config/mudlet/profiles/Toril/NyyLIB011dev/buttons/TiaOcular-on.
png not found]

Script version: 2/28/2018 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

**Comment by Nyyrazzilyss** [comment]
fixed 3/7 dev
