### ISSUE TITLE
Train stalls

### ISSUE THREAD

**Issue by Fisig** [Nyyrazzilyss/NyyLIB#148]
< 832h/832H 105v/105V |3|3|3|3|2| T: Ezred TC: excellent E: prostitute EC: awful EP: rcl P: std > 
[ Rescue: Ezred ]

An aging prostitute misses Ezred with her hit.
An aging prostitute misses Ezred with her hit.
Ezred brutally wounds an aging prostitute with his massive slash.
Ezred wounds an aging prostitute harshly with his massive slash.
An aging prostitute staggers from Ezred's massive slash!
An aging prostitute staggers from your massive slash!
An aging prostitute staggers from your massive slash!
You critically wound an aging prostitute with a massive slash!

< 832h/832H 105v/105V |3|3|3|3|2| T: Ezred TC: excellent E: prostitute EC: awful EP: rcl P: std >

The House of Pleasure

[MELEE: Terrifying Smite] TRS
< 832h/832H 105v/105V |3|3|3|3|2| P: std >

But nobody is fighting him?

< 832h/832H 105v/105V |3|3|3|3|2| P: std >

No target for your power could be found!

< 832h/832H 105v/105V |3|3|3|3|2| P: std >

You get a small pile of coins from corpse of an aging prostitute.
There were: 14 platinum coins, 18 gold coins, 4 silver coins, 1 copper coin.

< 832h/832H 105v/105V |3|3|3|3|2| P: std > 

Corpse of an aging prostitute melts into the ground, leaving no trace of its passing.

< 832h/832H 105v/105V |3|3|3|3|2| P: std > 

Autosaving...

< 832h/832H 105v/105V |3|3|3|3|2| P: std >

******************
Gag'd look firing right at the kill.
At this point the train stalls, simply hitting look and it resumes.

**Comment by Nyyrazzilyss** [comment]
Hopefully fixed 3/7 dev
