### ISSUE TITLE
map issue in UM2

### ISSUE THREAD

**Issue by ebouchard88** [Nyyrazzilyss/NyyLIB#149]
2 rooms not shown in my version of the map at least (might be on latest version though) but still.. here they are:

From 10000000000 up from SP. e, s. You are in a N-W corner. There is a hidden room south with a bunch of wine bottle.

From the same 1000000000 up from SP: 2e, s, w. You are in a E-W room. There is a locked door south.

**Comment by Nyyrazzilyss** [comment]
I'm not sure what room '1000000000' is.

Example:

It is pitch black...

< 584h/799H 903p/913P 101v/120V P: std > 
e
[onNetworkOutput: e]
A T-intersection in the Passage
Exits: -E -S -W        [71013] 
A red silk cloak of exceptional quality lies upon the ground here. (magic)

**Comment by ebouchard88** [comment]
I was just saying from the room you go a thousand up in the pitch black :). Anyway, just got the room number it might be easie.

Room 71012 and 70903 close to entrance from SP. They both have a south secret which is not on your map

**Comment by Nyyrazzilyss** [comment]
Added, thanks
