### ISSUE TITLE
Warder cloak - timer resets to 120 seconds even if there is a timer already active

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#15]
If you try to proc warder cloak, it doesn't check to see if there is an existing timer active and resets the timer here: timer:set("TiaWarder", 2*60)

I imagine it should be similar to the assassinate timer, which shows you the time left on the already active timer if you try to use it before its recharged.

Though some people have multiple warder cloaks to proc, so not sure how that would get handled.

**Comment by Nyyrazzilyss** [comment]
fixed 7/23 dev
