### ISSUE TITLE
missing room in UM2

### ISSUE THREAD

**Issue by ebouchard88** [Nyyrazzilyss/NyyLIB#151]
room 71919. show 1 room. but it is in fact many rooms. Haven't had time to map it all as I did a mistake and lost sneak and died :) Room is unlocked with a key coming from wandering hidden thieves

**Comment by Nyyrazzilyss** [comment]
A mapfile including this can be found at https://github.com/Nyyrazzilyss/NyyLIB/blob/master/NyyLIB011dev/toril.map
