### ISSUE TITLE
Ranger - Twin Strike killing bow doesn't trigger NyyLib button cooldown

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#155]
Steps:
Land twin strike as killing blow

Expected Result:
Twin Strike button engages cooldown

Actual Result:
NyyLib tries to use twin strike as a skill on next fight because it's not tracking cooldown

Sample Text
You strike a vulture down with a barrage of blows from both weapons.

**Comment by Nyyrazzilyss** [comment]
Twin Strike missing the following trigger pattern:

^(?:< .* > )?You strike .* down with a barrage of blows from both weapons.

**Comment by Nyyrazzilyss** [comment]
rc2 updated 4/15
