### ISSUE TITLE
Gag does not gag chat window as well

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#156]
I gag Moving to:
and
Attacking:

the text is gagged in the main mud window, but it still shows up in the captured text, which is why i gagged it in the first place, ill fix it myself, just a heads up.

**Comment by zenevan** [comment]
I changed this block in "code" under demonic:

	-- check if broken packet/line on same line as prompt

	local roomline = getLines(getLineCount(), getLineCount()-1)[1]
  
	-- don't echo gagged text

	if isGagged(captureWho) or isGagged(captureBody) or isGagged(roomline) then
		return
	end
	
	if roomline == nil then
		echo("[ERROR: nil roomline]\n")
	end

	local linecheck = string.find(roomline, "^< .* > ")

	if linecheck ~= nil then
		linecheck = string.find(roomline, "> ")
	end

	if linecheck ~= nil then
		-- include part line without prompt
		selectSection(linecheck+1, string.len(roomline)-linecheck-1)
	else
	-- include full line in capture window
		selectCurrentLine()
	end

  copy()

	



	-- don't echo empty lines

**Comment by Nyyrazzilyss** [comment]
12/22/18 dev
