### ISSUE TITLE
Blackguard - spam's Dominating Smite when "They are too large for you to do that!"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#159]
< 734h/599H 120v/120V |ps 1|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|1| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
Slair OOC: 'no license, 1 and done'
They are too large for you to do that!

< 734h/599H 120v/120V |ps 1|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|1| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 
[SPELL: Aura of Death] AD
You start chanting... [Casting: AD (Aura of Death)]

< 733h/599H 120v/120V |ps 1|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|1| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 

[MELEE: Dominating Smite] DS

You complete your spell... [ AD (Aura of Death) ]
A dark mist surrounds you, wrapping you in the chill embrace of death.

< 733h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your awesome slash barely wounds a baby stone-eater.
A baby stone-eater dodges your futile attack.
A baby stone-eater misses you with its smash. (x3)
They are too large for you to do that!

< 742h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std >

< 742h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 741h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: small wounds EP: std P: std > 

A baby stone-eater dodges your futile attack.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash barely wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x3)

< 749h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 749h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x3)

< 761h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 760h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your powerful slash barely wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x2)

< 772h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 772h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash badly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x3)

< 784h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

[MELEE: Dominating Smite] DS

[Elemental Ward has expired on Ezred.]
They are too large for you to do that!

< 783h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

Slair OOC: 'if your child should die tragicly, your line has ended, sorry, we don't need you'

< 782h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 781h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: few wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash slightly wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x3)

< 795h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 794h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

A baby stone-eater dodges your futile attack.
The dark mists surge as life force is siphoned into you.
Your massive slash badly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash badly wounds a baby stone-eater.
A baby stone-eater misses you with its smash. (x3)

< 796h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 795h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your massive slash badly wounds a baby stone-eater. (x3)
A baby stone-eater misses you with its smash. (x3)

< 796h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 796h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

[MELEE: Dark Majesty] DM
Dark tendrils crawl forth from your shield and wrap around you as you strike out at a baby stone
-eater.

< 795h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 3|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: nasty wounds EP: std P: std > 

The dark mists surge as life force is siphoned into you.
Your mighty slash slightly wounds a baby stone-eater.
Your massive slash badly wounds a baby stone-eater.
A baby stone-eater dodges your futile attack.
A baby stone-eater misses you with its smash. (x2)

< 796h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 3|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

Obanax OOC: 'lol@we dont need you'

< 795h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 2|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 794h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 2|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 
Halmetalok OOC: 'I say license regarding, meet the requirements and you get a license for a kid, and
yea one and done'

< 794h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 2|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 793h/599H 120v/120V |ps +|sot +|bc +|drs +|ds +|dm 2|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

[MELEE: Plundering Smite] PS
The dark mists surge as life force is siphoned into you.
Your massive slash badly wounds a baby stone-eater.
A baby stone-eater dodges your futile attack.
Your massive slash badly wounds a baby stone-eater.
A baby stone-eater misses you with its smash.
A baby stone-eater's attack only grazes you as you dodge aside!
A baby stone-eater barely wounds you with its average smash.
A baby stone-eater misses you with its smash.
Your strike leaves a vile blight on a baby stone-eater, and some of its life flows into you.

< 779h/599H 120v/120V |ps 3|sot +|bc +|drs +|ds +|dm 1|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

A baby stone-eater's attack only grazes you as you dodge aside!
A baby stone-eater barely wounds you with its average smash.

< 761h/599H 120v/120V |ps 3|sot +|bc +|drs +|ds +|dm 1|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: pretty hurt EP: std P: std > 

A baby stone-eater misses you with its smash. (x3)
The dark mists surge as life force is siphoned into you.
Your mighty slash badly wounds a baby stone-eater.
The dark mists surge as life force is siphoned into you.
Your massive slash wounds a baby stone-eater harshly.
The dark mists surge as life force is siphoned into you.
Your massive slash wounds a baby stone-eater harshly.
A baby stone-eater misses you with its smash. (x2)
You dodge a baby stone-eater's vicious attack.

< 776h/599H 120v/120V |ps 3|sot +|bc +|drs +|ds +|dm 1|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: awful EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

< 775h/599H 120v/120V |ps 2|sot +|bc +|drs +|ds +|dm 1|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: awful EP: std P: std > 

The shadowy tendrils around you slowly unfurl and fade away.

< 774h/599H 120v/120V |ps 1|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|1|0|0| T: Ezred TC:
excellent E: stone-eater EC: awful EP: std P: std > 

[MELEE: Dominating Smite] DS
They are too large for you to do that!

**Comment by CountVooku** [comment]
Could you add a disable trigger on the message until you see a "RIP" and then have it reenable?
