### ISSUE TITLE
Warrior - Skullcrusher doesn't always trigger button cooldown, which falsely implies the skill is ready to use

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#160]
I noticed regularly yesterday during gith that using skullcrusher skill manually would not trigger the button cooldown.  I knew the skill wasn't ready because I just used it, but it made it difficult to track exactly when the skill was ready again :)

Sample log:
You raise your weapon high and bring it crashing down on a spectral hound's head with a sickening 
crack.

**Comment by Nyyrazzilyss** [comment]
This is likely fixed on 4/15, and gone through all the melee powered to make sure it had all (hit/miss/glance/kill) messages
