### ISSUE TITLE
"fols" command is getting swallowed, need to type "FOLS" for my paladin/ranger (non pet class bug?)

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#163]
I've noticed on both paladin and ranger that if I type the "fols" command it gets swallowed by the script.  I have to type "FOLS" to bypass.

Log:

< 1093h/1093H 227v/227V |3|3|3|3|2| P: std > 
The Standing Stone
Exits: - North - East  - South - West                  [8758] 
A massive granite block stands on the hilltop.
Munintokik  (Duergar) stands in mid-air here.

< 1093h/1093H 227v/227V |3|3|3|3|2| P: std > 
i
You are carrying:
a portable hole

< 1093h/1093H 227v/227V |3|3|3|3|2| P: std > 
fols
FOLS

Follower summary for Manorak:
Number of Followers: 1

PC:
   772/815   HP  110/110  MV      + Munintokik

< 1093h/1093H 227v/227V |3|3|3|3|2| P: std > 
gsay follow

**Comment by Nyyrazzilyss** [comment]
already fixed, last update to rc2 was 4/15
