### ISSUE TITLE
Enchanter - Script is spamming globe for a target that isn't in room

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#166]
Your skin crawls as you hear a death cry nearby!
Sullemon has died!
Sullemon group-says 'Dragonscales Out ------ Larim'
[Dragonscales has expired on Sullemon.]

< 303h/866H 101v/101V P: std > 

Mapnanemar sneaks east.

< 304h/866H 101v/101V P: std > 

Beern enters from the east.

l e
< 304h/866H 101v/101V P: std >

An Ancient Trail
Exits: - East  - West 
You see the red shape of a colossal being here.

< 305h/866H 101v/101V P: std > 

Sullemon has returned to the land of the living.

< 305h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 305h/866H 101v/101V P: std >
< 306h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 306h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 306h/866H 101v/101V P: std >
< 307h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 307h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 308h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
Beern leaves east.

< 308h/866H 101v/101V P: std >

You don't see them here!

< 308h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 309h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 309h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 310h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 311h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 311h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 311h/866H 101v/101V P: std >
< 312h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 312h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 312h/866H 101v/101V P: std >
< 313h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 313h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
You don't see them here!

< 313h/866H 101v/101V P: std >
< 314h/866H 101v/101V P: std > 
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
l
You don't see them here!

< 314h/866H 101v/101V P: std >

< 314h/866H 101v/101V P: std >

An Ancient Trail
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon
Exits: - East  - South      [Map not in sync, type @find or scan to attempt resync] 

< 314h/866H 101v/101V P: std >

You don't see them here!
[SPELL: Globe of Invulnerability] gi Sullemon
gi Sullemon

< 315h/866H 101v/101V P: std >

You don't see them here!

< 315h/866H 101v/101V P: std >

**Comment by Nyyrazzilyss** [comment]
This was fixed sometime prior the the 4/22 update to rc2
