### ISSUE TITLE
Add toggle to remove ‘gcmd’ from gsay chat log..

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#168]
Weed out the spammy “moving to”, etc from the person running the train.

**Comment by Nyyrazzilyss** [comment]
This was indirectly dealt with when I fixed the @gag command to remove from the chat window also. However: The problem with that is it also removes from the main window.

I'll add an alias @cgag that duplicates how the @gag command works, but only removes from the chat window / not the main window.

**Comment by Nyyrazzilyss** [comment]
12/22/18 dev
