### ISSUE TITLE
Un-Hiding in zone unexpectedly

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#17]
Log:

An Ethereal Staircase
Exits: - Up    - Down   [93628] 

< 553h/500H 130v/130V P: std > 

Lilabipple group-says 'moving'

< 552h/500H 130v/130V P: std > 

Lilabipple group-says 'silence mages'

< 551h/500H 130v/130V P: std > 
gsay "An Ethereal Staircase"
You group-say '"An Ethereal Staircase"'

< 551h/500H 130v/130V P: std > 

Lilabipple flies in from below.
Rekpezul flies in from below.
Awberuy rides in on a hell hound from below.
Alane flies in from below.
Warraz flies in from below.
Lanlira flies in from below.
Dagkog flies in from below.
Isila flies in from below.
Bobidibble flies in from below.
Lifleil flies in from below.
Ataj flies in from below.
The ghost of a huge stone golem flies in from below.
Aynep flies in from below.
The ghost of a human noble flies in from below.
The spectre of a human noble flies in from below.
Ewiril flies in from below.
Esif flies in from below.

< 550h/500H 130v/130V P: std > 
Bobidibble group-says 'whomever is considered an archaic form anymore'

< 550h/500H 130v/130V P: std >

**You stop trying to hide.**

< 550h/500H 130v/130V P: std > 
l
An Ethereal Staircase
Exits: - Up    - Down   [93628] 
Esif  (Half-Orc) stands in mid-air here.
Ewiril - Librarian - The Warders (RP) (Moon Elf) stands in mid-air here.
The spectre of a human noble stands here.
The ghost of a human noble stands here.
Aynep  (Drow Elf) stands in mid-air here.
The ghost of a huge stone golem stands here.
Ataj  (Drow Elf) stands in mid-air here.
Lifleil  (Moon Elf) stands in mid-air here.
Bobidibble  (Gnome) stands in mid-air here.
Isila  (Moon Elf) stands in mid-air here.
Dagkog  (Orc) stands in mid-air here.
Lanlira  (Moon Elf) stands in mid-air here.
Warraz  (RP) (Troll) stands in mid-air here.
Alane Aeranae - The Hunter, Soldier of Fortune (Moon Elf) stands in mid-air here.
A slavering hell hound growls deep in its throat.
Awberuy  (Half-Orc) stands in mid-air here, riding a hell hound.
Rekpezul Caty Purry - Pride of the Sabertooth (Halfling) stands in mid-air here.
Lilabipple  (Gnome) stands in mid-air here.

< 550h/500H 130v/130V P: std > 

Lilabipple group-says 'perfect'

Set:

< 776h/776H 130v/130V P: std > 

set
Usage: set key value Example: set loot off - turns off autoloot
------------
       [sound] true                  off|limited|on  play sounds
         [map] on                            on|off  display map
  [roomwindow] false                     true|false  display room window
     [swedish] false                     true|false  translate acc/etc to swedish
       [style] true                      true|false  use Qt icon stylesheet
   [hideicons] false                     true|false  hide lower icon bar
   [hideequip] true                      true|false  hide left equip icon bar
      [border] default            default|file|none  
    [numcolor] orange                             *  color of numbers on buttons
    [statname] unset                              *  
    [autoopen] false                     true|false  auto-open doors
    [echodrag] false                     true|false  echo when a corpse is dragged
  [autoportal] true                      true|false  auto enter rifts/portals/etc
   [condensed]
             items      true | misc       true | combat    false | duplicate  true |
             debug     false | spells     true | arrows    false | dragon     true |
        [vnum] true                      true|false  display room vnum
[chatfontsize] auto                          auto|#  fontsize to use for the chat window
 [grpfontsize] 14                            auto|#  fontsize to use for the group window
   [reconnect] false                        false|#  auto login this char number
    [endspell] vit             vit|dsp|pwt|fly|grp|pfu|hst|dop  
        [gcmd] false                     true|false  use gcmd instead of gsay
       [group] true                      true|false  updated group display
   [assocchar] ezdad                              *  connect to association chat, storage
     [blurout] [[ BLUR OUT ]]                     *  
 [displaceout] [[ DISPLACE OUT ]]                    *  
    [globeout] [[ GLOBE OUT ]]                    *  
    [hasteout] [[ HASTE OUT ]]                    *  
    [scaleout] [[ SCALE OUT ]]                    *  
    [stoneout] [[ STONE OUT ]]                    *  
      [vitout] [[ VIT OUT ]]                      *  
     [barkout] [[ BARK OUT ]]                     *  
--------------
   [container] portable                           *  set the name of your main container
        [food]                                    *  food name to eat
     [canteen]                                    *  name of water container
    [autoloot] off                    off|coins|all  
        [flee] off               on|off|dragon|lich  
  [autoassist] true                      true|false  assist people in combat
   [petrescue] ME                       NONE|ALL|ME  
--------------
        [wuss]                                    *  always rescue and spell wuss
  [autocircle] true                      true|false  
    [autotrip] false                     true|false  
[autoassassinate] true                      true|false  
  [autopoison] false                     true|false  
   [poisonbag] hole                               *  name of container holding poisons
    [primaryp] blind                              *  poison for primary weapon
  [secondaryp] slow                               *  poison for secondary weapon

**Comment by Nyyrazzilyss** [comment]
should be fixed 011dev 7/27
