### ISSUE TITLE
Autoroller

### ISSUE THREAD

**Issue by Nyyrazzilyss** [Nyyrazzilyss/NyyLIB#170]
The mud roller was changed to show numbers.

**Comment by CountVooku** [comment]
I did the following. I'm sure there is a more simple way to do it, but this seems to work fine.

Changed trigger to:....

(Strength|Dexterity|Agility|Constitution|Power|Intelligence|Wisdom|Charisma): +(90|91|92|93|94|95|96|97|98|99|100)

And the code to....

if matches[3] == "90" then
   NyyLIB.roller = NyyLIB.roller +  1
end
if matches[6] == "90" then
   NyyLIB.roller = NyyLIB.roller +  1
end

if matches[3] == "91" then
   NyyLIB.roller = NyyLIB.roller +  1
end
if matches[6] == "91" then
   NyyLIB.roller = NyyLIB.roller +  1
end

if matches[3] == "92" then
   NyyLIB.roller = NyyLIB.roller +  1
end
if matches[6] == "92" then
   NyyLIB.roller = NyyLIB.roller +  1
end

if matches[3] == "93" then
   NyyLIB.roller = NyyLIB.roller +  1
end
if matches[6] == "93" then
   NyyLIB.roller = NyyLIB.roller +  1
end

if matches[3] == "94" then
   NyyLIB.roller = NyyLIB.roller +  1
end
if matches[6] == "94" then
   NyyLIB.roller = NyyLIB.roller +  1
end

if matches[3] == "95" then
   NyyLIB.roller = NyyLIB.roller +  2
end
if matches[6] == "95" then
   NyyLIB.roller = NyyLIB.roller +  2
end

if matches[3] == "96" then
   NyyLIB.roller = NyyLIB.roller +  2
end
if matches[6] == "96" then
NyyLIB.roller = NyyLIB.roller +  2
end

if matches[3] == "97" then
   NyyLIB.roller = NyyLIB.roller +  2
end
if matches[6] == "97" then
   NyyLIB.roller = NyyLIB.roller +  2
end

if matches[3] == "98" then
   NyyLIB.roller = NyyLIB.roller +  2
end
if matches[6] == "98" then
   NyyLIB.roller = NyyLIB.roller +  2
end

if matches[3] == "99" then
   NyyLIB.roller = NyyLIB.roller +  2
end
if matches[6] == "99" then
   NyyLIB.roller = NyyLIB.roller +  2
end

if matches[3] == "100" then
   NyyLIB.roller = NyyLIB.roller +  3
end
if matches[6] == "100" then
   NyyLIB.roller = NyyLIB.roller +  3
end

**Comment by CountVooku** [comment]
In the newer version you need to change the "RollerTrigger" to...

"You may choose to reroll your character at this time" (substring)

"^Constitution: .* Charisma: .*" doesn't seem to work

**Comment by Nyyrazzilyss** [comment]
The problem was spacing when the name was changed to numbers.

"^Constitution: .* Charisma: .*" needs to be changed to
"^Constitution: .*Charisma: .*"

**Comment by Nyyrazzilyss** [comment]
9/2 dev
