### ISSUE TITLE
train keeps breaking

### ISSUE THREAD

**Issue by settlestone** [Nyyrazzilyss/NyyLIB#171]
[Moving to: Forell Luckaun (48850)  <.n3w2ne>]
< 768h/823H 125v/125V |bds +|nop +|cs 1|cc 8|ub 5|sb 2|ut +|ds +|hd +|vip +|bs 1|dsd 62|wu +|ra
6|sod 28| P: std > 
@fwalk 48850
[Path: .n3w2ne]
n

[Currently moving. Spellcasting is temporarily paused.]

w
w
w
n
n
e

Lavarpard Street
Exits: -N -E -S -W
A human traveler tours the city.
A ruby-throated humming bird hovers here feeding.
A small falcon swoops in trying to catch smaller birds.

< 771h/823H 124v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

Lavarpard Street
Exits: -N -E -S -W

< 771h/823H 123v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

The Market
Exits: -N -E -S -W
A stone flower pot rests solidly here.
A small lizard crawls here keeping to the shadows.
A gold and black bird hops on the ground here.
A dwarf stands here looking grumpy.

< 771h/823H 122v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

The Market
Exits: -N -E -S -W
A halfling farmer has come into town to trade.
A gnome tinker journeys here.
A human boy wanders the streets.
Kemeca stands here selling potions.

< 771h/823H 121v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

The Draw
Exits: -N -E -S -W

< 771h/823H 120v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

The Draw
Exits: -N -E -S -W
A spotted housecat is here looking for mice.

< 772h/823H 120v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std >

The House of the Harp
Exits: -W
Blood splotches cover everything in the area.
A broken lyre stands here.
Ruxum  (RP) (Troll) stands here, fighting Forell Luckaun.
Forell Luckaun is lying here, fighting Ruxum.

< 772h/823H 119v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std > 
Ruxum blocks Forell Luckaun's attack with his shield!
Forell Luckaun's attack only grazes Ruxum as he dodges aside!
Forell Luckaun slightly wounds Ruxum with his powerful hit.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.

< 772h/823H 119v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std > 
Ruxum drops into a defensive posture and raises his shield as he lands a strike on Forell Luckaun.

< 772h/823H 120v/125V |bds +|nop +|cs +|cc 7|ub 4|sb 1|ut +|ds +|hd +|vip +|bs +|dsd 61|wu +|ra
5|sod 27| P: std > 
You drop your guard slightly under the fatigue of maintaining superior defenses.

< 773h/823H 120v/125V |bds +|nop +|cs +|cc 6|ub 3|sb +|ut +|ds +|hd +|vip +|bs +|dsd 60|wu +|ra
4|sod 26| P: std > 

Forell Luckaun misses Ruxum with his hit.
Ruxum parries Forell Luckaun's lunge at him.
Forell Luckaun dodges Ruxum's attack.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.
Forell Luckaun dodges Ruxum's attack.

< 776h/823H 123v/125V |bds +|nop +|cs +|cc 6|ub 3|sb +|ut +|ds +|hd +|vip +|bs +|dsd 60|wu +|ra
4|sod 26| P: std > 

[Diamond Shield Defense has expired on Ogq.]

Forell Luckaun misses Ruxum with his hit.
Ruxum parries Forell Luckaun's lunge at him.
Forell Luckaun clambers to his feet.
Forell Luckaun dodges Ruxum's attack.
Forell Luckaun dodges Ruxum's attack.
Ruxum barely wounds Forell Luckaun with his awesome bludgeon.

< 779h/823H 125v/125V |bds +|nop +|cs +|cc 5|ub 2|sb +|ut +|ds +|hd +|vip +|bs +|dsd 59|wu +|ra
3|sod 25| P: std > 
Ruxum slams his shield into Forell Luckaun with tremendous force, knocking him to the ground!

< 779h/823H 125v/125V |bds +|nop +|cs +|cc 5|ub 2|sb +|ut +|ds +|hd +|vip +|bs +|dsd 59|wu +|ra
3|sod 25| P: std > 

Forell Luckaun misses Ruxum with his hit.
Forell Luckaun misses Ruxum with his hit.
Ruxum's attack only grazes Forell Luckaun as he dodges aside!
Ruxum barely wounds Forell Luckaun with his powerful bludgeon.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.
Ruxum slightly wounds Forell Luckaun with his massive bludgeon.

< 783h/823H 125v/125V |bds +|nop +|cs +|cc 4|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 58|wu +|ra
2|sod 24| P: std > 

Ruxum hoists his weapon in the air and flashes it menacingly at Forell Luckaun.
Forell Luckaun turns his attention to Ruxum.

< 783h/823H 125v/125V |bds +|nop +|cs +|cc 4|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 58|wu +|ra
2|sod 24| P: std >

< 784h/823H 125v/125V |bds +|nop +|cs +|cc 3|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 57|wu +|ra
1|sod 23| P: std > 

Forell Luckaun misses Ruxum with his hit.
Forell Luckaun misses Ruxum with his hit.
Ruxum wounds Forell Luckaun harshly with his massive bludgeon.
Ruxum's attack only grazes Forell Luckaun as he dodges aside!
Ruxum slightly wounds Forell Luckaun with his awesome bludgeon.
Ruxum badly wounds Forell Luckaun with his massive bludgeon.

< 786h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 57|wu +|ra
1|sod 23| P: std > 

Ruxum drops into a defensive posture and raises his shield as he lands a strike on Forell Luckaun.

< 787h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 57|wu +|ra
1|sod 23| P: std > 

A momentary brilliant glow originating from Ruxum's circlet begins
a rapid change in his appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around Ruxum's arms, neck,
and torso, granting him a reptilian quickstrike ability! As his eyes gleam
a vivid yellow the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Ruxum badly wounds Forell Luckaun with his massive bludgeon.
Ruxum severely wounds Forell Luckaun with his massive bludgeon.
Forell Luckaun dodges Ruxum's attack.
Ruxum severely wounds Forell Luckaun with his massive bludgeon.
Ruxum severely wounds Forell Luckaun with his massive bludgeon.
Ruxum wounds Forell Luckaun harshly with his massive bludgeon.
Forell Luckaun dodges Ruxum's attack.

< 789h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 56|wu +|ra
+|sod 22| P: std > 

Forell Luckaun misses Ruxum with his hit.
Forell Luckaun misses Ruxum with his hit.
Ruxum severely wounds Forell Luckaun with his massive bludgeon.
Forell Luckaun dodges Ruxum's attack.
Ruxum misses Forell Luckaun with his bludgeon.

< 790h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 56|wu +|ra
+|sod 22| P: std > 

Ruxum lunges forward and cracks Forell Luckaun a brutal blow upside the head with his weapon.

< 790h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 56|wu +|ra
+|sod 22| P: std > 

Forell Luckaun misses Ruxum with his hit.
Forell Luckaun misses Ruxum with his hit.
Forell Luckaun clambers to his feet.
Ruxum brutally wounds Forell Luckaun with his massive bludgeon.
Ruxum brutally wounds Forell Luckaun with his massive bludgeon.
Forell Luckaun dodges Ruxum's attack.

< 794h/823H 125v/125V |bds +|nop +|cs +|cc 1|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 55|wu +|ra
+|sod 21| P: std > 

Ruxum slams his shield into Forell Luckaun with tremendous force, knocking him to the ground!

< 794h/823H 125v/125V |bds +|nop +|cs +|cc 1|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 55|wu +|ra
+|sod 21| P: std > 
acc you drop your guard slightly seems to break it it just broke
You ASSOC: 'you drop your guard slightly seems to break it it just broke'

< 797h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 54|wu +|ra
+|sod 20| P: std > 

Forell Luckaun misses Ruxum with his hit.
Forell Luckaun misses Ruxum with his hit.
Ruxum enshrouds Forell Luckaun in a mist of blood with his massive bludgeon!
Forell Luckaun is nearly slain by the force of Ruxum's massive bludgeon!
Ruxum crushes Forell Luckaun's skull.  Forell Luckaun instantly collapses.
Forell Luckaun is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of Forell Luckaun.

< 798h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 54|wu +|ra
+|sod 20| P: std > 
Ruxum gets a small pile of coins from corpse of Forell Luckaun.

< 798h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 54|wu +|ra
+|sod 20| P: std > 
acc how do i log it
You ASSOC: 'how do i log it'

< 801h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 53|wu +|ra
+|sod 19| P: std > 
@fwalk 48850
[Path: .n3w2ne]
n
w
w
w
n
n
e

Alas, you cannot go that way. . . .

< 802h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 52|wu +|ra
+|sod 18| P: std >

The Draw
Exits: -N -E -S -W
A spotted housecat is here looking for mice.

< 802h/823H 124v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 52|wu +|ra
+|sod 18| P: std >

Wynderfayne's Wonderful Wynds
Exits: -E
Thaddeus Wynderfayne is here minding his shop.

< 803h/823H 123v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 52|wu +|ra
+|sod 18| P: std >

Alas, you cannot go that way. . . .

< 803h/823H 123v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 52|wu +|ra
+|sod 18| P: std > 
acc now it sent me to a random room
You ASSOC: 'now it sent me to a random room'

< 812h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 50|wu +|ra
+|sod 16| P: std > 
acc map hasnt moved
You ASSOC: 'map hasnt moved'

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 44|wu +|ra
+|sod 10| P: std > 
l
Wynderfayne's Wonderful Wynds
Exits: -E
Thaddeus Wynderfayne is here minding his shop.

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 44|wu +|ra
+|sod 10| P: std > 

Nyyrazzilyss NHC: 'Easiest if you've got it in backscroll is scroll back/highlight/copy + paste'

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 40|wu +|ra
+|sod 6| P: std > 

Thaddeus paces while fiddling with the knot on his apron.

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 40|wu +|ra
+|sod 6| P: std > 

Nyyrazzilyss ASSOC:: 'Easiest if you've got it in backscroll is scroll back/highlight/copy + paste'

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 39|wu +|ra
+|sod 5| P: std > 

Thaddeus paces while fiddling with the knot on his apron.

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 37|wu +|ra
+|sod 3| P: std > 

Dubax NHC: 'you'll have to forgive some of my ignorance.  It seems to do it often, many zones, I
usually have to reconnect to get it to work, even then not always.  I don't remember how to capture 
vnum and have a slim rememberance of what it actually means. I haven't played a mud for some 15-20 
years.'

< 823h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs +|dsd 36|wu +|ra
+|sod 2| P: std > 

Thaddeus paces while fiddling with the knot on his apron.

**Comment by settlestone** [comment]
[happened again

Moving to: Lavis Ryl (48524)  <.sen>]
< 872h/823H 125v/125V |bds +|nop +|cs +|cc 2|ub +|sb 1|ut +|ds 1|hd +|vip +|bs 8|dsd 74|wu +|ra
4|sod 40| P: std > 
@fwalk 48524
[Path: .sen]
s


[Currently moving. Spellcasting is temporarily paused.]

e
n

The Market
Exits: -N -E -S -W
A stone flower pot rests solidly here.
A dwarf stands here looking grumpy.

< 871h/823H 124v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds 1|hd +|vip +|bs 8|dsd 73|wu +|ra
4|sod 39| P: std >

Lavarpard Street
Exits: -N -E -S -W

< 871h/823H 123v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds 1|hd +|vip +|bs 8|dsd 73|wu +|ra
4|sod 39| P: std >

Rhyester's Matins
Exits: -S
Lavis Ryl stands here giving a service to the Morninglord.

< 871h/823H 122v/125V |bds +|nop +|cs +|cc 2|ub +|sb +|ut +|ds 1|hd +|vip +|bs 8|dsd 73|wu +|ra
4|sod 39| P: std > 

With aching muscles, you relax your defensive posture.

< 870h/823H 123v/125V |bds +|nop +|cs +|cc 1|ub +|sb +|ut +|ds +|hd +|vip +|bs 7|dsd 72|wu +|ra
3|sod 38| P: std > 
say why?
You say 'why?'

< 868h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs 5|dsd 70|wu +|ra
1|sod 36| P: std > 
l
Rhyester's Matins
Exits: -S
Lavis Ryl stands here giving a service to the Morninglord.

< 867h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs 5|dsd 70|wu +|ra
1|sod 36| P: std > 
l
Rhyester's Matins
Exits: -S
Lavis Ryl stands here giving a service to the Morninglord.

< 867h/823H 125v/125V |bds +|nop +|cs +|cc +|ub +|sb +|ut +|ds +|hd +|vip +|bs 4|dsd 69|wu +|ra
+|sod 35| P: std > 

Your icy casi

**Comment by Nyyrazzilyss** [comment]
9/2 dev
