### ISSUE TITLE
yet another train issue 

### ISSUE THREAD

**Issue by settlestone** [Nyyrazzilyss/NyyLIB#173]
Wayward House Inn (Shadowed)
Exits: -N -U
A gaping hole in the ground leads into darkness.
A black dress has fallen here.
Someone has left behind a tidy white uniform. (illuminating)
An oak staff lies here.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A dapper noble is here socializing.
A dapper noble is here socializing.
A dapper noble is here socializing.
Babbidodle  (AFK) (Gnome) stands here.
Mugo  (Ogre) stands here.
Nyyrazzilyss  (Illithid) sits resting.
Icezzexxuy  (Illithid) sits resting.
Havorr Merendil stands behind the counter ready to serve.

< 698h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 14|sb +|ut +|ds +|hd +|vip +|bs +|dsd 44|wu +|ra
+|sod +| P: std > 
@inittrain
[Unlock path in Silverymoon]
@fwalk 48603
[Error: source room id is nil]
.neswen12e2n2sw2new2nsen2snesn3w2new2s13w3s3w5neudw2s3wnew4s9e2s2w2e5sesn5esudn11w3nud3s5e7nws
n
e
s
w
e
n
e
e
e
e
e
e
e
e
e
e
e
e
n
n
s
s
w
n
n
e
w
n
n
s
e
n
s
s
n
e
s
n
w
w
w
n
n
e
w
s
s
w
w
w
w
w
w
w
w
w
w
w
w
w
s
s
s
w
w
w
n
n
n
n
n
e
u
d
w
s
s
w
w
w
n
e
w
s
s
s
s
e
e
e
e
e
e
e
e
e
s
s
w
w
e
e
s
s
s
s
s
e
s
n
e
e
e
e
e
s
u
d
n
w
w
w
w
w
w
w
w
w
w
w
n
n
n
u
d
s
s
s
e
e
e
e
e
n
n
n
n
n
n
n
w
s
Ghostwalk
Exits: -N -E -S -W
A chipmunk scampers along the ground here.
A grey squirrel sniffs the air cautiously.
A proud commoner walks confidently here.

< 703h/823H 124v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

At Moonway and Ghostwalk
Exits: -N -E -S -W
A stone fountain bubbles here.
A human girl skips along absent mindedly.
A half-elven boy runs down the street.
Gwen Silversong stands here singing.

< 703h/823H 123v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Moonway
Exits: -N -E -S -W
A grey squirrel sniffs the air cautiously.

< 703h/823H 122v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

The Bank of Silverymoon
Exits: -E
A large wooden counter is here, with a sign posted on it.
Aureliel stands here overseeing the bank.

< 703h/823H 121v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Moonway
Exits: -N -E -S -W
A grey squirrel sniffs the air cautiously.

< 704h/823H 120v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

At Moonway and Ghostwalk
Exits: -N -E -S -W
A stone fountain bubbles here.
A human girl skips along absent mindedly.
A half-elven boy runs down the street.
Gwen Silversong stands here singing.

< 704h/823H 120v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Ghostwalk
Exits: -N -E -S -W

< 704h/823H 119v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Ghostwalk
Exits: -N -E -S -W
A barbarian shaman looks about warily.
An old man walks here with the aid of a walking stick.

< 704h/823H 118v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

At Brightbuckler Street and Ghostwalk
Exits: -N -E -S -W
A half-elven girl is here looking about.
A dark robed man wanders here.
A well dressed woman walks here.
A human boy wanders the streets.

< 705h/823H 117v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Ghostwalk
Exits: -N -E -S -W

< 705h/823H 117v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std >

Ghostwalk
Exits: -N -E -S -W
A robin searches for food here.
An elven druid roams the streets of Silverymoon.
A purple martin flies swiftly here.

< 705h/823H 116v/125V |bds +|nop +|cs +|cc +|ub 12|sb +|ut +|ds +|hd +|vip +|bs +|dsd 42|wu +|ra
+|sod +| P: std > 
say so laggy
You say 'so laggy'

< 713h/823H 124v/125V |bds +|nop +|cs +|cc +|ub 10|sb +|ut +|ds +|hd +|vip +|bs +|dsd 40|wu +|ra
+|sod +| P: std > 
l
Ghostwalk
Exits: -N -E -S -W
A robin searches for food here.
An elven druid roams the streets of Silverymoon.
A purple martin flies swiftly here.

< 714h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 9|sb +|ut +|ds +|hd +|vip +|bs +|dsd 39|wu +|ra
+|sod +| P: std > 
say and it broke
You say 'and it broke'

< 718h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 8|sb +|ut +|ds +|hd +|vip +|bs +|dsd 38|wu +|ra
+|sod +| P: std > 
w
w
say wtf is going on with mudlet
You say 'wtf is going on with mudlet'

< 727h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 6|sb +|ut +|ds +|hd +|vip +|bs +|dsd 36|wu +|ra
+|sod +| P: std > 
l
Ghostwalk
Exits: -N -E -S -W
A robin searches for food here.
An elven druid roams the streets of Silverymoon.
A purple martin flies swiftly here.

< 727h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 6|sb +|ut +|ds +|hd +|vip +|bs +|dsd 36|wu +|ra
+|sod +| P: std > 
w
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
enter hole
w
w
w
e
e
e
e
ss
You don't see them here!

ss
< 745h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 31|wu +|ra
+|sod +| P: std >

ss
< 746h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 31|wu +|ra
+|sod +| P: std >

You don't see them here!
n

< 746h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 30|wu +|ra
+|sod +| P: std >

You don't see them here!

n
< 746h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 30|wu +|ra
+|sod +| P: std >

Ghostwalk
Exits: -N -E -S -W
A robin searches for food here.
An elven druid roams the streets of Silverymoon.
A purple martin flies swiftly here.

n
< 747h/823H 125v/125V |bds +|nop +|cs +|cc +|ub 1|sb +|ut +|ds +|hd +|vip +|bs +|dsd 30|wu +|ra
+|sod +| P: std > 
@fwalk 48524
[Error: source room id is nil]
l
-------------------------------------------------------------------------------------------------------------------

to add as well the client seems very laggy.. no idea why. it's a fresh install on a fresh version of windows with literally nothing else installed on it besides mudlet.  windows 10.  as well as the laggy issues you can see it not letting me put commands in.  I can do say/gsay/acc stuff but no actual commands.. that's random.. no idea what's going on it was working fine last week.

**Comment by Nyyrazzilyss** [comment]
9/16 dev
