### ISSUE TITLE
Shaman keeps trying to cast spells in fugue

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#176]
Not sure about other casters. Keeps trying to cast gheal non stop until I disable the button. Also tries to cast stoneskin if 'self' enabled.

**Comment by Nyyrazzilyss** [comment]
The fugue trigger has a space at the end of it that was causing it not to fire. Correct spelling should be:

^Your soul is transported to The Fugue Plane as your crumbling body succumbs.*

**Comment by CountVooku** [comment]
Oh, shoulda caught that one. Thanks.

**Comment by Nyyrazzilyss** [comment]
9/2 dev
