### ISSUE TITLE
Train stopped

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#177]
Looks like while running a solo train, I entered a room where combat was already happening.  Train was about to move to the next stop, then I got aggroed by an area spell cast.  I ended up getting the killing blow, but didnt move to the next stop, even with a manual attempt by me at the end to call the nexttrainstop function.

Exits: -N -E -S -W     [48516] 
A spotted housecat is here looking for mice.
A human merchant from Waterdeep is here selling.

< 602h/867H 93v/95V |ts +|ss +|ap 2|ev +|bs 7| |1|0|1|1|0| P: std >

Temple of Silver Stars
Exits: -N              [48518] 
Blood is smeared all over the area.
Corpse of Shalyssa Lurialar is lying here.
A book rests here.
Jidas  (Shield Dwarf) stands here, fighting Shalyssa Lurialar.
Neve  (Half-Orc) stands here, fighting Shalyssa Lurialar.
Shalyssa Lurialar stands here, fighting Neve.

< 602h/867H 92v/95V |ts +|ss +|ap 2|ev +|bs 7| |1|0|1|1|0| P: std > 

[Reached train station: (48518) Shalyssa Lurialar]

[Players in room - Moving to next station]

[Moving to: Forell Luckaun (48850)  <.n3w2ne>]
< 603h/867H 92v/95V |ts +|ss +|ap 2|ev +|bs 7| |1|0|1|1|0| P: std > 

Jidas barely wounds Shalyssa Lurialar with his mighty bludgeon.
Neve misses Shalyssa Lurialar with her bludgeon.
Neve's a sharpened rapier studded with rubies explodes in a burst of searing flames!
Neve severely wounds Shalyssa Lurialar with her massive flaming pierce.
Neve badly wounds Shalyssa Lurialar with her massive bludgeon.
Neve badly wounds Shalyssa Lurialar with her massive flaming pierce.
Neve misses Shalyssa Lurialar with her bludgeon.
Shalyssa Lurialar badly wounds Neve with her powerful hit.
Shalyssa Lurialar starts casting an offensive spell.
Your massive bludgeon slightly wounds Shalyssa Lurialar.

< 603h/867H 93v/95V |ts +|ss +|ap 2|ev +|bs 7| |1|0|1|1|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: std P: std > 

[No longer moving. Spellcasting has resumed]

[MELEE: Sweeping Strike] SS
< 604h/867H 93v/95V |ts +|ss +|ap 2|ev +|bs 7| |1|0|1|1|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: std P: std >

You sweep attack Shalyssa Lurialar with a fury of blows, but she retains her balance.
[SPELL: Cloak of Resilience] CLR

< 604h/867H 93v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|1|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: std P: std >

You start chanting... [Casting: CLR (Cloak of Resilience)]

< 604h/867H 93v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|1|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: std P: std > 
Neve sweep attacks Shalyssa Lurialar with unbound fury, knocking her off balance!
Shalyssa Lurialar crashes to the ground!

< 604h/867H 94v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|1|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std > 

You complete your spell... [ CLR (Cloak of Resilience) ]
Wispy bands of shadow clasp about you in a cloak of resilience.

< 604h/867H 94v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std > 

[MELEE: Eviscerate] EV
@fwalk 48850
[Can't fwalk while in combat]

Shalyssa Lurialar stops chanting abruptly!

< 604h/867H 94v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std > 
< 604h/867H 95v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std >

You're not ready to perform another action!
[SPELL: Hunters Mark] HM

< 604h/867H 95v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std >

Your massive bludgeon wounds Shalyssa Lurialar harshly.
Your mighty pierce badly wounds Shalyssa Lurialar.
Your massive bludgeon severely wounds Shalyssa Lurialar.
Your massive pierce wounds Shalyssa Lurialar harshly.
Jidas severely wounds Shalyssa Lurialar with his mighty bludgeon.
Shalyssa Lurialar dodges Neve's attack.
Neve brutally wounds Shalyssa Lurialar with her massive flaming pierce.
Shalyssa Lurialar staggers from Neve's massive bludgeon!
Shalyssa Lurialar staggers from Neve's massive flaming pierce!
Shalyssa Lurialar misses Neve with her hit.
You start chanting... [Casting: HM (Hunters Mark)]

< 628h/867H 95v/95V |ts +|ss 3|ap 1|ev +|bs 6| |1|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std > 
You complete your spell... [ HM (Hunters Mark) ]
Shalyssa Lurialar is marked with a faint blue glow.
Neve strikes the weak spots in Shalyssa Lurialar's armor, leaving her vulnerable.
Shalyssa Lurialar trembles and appears vulnerable!

< 628h/867H 95v/95V |ts +|ss 3|ap 1|ev +|bs 6| |0|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std >

Temple of Silver Stars
[MELEE: Eviscerate] EV
< 628h/867H 95v/95V |ts +|ss 2|ap +|ev +|bs 5| |0|0|1|0|0| T: Neve TC: excellent E: shalyssa EC:
awful EP: rcl P: std >

You swing your weapons in a killing arc, eviscerating Shalyssa Lurialar in a spray of gore.
Shalyssa Lurialar is dead! R.I.P.
You receive 296,764 XP (0.79%) experience.
Your blood freezes as you hear the rattling death cry of Shalyssa Lurialar.

< 628h/867H 95v/95V |ts +|ss 1|ap +|ev 9|bs 4| |0|0|1|0|0| P: std >

You get a few coins from corpse of Shalyssa Lurialar.
There were: 6 platinum coins, 16 gold coins, 5 silver coins, 1 copper coin.
pac
put all.coin portable

< 628h/867H 95v/95V |ts +|ss 1|ap +|ev 8|bs 4| |0|0|1|0|0| P: std >

< 628h/867H 95v/95V |ts +|ss 1|ap +|ev 8|bs 4| |0|0|1|0|0| P: std >

Ok.
You put some coins into a portable hole.

< 628h/867H 95v/95V |ts +|ss 1|ap +|ev 8|bs 4| |0|0|1|0|0| P: std > 
Neve leaves north.
Jidas leaves north.

< 631h/867H 95v/95V |ts +|ss +|ap +|ev 6|bs 2| |0|0|1|0|0| P: std > 

Your radiant cloak of life fades away.

< 660h/617H 95v/95V |ts +|ss +|ap +|ev +|bs +| |0|1|1|0|0| P: std > 
Your shadowy cloak of resilience dissolves.

< 660h/617H 95v/95V |ts +|ss +|ap +|ev +|bs +| |0|1|1|0|0| P: std > 
l
Temple of Silver Stars
Exits: -N              [48518] 
Blood is smeared all over the area.
[2] Corpse of Shalyssa Lurialar is lying here.
A book rests here.

< 658h/617H 95v/95V |ts +|ss +|ap +|ev +|bs +| |1|1|1|0|0| P: std > 

lua NextTrainStop()

[Moving to: Seipora Rein (48721)  <.n19w2neu>]
< 655h/617H 95v/95V |ts +|ss +|ap +|ev +|bs +| |1|1|1|0|0| P: std > 
st
You are already standing.

**Comment by Nyyrazzilyss** [comment]
That's very much an edge case. Don't know when i'll look into it.

**Comment by Nyyrazzilyss** [comment]
Won't break if it happens (it'll still kill the mob)

9/16 dev
