### ISSUE TITLE
Omeder

### ISSUE THREAD

**Issue by Omeder** [Nyyrazzilyss/NyyLIB#178]
[MELEE: Dominating Smite] DS STOUT
You advance upon a stout commoner with a series of devastating blows that send her crashing to the
ground.

< 770h/770H 109v/110V |fa +|ps +|sot +|bc +|drs +|ds 3|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: excellent E: stout EC: few scratches EP: rcl P: std > 
< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds 3|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: excellent E: stout EC: few scratches EP: rcl P: std > 

Your mighty flaming slash barely wounds a stout commoner.
Your a burning star-metal falchion explodes in a burst of searing flames!
You score a CRITICAL HIT!
Your massive flaming slash badly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner misses you with her hit.

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds 3|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: excellent E: stout EC: small wounds EP: rcl P: std > 

Your mighty flaming slash slightly wounds a stout commoner.
Your mighty flaming slash slightly wounds a stout commoner.
You partially deflect a stout commoner's lunge at you.
A stout commoner barely wounds you with her average hit.

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds 2|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: rcl P: std > 

A stout commoner dodges your futile attack.
Your mighty flaming slash slightly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner misses you with her hit.

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds 1|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: rcl P: std > 

Nyyrazzilyss group-projects 'Right - It would be prior to then'

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds 1|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: rcl P: std > 

Your massive flaming slash badly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner clambers to her feet.

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: std P: std > 

Your attack only grazes a stout commoner as she dodges aside!
Your average flaming slash barely wounds a stout commoner.
Your powerful flaming slash slightly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner misses you with her hit.

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: std P: std > 
gsay I don't know what you mean
You group-say 'I don't know what you mean'

< 752h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: std P: std > 

Your awesome flaming slash slightly wounds a stout commoner.
Your mighty flaming slash slightly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner misses you with her hit.
A stout commoner, in a show of awesome skill, manages to trip up herself!

< 753h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: rcl P: std > 

A stout commoner dodges your futile attack.
Your mighty flaming slash slightly wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner misses you with her hit.

< 753h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: few wounds EP: rcl P: std > 

Your massive flaming slash badly wounds a stout commoner.
Your a burning star-metal falchion explodes in a burst of searing flames!
You score a CRITICAL HIT!
Your massive flaming slash brutally wounds a stout commoner.
A stout commoner misses you with her hit.
A stout commoner clambers to her feet.

< 753h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 

You miss a stout commoner with your flaming slash.
You parry a stout commoner's lunge at you.
A stout commoner misses you with her hit.

< 753h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 

Your powerful flaming slash badly wounds a stout commoner.
Your awesome flaming slash severely wounds a stout commoner.
You parry a stout commoner's lunge at you.
You parry a stout commoner's lunge at you.

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 
gsay I just typed ds commoner, it bashed the commoner, not sending any other skills at all.
You group-say 'I just typed ds commoner, it bashed the commoner, not sending any other skills at all
.'

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 

Your powerful flaming slash severely wounds a stout commoner.
Your powerful flaming slash severely wounds a stout commoner.
A stout commoner misses you with her hit.
You block a stout commoner's attack with your shield!

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 

Nyyrazzilyss group-projects 'The problem isn't that it's not working. I need to know the last powers
command sent PRIOR to that'

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| T: Omeder
TC: few scratches E: stout EC: pretty hurt EP: std P: std > 

Your powerful flaming slash severely wounds a stout commoner.
Your a burning star-metal falchion explodes in a burst of searing flames!
You score a CRITICAL HIT!
A stout commoner slumps to the ground.
Your final slash sends a stout commoner's head bouncing along the ground.
a stout commoner is dead! R.I.P.
A stout commoner slumps to the ground.
You receive 15,710 XP (0.04%) experience.
Your blood freezes as you hear the rattling death cry of a stout commoner.

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std >

You get a small pile of coins from corpse of a stout commoner.
There were: 3 platinum coins, 12 gold coins, 38 silver coins, 3 copper coins.

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std >

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay they are all turned on
You group-say 'they are all turned on'

< 754h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 

Nyyrazzilyss group-projects 'So the command to engage the mob isn't kill, it's ds?'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay I used ds this time
You group-say 'I used ds this time'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay kill last time
You group-say 'kill last time'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay when I used kill it sent no commands at all
You group-say 'when I used kill it sent no commands at all'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay accept kill of course
You group-say 'accept kill of course'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay when I typed ds, it did that, then nothing after
You group-say 'when I typed ds, it did that, then nothing after'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 

Nyyrazzilyss group-projects 'Right, but regardless at some point a command worked'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay once
You group-say 'once'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay your talking to a code idiot so I don't mean to frustrate you
You group-say 'your talking to a code idiot so I don't mean to frustrate you'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 

Nyyrazzilyss group-projects 'Right, and I need to see a log of the last command that worked'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 

Autosaving...

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 
gsay I don't really know how to do that.  copy and past it to a word file or soemthing?  I'm a 
nurse man, I just play the games :)
You group-say 'I don't really know how to do that.  copy and past it to a word file or soemthing? 
I'm a nurse man, I just play the games :)'

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std > 

Nyyrazzilyss group-projects 'copy/paste it to notepad/wordpad, then post it here 'https://github
.com/Nyyrazzilyss/NyyLIB/issues''

< 770h/770H 110v/110V |fa +|ps +|sot +|bc +|drs +|ds +|dm +|rs +|fr +|fs +| |3|3|3|3|2| P: std >

**Comment by Nyyrazzilyss** [comment]
Problem was from end user code changes
