### ISSUE TITLE
Improvement Bard

### ISSUE THREAD

**Issue by laiyna** [Nyyrazzilyss/NyyLIB#179]
Bard now auto sing, and when they out of power they stop. If you start to sing renewel to get psp back, when you full it auto starts to sing healing.

What MUCH better would be:
Tog a song, when you run out of psp, you start to sing renewel, and when full auto sing the last song you where singing. This way you have an endless loop.

Also a @set for bards, auto song yes/no
If its yes, it loops between your chosen song and renewel, if no, it stops after each song (so no default healing song)

**Comment by laiyna** [comment]
when I am full mana, and singing, it auto switches to healing song. when I switch back to haste (I regen mana when playing haste), it auto switches again back to healing when full mana.
This makes it at times impossible to sing something else then healing. Big issue if I try to solo..

**Comment by Nyyrazzilyss** [comment]
I'm having difficulties duplicating this


You finish a verse of the song of renewal.
You feel your energy renewing!
< 802h/733H 391p/392P 135v/135V P: std > 

Autosaving...
< 799h/733H 392p/392P 135v/135V P: std > 
[Max mana : switching songs]
With no one to accompany you, your song ends!
You stop your song.
< 798h/733H 392p/392P 135v/135V P: std >

You are not using it.
< 798h/733H 392p/392P 135v/135V P: std >

You don't have the piccolo.
< 798h/733H 392p/392P 135v/135V P: std >

You get a small oaken drum wrapped with dragonhide from a merchant's bag.
< 798h/733H 392p/392P 135v/135V P: std >

You hold a small oaken drum wrapped with dragonhide.
< 798h/733H 392p/392P 135v/135V P: std >

You are not composed enough to sing.
< 798h/768H 392p/392P 135v/135V P: std > 

A wagon rumbles along nearby, wooden wheels clattering on the stones.
< 797h/768H 392p/392P 135v/135V P: std > 
You are not composed enough to sing.
< 797h/768H 392p/392P 135v/135V P: std > 
You are not composed enough to sing.
< 797h/768H 392p/392P 135v/135V P: std > 
You begin singing.
< 796h/768H 392p/392P 135v/135V P: std > 

Your quickening chant fills your cohort with awesome determination.
Your song dramatically increases the movements of your companions!

**Comment by laiyna** [comment]
tried to duplicate it also, no avail, will make log next time

**Comment by Nyyrazzilyss** [comment]
If problem is still occuring, please repost with log
