### ISSUE TITLE
Rogue:  Auto-Circle issue when mob is wraithform

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#18]
Summary:
Auto circle seems to spam constantly if the mob is a wraith, possible solutions to temporarily disable autocircle when the mob is wraithform until mob death or You switch opponents!

Log:
< 705h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: few wounds EP: std P: std > 

[Ezdad : the mystical circlet of the coiled serpent]
The shadow of Alane deflects your blow, and strikes back at YOU!
The shadow of Alane misses you with her slash.
Your powerful pierce barely wounds the shadow of Alane. (x2)
The shadow of Alane parries your futile lunge at her.
Ewiril completes his spell...
A ball of swirling electricity rises from Ewiril's hands, hovering momentarily
above his head before releasing a torrent of electricity in every direction.
The shadow of Ezdad slumps to the ground.
Ewiril's lightning blast knocks the shadow of Ezdad to the ground, dead!
the shadow of Ezdad is dead! R.I.P.
The shadow of Ezdad slumps to the ground.
You receive 1 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of the shadow of Ezdad.
The shadow of Ezdad dissolves into nothingness.

< 705h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]
The ghost of a human noble completes its spell...
The ghost of a human noble utters the words, 'orabz ay uizjrizfaburuhl'.
The ghost of a human noble begins to shimmer.
You would pass right through them!

< 705h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

Aynep completes his spell...
A horde of maggots bursts from the ground!
< 705h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]

You feel your blood boil in your veins!
The shadow of Alane dodges your futile attack.
Your mighty pierce barely wounds the shadow of Alane. (x3)
The shadow of Alane misses Lanlira with her slash. (x2)
The ghost of a huge stone golem misses the shadow of Alane with its drain.
The shadow of Alane deflects the ghost of a huge stone golem's blow, and strikes back at the ghost
of a huge stone golem!
The shadow of Alane misses the ghost of a huge stone golem with her slash.
The ghost of a huge stone golem starts casting an offensive spell.
Bobidibble misses the shadow of Alane with his flaming bludgeon.
Esif starts casting an offensive spell called 'Creeping Doom'

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

You would pass right through them!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]
Rekpezul assists you heroically.
Rekpezul barely wounds the shadow of Alane with his average pierce.

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

You would pass right through them!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

The ghost of a human noble starts casting an offensive spell.
Ataj completes his spell...
The shadow of Alane suffers in great pain as Ataj's lich touch connects.
< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]
Esif stops chanting abruptly!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

You would pass right through them!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

Lifleil completes his spell...
A ball of swirling electricity rises from Lifleil's hands, hovering momentarily
above his head before releasing a torrent of electricity in every direction.
< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]
Ewiril starts casting an offensive spell called 'Ball Lightning'

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

You would pass right through them!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]

Esif starts casting an offensive spell called 'Hailstorm'
Bobidibble starts casting an offensive spell called 'Inferno'

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

You would pass right through them!

< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std >

Warraz assists Lanlira heroically.
The shadow of Alane parries Warraz's lunge at her.
< 686h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: nasty wounds EP: std P: std > 

[Attacking with circle]
You feel your blood boil in your veins!
Warraz barely wounds the shadow of Alane with her strong slash.
The shadow of Alane partially deflects Warraz's lunge at her.
Warraz barely wounds the shadow of Alane with her average slash.
Warraz barely wounds the shadow of Alane with her strong slash.
The shadow of Alane partially deflects Rekpezul's lunge at her.
Rekpezul barely wounds the shadow of Alane with his weak pierce.
The shadow of Alane blocks Rekpezul's attack with her shield!
Rekpezul barely wounds the shadow of Alane with his average pierce.
The shadow of Alane deflects Dagkog's blow, and strikes back at Dagkog!
The shadow of Alane misses Dagkog with her slash.
Lanlira misses the shadow of Alane with her slash.
Lanlira barely wounds the shadow of Alane with her average slash.
The shadow of Alane partially deflects your lunge at her.
Your average pierce barely wounds the shadow of Alane.
Your powerful pierce barely wounds the shadow of Alane. (x2)
You miss the shadow of Alane with your pierce.
Your powerful pierce barely wounds the shadow of Alane. (x2)
The shadow of Alane misses Lanlira with her slash. (x2)
Ataj misses the shadow of Alane with his hit.
Lifleil barely wounds the shadow of Alane with his weak bludgeon.

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std >

You would pass right through them!

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std > 

[Attacking with circle]

Lilabipple flies down.

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std >

You would pass right through them!
Awberuy maneuvers his wolf to outflank the shadow of Alane!
The shadow of Alane dodges Awberuy's attack.

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std > 

[Attacking with circle]
The ghost of a huge stone golem completes its spell...
The ghost of a huge stone golem utters the words, 'braqtwaihrz'.
You would pass right through them!

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std > 

[Attacking with circle]

Ataj starts casting an offensive spell called 'Lich Touch'

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std >

You would pass right through them!

< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std >

Esif completes his spell...
Esif summons an arctic hailstorm!
< 667h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std > 

[Attacking with circle]
The spectre of a human noble misses the shadow of Alane with its drain.

[the shadow of Alane : the mystical circlet of the coiled serpent]
The shadow of Alane misses Lanlira with her slash. (x3)
You feel your blood boil in your veins!
The shadow of Alane parries the spectre of a human noble's lunge at her.
The spectre of a human noble misses the shadow of Alane with its drain. (x2)
Awberuy barely wounds the shadow of Alane with his powerful bludgeon.
The shadow of Alane parries Awberuy's lunge at her.
The shadow of Alane blocks Awberuy's attack with her shield!
The shadow of Alane dodges Awberuy's attack.
Awberuy slightly wounds the shadow of Alane with his awesome bludgeon.
Aynep misses the shadow of Alane with his hit.
The shadow of Alane partially blocks Lifleil's attack with her shield!
Lifleil barely wounds the shadow of Alane with his weak bludgeon.
Warraz barely wounds the shadow of Alane with her powerful slash.
Warraz barely wounds the shadow of Alane with her strong slash.
The shadow of Alane blocks Warraz's attack with her shield!
Rekpezul barely wounds the shadow of Alane with his average pierce.
Dagkog barely wounds the shadow of Alane with his weak sonic bludgeon.
Lanlira barely wounds the shadow of Alane with her average slash.
Lanlira misses the shadow of Alane with her slash.
Your mighty pierce slightly wounds the shadow of Alane. (x2)
Your powerful pierce barely wounds the shadow of Alane. (x2)
Your mighty pierce slightly wounds the shadow of Alane.
Your powerful pierce barely wounds the shadow of Alane.
The shadow of Alane misses Lanlira with her slash. (x2)
The ghost of a huge stone golem misses the shadow of Alane with its drain.
The ghost of a huge stone golem barely wounds the shadow of Alane with its average drain.
You would pass right through them!

< 648h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std > 

[Attacking with circle]
A harmonious combination of notes from Rekpezul soothes your wounds.
You feel better!

< 738h/776H 130v/130V T: Lanlira TC: excellent E: shadow EC: pretty hurt EP: std P: std >

**Comment by Nyyrazzilyss** [comment]
Should be fixed 7/29 dev
