### ISSUE TITLE
train attacked mob while player in the room

### ISSUE THREAD

**Issue by laiyna** [Nyyrazzilyss/NyyLIB#181]
I notice that you prefer a log (Cyre was not grouped with me):

Cyre leaves west.

< 685h/556H 120v/120V |vs +|ds 21|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std > 
@fwalk 87253
[Path: .w2ne]
w
n
n
e

Along the Dragonride
   The road is warped here, the once tightly-fit flagstones gently rippled, like
a newly-formed wave in the sea. The stones themselves are worn from use and
there is no shortage of horses, wagons, and caravans tied to hitching posts
spaced at regular intervals along the avenue. The sidewalks, built from charred
and blackened bricks salvaged from the foundations of buildings that did not
survive the explosion, are raised roughly four feet from the ground to allow
for passengers to board and deboard carriages without having to climb down.
A large airy looking building lies to the east.  The Dragonride continues
north and south.
Exits: - North - East  - South
A tall cast-iron streetlight arcs high overhead.
A thug from the Triad RedStone is here looking for trouble.(Red Aura)
A thug from the Triad RedStone is here looking for trouble.(Red Aura)
A thug from the Triad RedStone is here looking for trouble.(Red Aura)
The leader of the RedStone Triad is standing here alertly.(Red Aura)
Yolokotul enters from the east.

< 684h/556H 119v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std >

Along the Dragonride
   The road is warped here, the once tightly-fit flagstones gently rippled, like
a newly-formed wave in the sea. The stones themselves are worn from use and
there is no shortage of horses, wagons, and caravans tied to hitching posts
spaced at regular intervals along the avenue. The sidewalks, built from charred
and blackened bricks salvaged from the foundations of buildings that did not
survive the explosion, are raised roughly four feet from the ground to allow
for passengers to board and deboard carriages without having to climb down.
This section of town has a number of stately residences used by the wealthy.
The Dragonride continues north and south.
Exits: - North - East  - South - West 
A tall cast-iron streetlight arcs high overhead.
Yolokotul enters from the south.

< 684h/556H 118v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std >

Along the Dragonride
   The road is warped here, the once tightly-fit flagstones gently rippled, like
a newly-formed wave in the sea. The stones themselves are worn from use and
there is no shortage of horses, wagons, and caravans tied to hitching posts
spaced at regular intervals along the avenue. The sidewalks, built from charred
and blackened bricks salvaged from the foundations of buildings that did not
survive the explosion, are raised roughly four feet from the ground to allow 
for passengers to board and deboard carriages without having to climb down.
This part of town is home to the upper class, the buildings are designed to
impress.  The Dragonride continues north and south.
Exits: - North - East  - South - West 
A tall cast-iron streetlight arcs high overhead.
Yolokotul enters from the south.

< 683h/556H 117v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std >

A Large Mansion Embellished with Brass Filigree
   This large mansion seems to tower above you, made of stone it had a large
base and rises to narrow spires.  The ornate stonework has been decorated with
symbols of fire and flames, all covered in brass filigree.  Inside the
mansion the furniture is all brass covered with sumptuous cushions covered
in red and gold fabric.  The rooms have high ceilings held aloft
by many decorated stone columns.
Exits: - West 
[2] Corpse of an Ashstone noble is lying here.
A flat-looking longsword has been discarded here.
Cyre Tahl'Veras the Huntsman of Ashen Lorenthal (Moon Elf) stands here.
An Ashstone noble stands here in a rage.(Red Aura)
Yolokotul enters from the west.

< 683h/556H 116v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std > 

[Reached train station: (87253) Ashstone noble]

An Ashstone noble is in an excellent condition. (Medium)

< 683h/556H 116v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std > 

Cyre sweep attacks an Ashstone noble with unbound fury, knocking him off balance!
Tendrils of acidic greenfire leap from Cyre's weapon!
Tendrils of acidic greenfire leap from Cyre's weapon!
An Ashstone noble crashes to the ground!

< 682h/556H 117v/120V |vs +|ds 20|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std > 

[MELEE: Thunderous Smite] TS ASHSTONE
You group-say '[Attacking: Ashstone]'

< 681h/556H 118v/120V |vs +|ds 19|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|0| P: std >

Your weapon explodes in a peal of roaring thunder as you strike an Ashstone noble!
An Ashstone noble is thrown to the ground by the shockwave!

< 681h/556H 118v/120V |vs +|ds 19|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Cyre TC:
excellent E: noble EC: small wounds EP: rcl P: std > 

[No longer moving. Spellcasting has resumed]

You miss an Ashstone noble with your slash.
Your awesome slash barely wounds an Ashstone noble.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
An Ashstone noble dodges Cyre's attack.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
Cyre barely wounds an Ashstone noble with his massive greenfire slash.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
An Ashstone noble misses Cyre with his hit.
Cyre partially deflects an Ashstone noble's lunge at him.
An Ashstone noble barely wounds Cyre with his average hit.

< 681h/556H 118v/120V |vs +|ds 19|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Cyre TC:
excellent E: noble EC: small wounds EP: rcl P: std >

< 681h/556H 119v/120V |vs +|ds 19|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Cyre TC:
excellent E: noble EC: few wounds EP: rcl P: std > 

Your massive slash barely wounds an Ashstone noble.
Your massive slash barely wounds an Ashstone noble.
Cyre misses an Ashstone noble with his greenfire bludgeon.
Cyre barely wounds an Ashstone noble with his massive greenfire slash.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
An Ashstone noble dodges Cyre's attack.
Cyre barely wounds an Ashstone noble with his massive greenfire bludgeon.
An Ashstone noble misses Cyre with his hit.
An Ashstone noble's attack only grazes Cyre as he dodges aside!
An Ashstone noble barely wounds Cyre with his average hit.

< 678h/556H 120v/120V |vs +|ds 18|dc +|lh +|ts 2|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Cyre TC:
excellent E: noble EC: few wounds EP: rcl P: std >

**Comment by laiyna** [comment]
This would also explain why I random rescue people....

**Comment by Nyyrazzilyss** [comment]
It should never have engaged on seeing Cyre in the room. Will look

**Comment by laiyna** [comment]
And here a log, somebody tries to rescue me :)

An Airy Building of Light Stonework
   This stone mansion seems to rise up out of the earth and reach towards
the heavens.  The light stonework and elegant buttresses lend it strength
without blocking any of the light that generously flows into the interior
through its many arcade windows.  Inside columns line the walls holding up the
vaulted ceilings.  Ornate wooden furniture is generously distributed through
the rooms providing places to enjoy the sunlight.
Exits: - West 
A flat-looking longsword has been discarded here.
An unholy symbol is lying here.
An Ashstone noble stands here flitting about.(Red Aura)

< 706h/556H 117v/120V |vs +|ds 70|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|1| P: std > 

[Reached train station: (87249) Ashstone noble]


Nimornil enters from the west.
Yolokotul enters from the west.
Zolah enters from the west.

< 706h/556H 117v/120V |vs +|ds 70|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|1| P: std >

An Ashstone noble is in an excellent condition. (Medium)

< 706h/556H 117v/120V |vs +|ds 70|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|1| P: std > 

[Attacking: Ashstone]


[MELEE: Thunderous Smite] TS ASHSTONE
Your weapon explodes in a peal of roaring thunder as you strike an Ashstone noble!
An Ashstone noble is thrown to the ground by the shockwave!

< 704h/556H 119v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|1| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std > 

[No longer moving. Spellcasting has resumed]

< 703h/556H 119v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|1| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std > 
[SPELL: Aura of Life] AL
Zolah attempts to flee.
Zolah leaves west.

< 703h/556H 119v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|1| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std >

You start chanting... [Casting: AL (Aura of Life)]

< 703h/556H 120v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|1| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std > 
Nimornil fails miserably in his attempt to rescue you.

< 703h/556H 120v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|1| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std > 
You complete your spell... [ AL (Aura of Life) ]
You begin to pulsate with a soft light as you are infused with divine health.

< 806h/806H 120v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: few scratches EP:
rcl P: std > 
< 805h/806H 120v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few scratches
EP: rcl P: std > 

[MELEE: Terrifying Smite] TRS
An Ashstone noble dodges Nimornil's attack.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his awesome greenfire slash.
Nimornil misses an Ashstone noble with his greenfire pierce.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his awesome greenfire slash.
You score a CRITICAL HIT!
Your massive slash barely wounds an Ashstone noble.
Your mighty slash barely wounds an Ashstone noble.
Your awesome slash barely wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.
Radkor GCC: 'you might be able to get kokhed       it might even be fitting for some people but it aint gunna stay for long'

< 805h/806H 120v/120V |vs +|ds 69|dc +|lh +|ts 3|brs +|trs +|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: small wounds
EP: rcl P: std >

Your eyes glow with a terrifying radiance as waves of divine dread wash over your enemies.
You hound an Ashstone noble with a series of merciless attacks!
An Ashstone noble is shaken with fear!

< 805h/806H 120v/120V |vs +|ds 68|dc +|lh +|ts 1|brs +|trs 6|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: small wounds
EP: rcl P: std > 

Nimornil fails miserably in his attempt to rescue you.

< 805h/806H 120v/120V |vs +|ds 68|dc +|lh +|ts 1|brs +|trs 6|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: small wounds
EP: rcl P: std > 

Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Your awesome slash barely wounds an Ashstone noble.
Your massive slash barely wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 805h/806H 120v/120V |vs +|ds 68|dc +|lh +|ts 1|brs +|trs 6|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 

[MELEE: Valiant Strike] VS
Your weapon ignites with a blazing holy light!
Your powerful strike engulfs an Ashstone noble in searing ribbons of divine radiance.

< 805h/806H 120v/120V |vs 3|ds 67|dc +|lh +|ts 1|brs +|trs 4|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 

Nimornil starts casting a spell called 'Cloak of Resilience'

< 805h/806H 120v/120V |vs 3|ds 67|dc +|lh +|ts 1|brs +|trs 4|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 
Nimornil completes his spell...
Wispy bands of shadow clasp about Nimornil in a cloak of resilience.

< 805h/806H 120v/120V |vs 3|ds 67|dc +|lh +|ts 1|brs +|trs 4|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 

Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his awesome greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Your mighty slash barely wounds an Ashstone noble.
An Ashstone noble dodges your futile attack.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 805h/806H 120v/120V |vs 3|ds 67|dc +|lh +|ts 1|brs +|trs 4|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 

[MELEE: Brilliant Smite] BRS
Your weapon detonates in a flash of pure light as you strike an Ashstone noble!
An Ashstone noble is blinded!
Nimornil fails miserably in his attempt to rescue you.

< 805h/806H 120v/120V |vs 2|ds 66|dc +|lh +|ts +|brs 6|trs 3|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: few wounds EP:
rcl P: std > 

Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire pierce.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Nimornil barely wounds an Ashstone noble with his massive greenfire slash.
Your awesome slash barely wounds an Ashstone noble.
Your massive slash barely wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.
An Ashstone noble clambers to his feet.

[MELEE: Thunderous Smite] TS

< 805h/806H 120v/120V |vs 2|ds 66|dc +|lh +|ts +|brs 6|trs 3|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: nasty wounds
EP: std P: std >

Your weapon explodes in a peal of roaring thunder as you strike an Ashstone noble!
[Ashstone Noble has nasty wounds!]
An Ashstone noble is thrown to the ground by the shockwave!

< 805h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: nasty wounds
EP: rcl P: std >

< 805h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: nasty wounds 
EP: rcl P: std > 

Nimornil spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Nimornil rains a series of deadly blows on an Ashstone noble!
Tendrils of acidic greenfire leap from Nimornil's weapon!
Tendrils of acidic greenfire leap from Nimornil's weapon!

< 805h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: nasty wounds
EP: rcl P: std > 
Nimornil fails miserably in his attempt to rescue you.

< 805h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: few scratches E: noble EC: nasty wounds
EP: rcl P: std > 
gcc all names I would find acceptable, the last one I played with for 1 week
You GCC: 'all names I would find acceptable, the last one I played with for 1 week'

< 806h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: nasty wounds EP:
rcl P: std > 
Nimornil barely wounds an Ashstone noble with his massive slash.
Nimornil barely wounds an Ashstone noble with his massive pierce.
Nimornil barely wounds an Ashstone noble with his massive slash.
Nimornil barely wounds an Ashstone noble with his massive pierce.
Nimornil barely wounds an Ashstone noble with his awesome slash.
Nimornil slightly wounds an Ashstone noble with his massive slash.
Your awesome slash barely wounds an Ashstone noble.
You score a CRITICAL HIT!
Your massive slash badly wounds an Ashstone noble.
Your mighty slash barely wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 806h/806H 120v/120V |vs 1|ds 65|dc +|lh +|ts 3|brs 5|trs 2|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: pretty hurt EP:
rcl P: std > 

Nimornil fails miserably in his attempt to rescue you.

< 806h/806H 120v/120V |vs +|ds 64|dc +|lh +|ts 1|brs 4|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: pretty hurt EP:
rcl P: std > 
Zolah enters from the west.

< 806h/806H 120v/120V |vs +|ds 64|dc +|lh +|ts 1|brs 4|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: pretty hurt EP:
rcl P: std > 

Nimornil slightly wounds an Ashstone noble with his massive slash.
Nimornil slightly wounds an Ashstone noble with his massive pierce.
Nimornil badly wounds an Ashstone noble with his massive slash.
Nimornil slightly wounds an Ashstone noble with his massive pierce.
Nimornil wounds an Ashstone noble harshly with his massive slash.
Your massive slash badly wounds an Ashstone noble.
Your awesome slash slightly wounds an Ashstone noble.
Your massive slash badly wounds an Ashstone noble.
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 806h/806H 120v/120V |vs +|ds 64|dc +|lh +|ts 1|brs 4|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

[MELEE: Valiant Strike] VS
Your weapon ignites with a blazing holy light!
Your powerful strike engulfs an Ashstone noble in searing ribbons of divine radiance.

< 806h/806H 120v/120V |vs 3|ds 63|dc +|lh +|ts 1|brs 3|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

Autosaving...

< 806h/806H 120v/120V |vs 2|ds 63|dc +|lh +|ts 1|brs 2|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

Nimornil starts casting an offensive spell called 'Hunters Mark'

< 806h/806H 120v/120V |vs 2|ds 63|dc +|lh +|ts 1|brs 2|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 
Nimornil completes his spell...
an Ashstone noble is marked with a faint blue glow.

< 806h/806H 120v/120V |vs 2|ds 63|dc +|lh +|ts 1|brs 2|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

Nimornil misses an Ashstone noble with his slash.
Nimornil severely wounds an Ashstone noble with his massive pierce.
Nimornil severely wounds an Ashstone noble with his massive slash.
Nimornil's attack only grazes an Ashstone noble as he dodges aside!
Nimornil badly wounds an Ashstone noble with his powerful pierce.
Nimornil wounds an Ashstone noble harshly with his massive slash.
An arched and jagged wave of negative energy lashes out in a great
cone from your massive quadribladed axe. The space between you and
an Ashstone noble seems to spin wildly as the cone of energy begins to fully
penetrate his body. Still, he shudders pitifully, trying to cling to
consciousness as the incredible power finally begins to subside.
Your mighty slash wounds an Ashstone noble harshly.
An arched and jagged wave of negative energy lashes out in a great
cone from your massive quadribladed axe. The space between you and
an Ashstone noble seems to spin wildly as the cone of energy begins to fully
penetrate his body. Still, he shudders pitifully, trying to cling to
consciousness as the incredible power finally begins to subside.
An Ashstone noble is nearly slain by the force of your awesome slash!
An Ashstone noble misses you with his hit.
An Ashstone noble misses you with his hit.

< 806h/806H 120v/120V |vs 2|ds 63|dc +|lh +|ts 1|brs 2|trs 1|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 
Zolah assists Nimornil heroically.
Zolah misses an Ashstone noble with his hit.

< 806h/806H 120v/120V |vs 2|ds 62|dc +|lh +|ts 1|brs 2|trs +|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

Nimornil fails miserably in his attempt to rescue you.

< 806h/806H 120v/120V |vs 2|ds 62|dc +|lh +|ts +|brs 2|trs +|tn +|wws +| |3|3|1|1|0| T: Ishana TC: excellent E: noble EC: awful EP: rcl P:
std > 

[MELEE: Terrifying Smite] TRS
Your eyes glow with a terrifying radiance as waves of divine dread wash over your enemies.
With grim resolve, you strike an Ashstone noble down in a flurry of powerful blows!
an Ashstone noble is dead! R.I.P.
You receive 281,047 XP (0.94%) experience.
Your blood freezes as you hear the rattling death cry of an Ashstone noble.

[Calling function: NextTrainStop()]

< 806h/806H 120v/120V |vs 1|ds 61|dc +|lh +|ts +|brs 1|trs 6|tn +|wws +| |3|3|1|1|0| P: std >

You get a small pile of coins from corpse of an Ashstone noble.
There were: 9 platinum coins, 15 gold coins, 6 silver coins.

**Comment by Nyyrazzilyss** [comment]
9/16 dev
