### ISSUE TITLE
Starts to sing heal without activating it

### ISSUE THREAD

**Issue by laiyna** [Nyyrazzilyss/NyyLIB#183]
You assist Solah heroically.
Your strong pierce barely wounds a black dragon scout.

< 1052h/1052H 492p/537P 119v/120V T: Maltevum TC: excellent E: black EC: few scratches EP: std P: std > 
Rodhal assists Maltevum heroically.
Rodhal barely wounds a black dragon scout with his mighty bludgeon.

< 1052h/1052H 492p/537P 119v/120V T: Maltevum TC: excellent E: black EC: few scratches EP: std P: std > 

Lilabipple leaves north.

< 1052h/1052H 493p/537P 119v/120V T: Maltevum TC: excellent E: black EC: few scratches EP: std P: std > 

Solah barely wounds a black dragon scout with her massive pierce.
Misi circles around a black dragon scout stabbing at his back.

< 1052h/1052H 493p/537P 120v/120V T: Maltevum TC: excellent E: black EC: few scratches EP: std P: std > 

Lilabipple enters from the north.
Ssimik slithers in from the north.

< 1052h/1052H 493p/537P 120v/120V T: Maltevum TC: excellent E: black EC: few scratches EP: std P: std > 
Misi barely wounds a black dragon scout with her mighty pierce.
Misi barely wounds a black dragon scout with her massive pierce.
Misi barely wounds a black dragon scout with her massive pierce.
A black dragon scout dodges Misi's attack.
Rodhal's attack only grazes a black dragon scout as he dodges aside!
Rodhal barely wounds a black dragon scout with his massive slash.
Rodhal barely wounds a black dragon scout with his massive slash.
Rodhal's attack only grazes a black dragon scout as he dodges aside!
Rodhal barely wounds a black dragon scout with his mighty bludgeon.
Your attack is partially absorbed by a black dragon scout's scales!
Your average pierce barely wounds a black dragon scout.
Your strong pierce barely wounds a black dragon scout.
The runes on Mobod's dwarven waraxe begin to glow even brighter as he
raises his weapon high above his head.  With a scream of rage he brings
it crashing down with thunderous force, obliterating the magical defenses of
a black dragon scout
A swirl of energy travels from Mobod's finger tips, wrapping itself around a black dragon scout...
A black dragon scout glows momentarily!
A black dragon scout dodges Mobod's attack.
Mobod's attack only grazes a black dragon scout as he dodges aside!
Mobod barely wounds a black dragon scout with his awesome slash.
Jooku misses a black dragon scout with his slash.
Jooku barely wounds a black dragon scout with his powerful slash.
Jooku slashes a bloodstone studded shortsword towards a black dragon scout,
and he flinches back reflexively.  Paired sets of runes along Jooku's blades
flicker as he spins about agilely, driving a powerful slash into a black dragon scout's
body with a bloodstone studded longsword.  As the blade is wrenched clear of
the wound, a black dragon scout's movements falter and slow.
Jooku barely wounds a black dragon scout with his massive slash.
A black dragon scout dodges Edog's attack.
Edog misses a black dragon scout with his bludgeon.
A black dragon scout misses Maltevum with his claw.
A black dragon scout's attack only grazes Maltevum as he dodges aside!
A black dragon scout slightly wounds Maltevum with his powerful claw.
A black dragon scout misses Maltevum with his claw.
A black dragon scout lashes out with  mighty tail in a broad arc!
Ssimik staggers in pain as the massive tail smashes into him!
Lilabipple staggers in pain as the massive tail smashes into her!
Azora staggers in pain as the massive tail smashes into her!
Jooku staggers in pain as the massive tail smashes into him!
Zurek staggers in pain as the massive tail smashes into him!
Syrac staggers in pain as the massive tail smashes into him!
Jina staggers in pain as the massive tail smashes into her!
Rodhal staggers in pain as the massive tail smashes into him!
Lynio staggers in pain as the massive tail smashes into him!
Rolgim staggers in pain as the massive tail smashes into him!
Rolgim is knocked down on his knees!
Misi staggers in pain as the massive tail smashes into her!
Satac staggers in pain as the massive tail smashes into him!
Relith staggers in pain as the massive tail smashes into him!
You reel backwards in pain as the massive tail smashes into you!
OUCH!  That really did HURT!
Edog staggers in pain as the massive tail smashes into him!
Mugo staggers in pain as the massive tail smashes into her!
Mobod staggers in pain as the massive tail smashes into him!
Maltevum staggers in pain as the massive tail smashes into him!
Taskan staggers in pain as the massive tail smashes into him!
Theshial staggers in pain as the massive tail smashes into him!
Nilan staggers in pain as the massive tail smashes into him!
Nilan is knocked down on the ground!
Xyrik staggers in pain as the massive tail smashes into him!
Cyre staggers in pain as the massive tail smashes into him!
Solah staggers in pain as the massive tail smashes into her!
Maltevum barely wounds a black dragon scout with his massive slash.
Maltevum barely wounds a black dragon scout with his massive slash.
Maltevum barely wounds a black dragon scout with his massive slash.
Physical power emanating from the tip of Solah's an enchanted khanjari dagger
races towards its wielder within a narrow strip of bright white light. A significant sounding
BOOM reverberates between your ears as the light settles into Solah's skin.
A black dragon scout gasps in agony as Solah strikes at his side, sending blood flying everywhere!
Solah barely wounds a black dragon scout with her massive pierce.
Solah barely wounds a black dragon scout with her massive pierce.
Solah barely wounds a black dragon scout with her massive pierce.
Solah barely wounds a black dragon scout with her massive pierce.

< 869h/1052H 493p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: small wounds EP: std P: std > 
Jooku sweep attacks a black dragon scout with unbound fury, knocking him off balance!
Theshial spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Theshial rains a series of deadly blows on a black dragon scout!
You are already standing.

< 869h/1052H 493p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Cyre sweep attacks a black dragon scout with unbound fury, knocking him off balance!
Satac spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Satac rains a series of deadly blows on a black dragon scout!
Rodhal sweep attacks a black dragon scout with unbound fury, knocking him off balance!
You are not using it.

< 869h/1052H 493p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Cyre starts casting a spell called 'Cloak of Resilience'
Maltevum starts casting a spell called 'Aura of Life'
Theshial starts casting a spell called 'Cloak of Resilience'
With no one to accompany you, your song ends!
You stop your song.
Xyrik sweep attacks a black dragon scout with unbound fury, knocking him off balance!

< 869h/1052H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Jooku starts casting a spell called 'Cloak of Resilience'
You stop using a small oaken drum wrapped with dragonhide.

< 869h/1017H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Cyre completes his spell...
Wispy bands of shadow clasp about Cyre in a cloak of resilience.
Maltevum completes his spell...
Maltevum begins to pulsate with a soft light.
Theshial completes his spell...
Wispy bands of shadow clasp about Theshial in a cloak of resilience.
Satac starts casting an offensive spell called 'Hunters Mark'
Sorry, you aren't allowed to do that in combat.
Xyrik starts casting a spell called 'Cloak of Resilience'

< 869h/1017H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Jooku completes his spell...
Wispy bands of shadow clasp about Jooku in a cloak of resilience.
Rodhal starts casting an offensive spell called 'Hunters Mark'
Mobod drops into a defensive posture and raises his shield as he lands a strike on a black dragon scout.
You get the Ancient Lyre of Amberyl from a pouch of astral dust.

< 869h/1017H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

A momentary brilliant glow originating from Zurek's circlet begins
a rapid change in his appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around Zurek's arms, neck,
and torso, granting him a reptilian quickstrike ability! As his eyes gleam
a vivid yellow the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Zurek's attack only grazes a black dragon scout as he dodges aside!
Zurek barely wounds a black dragon scout with his powerful pierce.
Zurek barely wounds a black dragon scout with his massive pierce.
A black dragon scout dodges Zurek's attack.
Zurek barely wounds a black dragon scout with his powerful pierce.
Satac completes his spell...
a black dragon scout is marked with a faint blue glow.
Xyrik completes his spell...
Wispy bands of shadow clasp about Xyrik in a cloak of resilience.
You hold the Ancient Lyre of Amberyl.

< 869h/1017H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std >

Rodhal completes his spell...
You are not composed enough to sing.

< 869h/1032H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std > 
A momentary brilliant glow originating from Azora's circlet begins
a rapid change in her appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around Azora's arms, neck,
and torso, granting her a reptilian quickstrike ability! As her eyes gleam
a vivid yellow the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Azora barely wounds a black dragon scout with her powerful bludgeon.
Azora barely wounds a black dragon scout with her massive bludgeon.
Azora barely wounds a black dragon scout with her powerful bludgeon.
Azora barely wounds a black dragon scout with her massive bludgeon.

< 869h/1032H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std > 

Mugo weaves through her foes, her weapon flashing as she strikes through their ranks.
Mugo confronts a black dragon scout and delivers a ferocious blow before sidestepping away.
Lilabipple group-says 'thanks solah'

< 869h/1032H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: few wounds EP: std P: std > 

A momentary brilliant glow originating from Jooku's circlet begins
a rapid change in his appearance. Countless serpents begin to uncoil,
slithering and sliding their way down and around Jooku's arms, neck,
and torso, granting him a reptilian quickstrike ability! As his eyes gleam
a vivid yellow the brief enchantment begins to fade. Quickly as
they descended, the serpents twist and twine their way back to the magic
within their circlet.
Jooku barely wounds a black dragon scout with his mighty slash.
Jooku barely wounds a black dragon scout with his massive slash.
Jooku darts to the one side, weapons flashing as they cut in
at a black dragon scout.
Jooku barely wounds a black dragon scout with his powerful slash.
Jooku barely wounds a black dragon scout with his mighty slash.
Jooku stops his rush suddenly, pivoting around on the ball
of his foot to reverse his angle of attack.
Jooku barely wounds a black dragon scout with his powerful slash.
Jooku barely wounds a black dragon scout with his massive slash.
With a sudden feint, Jooku darts forward and finishes his
attack routine with a dizzying flourish.
Jooku barely wounds a black dragon scout with his massive slash.
Jooku barely wounds a black dragon scout with his mighty slash.
Cyre barely wounds a black dragon scout with his massive icy slash.
Cyre barely wounds a black dragon scout with his mighty icy slash.
Cyre's attack only grazes a black dragon scout as he dodges aside!
Cyre barely wounds a black dragon scout with his mighty icy slash.
A black dragon scout dodges Xyrik's attack.
A black dragon scout dodges Xyrik's attack.
A black dragon scout dodges Xyrik's attack.
Xyrik barely wounds a black dragon scout with his massive slash.
Xyrik barely wounds a black dragon scout with his massive slash.
A black dragon scout gasps in agony as Nilan strikes at his side, sending blood flying everywhere!
Nilan barely wounds a black dragon scout with his massive pierce.
Nilan barely wounds a black dragon scout with his powerful pierce.
Nilan barely wounds a black dragon scout with his massive pierce.
Nilan barely wounds a black dragon scout with his massive pierce.
Nilan's glittering dagger glows brightly, and then he simply disapears. A
moment later he reappears, grinning as he places his dagger perfectly into
a black dragon scout's back. A screaming can be heard for miles as his very lifeforceis drained.
A black dragon scout dodges Nilan's attack.
Theshial barely wounds a black dragon scout with his massive bludgeon.
Theshial barely wounds a black dragon scout with his massive slash.
Theshial misses a black dragon scout with his bludgeon.
Theshial's attack only grazes a black dragon scout as he dodges aside!
Theshial barely wounds a black dragon scout with his strong bludgeon.
Taskan misses a black dragon scout with his bludgeon.
A black dragon scout dodges Mugo's attack.
Mugo barely wounds a black dragon scout with her massive bludgeon.
Mugo barely wounds a black dragon scout with her massive bludgeon.
Relith barely wounds a black dragon scout with his massive icy slash.
Relith barely wounds a black dragon scout with his massive icy slash.
Relith barely wounds a black dragon scout with his massive icy slash.
Satac barely wounds a black dragon scout with his massive bludgeon.
Satac barely wounds a black dragon scout with his massive slash.
Satac misses a black dragon scout with his bludgeon.
Satac barely wounds a black dragon scout with his massive bludgeon.
Rolgim barely wounds a black dragon scout with his strong sonic bludgeon.
Lynio barely wounds a black dragon scout with his massive slash.
Lynio barely wounds a black dragon scout with his massive bludgeon.
Lynio barely wounds a black dragon scout with his massive slash.
Lynio barely wounds a black dragon scout with his awesome bludgeon.
Jina misses a black dragon scout with her bludgeon.
Zurek slightly wounds a black dragon scout with his massive pierce.
Zurek barely wounds a black dragon scout with his massive pierce.
Zurek barely wounds a black dragon scout with his mighty pierce.
Zurek barely wounds a black dragon scout with his massive pierce.
Zurek's glittering dagger glows brightly, and then he simply disapears. A
moment later he reappears, grinning as he places his dagger perfectly into
a black dragon scout's back. A screaming can be heard for miles as his very lifeforceis drained.
Azora barely wounds a black dragon scout with her massive bludgeon.
Azora slightly wounds a black dragon scout with her massive pierce.
Azora barely wounds a black dragon scout with her massive bludgeon.
Azora slightly wounds a black dragon scout with her massive pierce.
Lilabipple misses a black dragon scout with her bludgeon.
Ssimik misses a black dragon scout with his bludgeon.
Misi barely wounds a black dragon scout with her awesome pierce.
Misi barely wounds a black dragon scout with her awesome pierce.
Rodhal slightly wounds a black dragon scout with his massive bludgeon.
Rodhal holds a shimmering blade of light  before him, as a yellow beam of 
light streaks towards a black dragon scout.
Rodhal slightly wounds a black dragon scout with his massive bludgeon.
Rodhal slightly wounds a black dragon scout with his massive slash.
Your strong pierce barely wounds a black dragon scout.
Your strong pierce barely wounds a black dragon scout.
Mobod barely wounds a black dragon scout with his strong slash.
Mobod barely wounds a black dragon scout with his mighty slash.
Jooku slightly wounds a black dragon scout with his massive slash.
Jooku barely wounds a black dragon scout with his mighty slash.
Jooku slightly wounds a black dragon scout with his massive slash.
A black dragon scout misses Maltevum with his claw.
Relith shrieks in pain as a black dragon scout plunges a razor-sharp wing talon into his flesh!
Maltevum barely wounds a black dragon scout with his massive slash.
A black dragon scout dodges Maltevum's attack.
A black dragon scout gasps in agony as Solah strikes at his side, sending blood flying everywhere!
Solah severely wounds a black dragon scout with her massive pierce.
Solah slightly wounds a black dragon scout with her massive pierce.
Solah badly wounds a black dragon scout with her massive pierce.
Solah slightly wounds a black dragon scout with her massive pierce.
Solah badly wounds a black dragon scout with her massive pierce.
Cyre spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Cyre rains a series of deadly blows on a black dragon scout!

< 869h/1032H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: awful EP: std P: std > 
Satac sweep attacks a black dragon scout with unbound fury, knocking him off balance!
Nilan clambers to his feet.
Jooku spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Jooku rains a series of deadly blows on a black dragon scout!

< 869h/1032H 494p/537P 120v/120V T: Maltevum TC: small wounds E: black EC: awful EP: std P: std > 
Cyre starts casting a spell called 'Cloak of Protection'
Maltevum starts casting a spell called 'Shield of Warding'
Rolgim rises to his feet.
Theshial strikes the weak spots in a black dragon scout's armor, leaving him vulnerable.
A black dragon scout trembles and appears vulnerable!
Xyrik spins and leaps through the fray, unleashing a torrent of steel on his enemies!
Xyrik rains a series of deadly blows on a black dragon scout!
A black dragon scout is torn to pieces under Xyrik's overwhelming onslaught!
a black dragon scout is dead! R.I.P.
You receive 12,464 XP (0.03%) experience.
Your blood freezes as you hear the rattling death cry of a black dragon scout.

< 869h/1032H 494p/537P 120v/120V P: std > 
Edog gets a small pile of coins from corpse of a black dragon scout.

< 869h/1032H 494p/537P 120v/120V P: std >

Cyre completes his spell...
Softly glowing mists wrap around Cyre in an cloak of protection.
Maltevum completes his spell...
An opaque globe of light blossoms around Maltevum.
The corpse of a black dragon scout does not contain the coins.

< 869h/1032H 495p/537P 120v/120V P: std >

< 869h/1032H 495p/537P 120v/120V P: std >

You are not composed enough to sing.

< 869h/1032H 495p/537P 120v/120V P: std > 

Lilabipple group-says 'mem'

< 869h/1032H 495p/537P 120v/120V P: std >

**Comment by Nyyrazzilyss** [comment]
This is by design. A bard attacked by a dragon will always switch to heal
