### ISSUE TITLE
Rooms missing on map in UM

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#184]
Hidden rooms east of the room with the rancid ghast. I didn't write down that rooms vnum.

**Comment by Gyrx** [comment]
From Acheron portal in UM down from Yawning Portal Inn in WD, the .es after the search east below are the rooms that are missing from the map.  The room .es is used to drop paladin heart to pop ethereal shield, which is used in disruption burst.  Please color on the map accordingly (purple?).

2w4s3w3sesd(search east)es

**Comment by Nyyrazzilyss** [comment]
A mapfile including this can be found at https://github.com/Nyyrazzilyss/NyyLIB/blob/master/NyyLIB011dev/toril.map
