### ISSUE TITLE
Uncaught casting exception to lock spell queue

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#185]
When trying to dispel invis on an item, there is the "them" keyword as opposed to he/she.

                 
< 206h/206H 100v/102V P: std > 
disi robe
**You don't see them here!**

< 206h/206H 100v/102V P: std >

< 206h/206H 101v/102V P: std >

A grey squirrel scampers down a tree, runs across the ground and up another tree.

i
< 206h/206H 101v/102V P: std > 
You are carrying:
a golden spellbook etched with platinum

< 206h/206H 101v/102V P: std > 
di self
DI self
You start chanting... [Casting: DI SELF (Detect Invisibility)]

< 206h/206H 102v/102V P: std > 

Casting: Detect Invisibility **

< 206h/206H 102v/102V P: std > 

Casting: Detect Invisibility *

< 206h/206H 102v/102V P: std > 

You complete your spell... [ DI SELF (Detect Invisibility) ]
Your eyes tingle.

**Comment by Nyyrazzilyss** [comment]
I -think- I might have fixed (not posted though) this previously, but i'll doublecheck with the last posted version also. With mine:

< 487h/198H 188p/188P 141v/141V P: std > 
disi robe
[onNetworkOutput: disi robe]
You don't see them here!
[onNetworkOutput: LOOK]

< 477h/198H 188p/188P 141v/141V P: std > 
i
[onNetworkOutput: i]
You are carrying:
a midnight-blue book marked with stars
a small barrel

< 473h/198H 188p/188P 141v/141V P: std > 
di self

[SPELL: Detect Invisibility] DI self[onNetworkOutput: DI self]
You start chanting... [Casting: DI SELF (Detect Invisibility)]

< 461h/198H 188p/188P 141v/141V P: std > 

Casting: Detect Invisibility *

< 458h/198H 188p/188P 141v/141V P: std > 

You complete your spell... [ DI SELF (Detect Invisibility) ]
[onNetworkOutput: LOOK]
Your eyes tingle.

**Comment by Nyyrazzilyss** [comment]
9/2 dev
