### ISSUE TITLE
Ghore - Missing room for Gaptooth quest mob

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#186]
"The Underground Market of Ghore" is missing in map lib.                                                  

< 619h/606H 121v/126V |vs +|sot +|bc +|drs +|ss +|md +|sph +|fr +|uf +| |3|3|3|3|2| P: std > 
A Room Full of Rubble (Shadowed)
   This room is almost filled with rubble and debris of various types. Huge
chunks of rock and stone are piled making it impossible to proceed very far 
into the room. The northern wall has a large section out of it in the upper
right hand section. The east and west walls are intact and appear sturdy.
  Rats scurry in and out of the piles and bones can be seen amounst the debris.
Pieces of broken armor and weapons are scattered about, none of it looks very
usefull. The room smells of death and decay. The only exit is south to the 
street.
Exits: - South - Down   [12059] 
A gaping hole in the ground leads into darkness.

< 619h/606H 113v/126V |vs +|sot +|bc +|drs +|ss +|md +|sph +|fr +|uf +| |3|3|3|3|2| P: std > 

Mugo ASSOC:: 'np'

< 619h/606H 115v/126V |vs +|sot +|bc +|drs +|ss +|md +|sph +|fr +|uf +| |3|3|3|3|2| P: std > 
// nyyr search here
Pardon?

< 619h/606H 118v/126V |vs +|sot +|bc +|drs +|ss +|md +|sph +|fr +|uf +| |3|3|3|3|2| P: std > 
d
**The Underground Market of Ghore**
   This room and dark and musty, dimly lit by a single torch on the wall. The
floor is covered with rubble and debris making moving around very difficult. A
single figure stands here in the shadows, its eyes reflecting the light from
the torch as it watches you carefully. The only exit is up.
Exits: - Up            [12056] 
You hardly notice this dull object as it gathers dust in the corner.
A round white ball has been left here.
A bail of hay has been pitched here.
Gaptooth stands here in the shadows.

< 619h/606H 114v/126V |vs +|sot +|bc +|drs +|ss +|md +|sph +|f

**Comment by Nyyrazzilyss** [comment]
A mapfile including this can be found at https://github.com/Nyyrazzilyss/NyyLIB/blob/master/NyyLIB011dev/toril.map
