### ISSUE TITLE
Backstab Auto-Assist when mob is wraithform

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#19]
Script spams to "bs shadow" when mob is a wraithform and doesn't switch to kill instead to engage.

Log:
< 721h/776H 130v/130V T: ghost TC: few wounds E: creature EC: awful EP: std P: std > 

Esif misses the illusion of a mage with his bludgeon.
The shadow of Awberuy misses Alane with his slash. (x4)
You score a CRITICAL HIT!
Your mighty pierce brutally wounds the illusion of a mage.
The illusion of a mage is nearly slain by the force of your massive pierce!
The illusion of a mage is nearly slain by the force of your mighty pierce!
The illusion of a mage slumps to the ground.
You pierce the illusion of a mage's heart, you heartbreaker you.
the illusion of a mage is dead! R.I.P.
The illusion of a mage slumps to the ground.
You receive 1 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of the illusion of a mage.
The spectre of a human noble misses the shadow of Awberuy with its drain. (x3)
The shadow of Awberuy parries Rekpezul's lunge at him.
Rekpezul barely wounds the shadow of Awberuy with his average pierce.
The shadow of Awberuy deflects Alane's blow, and strikes back at Alane!
The shadow of Awberuy misses Alane with his slash.
Alane barely wounds the shadow of Awberuy with her average bludgeon.
Lilabipple barely wounds the shadow of Awberuy with her average bludgeon.

< 721h/776H 130v/130V P: std > 
A harmonious combination of notes from Rekpezul soothes your wounds.
You feel better!

< 776h/776H 130v/130V P: std > 
< 757h/776H 130v/130V P: std > 

Aynep completes his spell...
Warraz begins to shimmer.

< 757h/776H 130v/130V P: std > 
Dagkog completes his spell...
Dagkog summons a healing light that surround the entire group.
Your body warms as your wounds are healed.
Isila completes her spell...
Isila surrounds the ghost of a huge stone golem in a brilliant aura of holy power.
Lanlira group-says '>>> Globe Out'
[Globe of Invulnerability has expired on Lanlira.]

< 776h/776H 130v/130V P: std >

Ewiril completes his spell...
Billowing clouds of incendiary gases pour from Ewiril's fingertips!

< 776h/776H 130v/130V P: std > 

[Alane : the mystical circlet of the coiled serpent]
The shadow of Awberuy partially deflects Alane's lunge at him.
Alane barely wounds the shadow of Awberuy with her average bludgeon.
[bs shadow]
Alane barely wounds the shadow of Awberuy with her average bludgeon. (x3)
Alane barely wounds the shadow of Awberuy with her strong bludgeon.
Alane barely wounds the shadow of Awberuy with her average bludgeon.
Aynep gives the ghost of a human noble an order.

< 776h/776H 130v/130V P: std > 
The shadow of Awberuy misses Alane with his slash. (x4)
The shadow of Awberuy partially deflects the spectre of a human noble's lunge at him.
The spectre of a human noble barely wounds the shadow of Awberuy with its average drain.
The shadow of Awberuy partially deflects the spectre of a human noble's lunge at him.
The spectre of a human noble barely wounds the shadow of Awberuy with its average drain.
The shadow of Awberuy deflects the spectre of a human noble's blow, and strikes back at the spectre
of a human noble!
The shadow of Awberuy misses the spectre of a human noble with his slash.
Aynep misses the shadow of Awberuy with his hit.
Rekpezul barely wounds the shadow of Awberuy with his average pierce. (x2)
Dagkog misses the shadow of Awberuy with his sonic bludgeon.
Alane barely wounds the shadow of Awberuy with her average bludgeon. (x2)
Lilabipple barely wounds the shadow of Awberuy with her average bludgeon.

< 776h/776H 130v/130V P: std >

You would pass right through them!
Ewiril starts casting an offensive spell called 'Incendiary Cloud'

< 776h/776H 130v/130V P: std >

< 776h/776H 130v/130V P: std >

You would pass right through them!

< 776h/776H 130v/130V P: std > 
< 757h/776H 130v/130V P: std > 
Bobidibble completes his spell...
Dagkog starts casting a spell called 'Group Heal'

< 757h/776H 130v/130V P: std > 

The ghost of a human noble completes its spell

**Comment by Nyyrazzilyss** [comment]
Should be fixed 7/29 dev
