### ISSUE TITLE
@starttrain tank breaks with only way to recover restarting mudlet

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#190]
I cannot consistently reproduce this, but have run into the issue 3x tonight in about 5 hours of running as my barbarian ranger - I have reproduced this in the past on this version as well, but haven't nailed down the exact repro.

The only way I have been able to recover, once in this state, is to restart mudlet.

Log
======================================

                                                          

< 689h/772H 115v/115V |bds +|ts 2|ss 3|ap 3|ev 7|bs 5| |1|1|1|1|1| T: Gurkz TC: small wounds E:
noble EC: pretty hurt EP: rcl P: std > 

You complete your spell... [ HM (Hunters Mark) ]
an Ashstone noble is marked with a faint blue glow.

< 689h/772H 115v/115V |bds +|ts 2|ss 3|ap 3|ev 7|bs 5| |0|1|1|1|1| T: Gurkz TC: small wounds E:
noble EC: pretty hurt EP: rcl P: std > 
< 689h/772H 115v/115V |bds +|ts 2|ss 3|ap 3|ev 7|bs 5| |0|1|1|1|1| T: Gurkz TC: small wounds E:
noble EC: pretty hurt EP: rcl P: std > 
Your massive slash badly wounds an Ashstone noble.
Your massive sonic slash badly wounds an Ashstone noble.
Your massive slash badly wounds an Ashstone noble.
Your massive sonic slash severely wounds an Ashstone noble.
Your massive slash severely wounds an Ashstone noble.
An Ashstone noble misses you with his hit. (x2)

< 701h/772H 115v/115V |bds +|ts 2|ss 3|ap 3|ev 7|bs 5| |0|1|1|1|1| T: Gurkz TC: few scratches E:
noble EC: pretty hurt EP: rcl P: std > 

An Ashstone noble looks strong again.

< 701h/772H 115v/115V |bds +|ts 1|ss 2|ap 2|ev 6|bs 4| |0|1|1|1|1| T: Gurkz TC: few scratches E:
noble EC: pretty hurt EP: rcl P: std > 
[Gurkz : the mystical circlet of the coiled serpent]
Your massive slash severely wounds an Ashstone noble.
You score a CRITICAL HIT!
Your massive slash brutally wounds an Ashstone noble.
Your massive slash wounds an Ashstone noble harshly.
You miss an Ashstone noble with your slash.
Your massive slash wounds an Ashstone noble harshly.
Your attack only grazes an Ashstone noble as he dodges aside!
You score a CRITICAL HIT!
Your massive slash brutally wounds an Ashstone noble.
An Ashstone noble staggers from your massive slash!

< 739h/772H 115v/115V |bds +|ts 1|ss 2|ap 2|ev 6|bs 4| |0|1|1|1|1| T: Gurkz TC: few scratches E:
noble EC: awful EP: rcl P: std > 

An Ashstone noble is nearly slain by the force of your massive slash!
Your an astral-forged force whip screams in a deafening sonic burst!
Your an astral-forged force whip explodes in a roar of deafening thunder!
Your whip opens a final wound, and an Ashstone noble gives up the fight for good.
an Ashstone noble is dead! R.I.P.
You receive 219,769 XP (0.73%) experience.
Your blood freezes as you hear the rattling death cry of an Ashstone noble.

[Calling function: NextTrainStop()]

< 745h/772H 115v/115V |bds +|ts 1|ss 2|ap 2|ev 6|bs 4| |0|1|1|1|1| P: std > 
You get a small pile of coins from corpse of an Ashstone noble.
There were: 8 platinum coins, 22 gold coins, 8 silver coins, 3 copper coins.

< 746h/772H 115v/115V |bds +|ts 1|ss 1|ap 1|ev 5|bs 3| |0|1|1|1|1| P: std > 

[Moving to: Ashstone Noble (87257)  <.2w>]
< 748h/772H 115v/115V |bds +|ts +|ss 1|ap 1|ev 5|bs 3| |0|1|1|1|1| P: std > 

Corpse of an Ashstone noble melts into the ground, leaving no trace of its passing.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |1|2|3|1|1| P: std > 
a blessed armor potion crumbles to dust and blows away.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |1|2|3|1|1| P: std > 

Sarimam GCC: 'can someone remind me where the entrance to dreadmist is please?'

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std > 

Auction: Only 1 day remaining on a glowing red skull eyepatch!

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std > 

Autosaving...

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std > 

Auction: Only 1 day remaining on a belt of braided gold chains!

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std > 

Sarimam GCC: 'no matter, found it thanks'

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std > 

Corpse of an Ashstone noble melts into the ground, leaving no trace of its passing.
Auction: Only 1 day remaining on a charred cloak covered with runic skulls!
Auction: Only 1 day remaining on a pair of studded hydra hide leggings!

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std (AFK) > 

An Ashstone noble looks at you.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std (AFK) > 

An Ashstone noble says 'Hrmph.'

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|1| P: std (AFK) > 

An Ashstone noble looks at you.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std (AFK) > 

An Ashstone noble says 'Hrmph.'

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std (AFK) > 

Ritel enters from the west.
Rodhal enters from the west.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std (AFK) > 

Ritel leaves west.
Rodhal leaves west.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std (AFK) > 
l
A Large Whitewashed Building
Exits: - West          [87258] 
Corpse of an Ashstone noble is lying here.
A flat-looking longsword has been discarded here.
An Ashstone noble stands here regarding you coldly.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 
w

[Currently moving. Spellcasting is temporarily paused.]

w
Along the Dragonride
   The road is warped here, the once tightly-fit flagstones gently rippled, like
a newly-formed wave in the sea. The stones themselves are worn from use and
there is no shortage of horses, wagons, and caravans tied to hitching posts
spaced at regular intervals along the avenue. The sidewalks, built from charred
and blackened bricks salvaged from the foundations of buildings that did not
survive the explosion, are raised roughly four feet from the ground to allow 
for passengers to board and deboard carriages without having to climb down.
The buildings here are luxurious made of brick and stone.  The Dragonride
continues north and south.
Exits: - North - East  - South - West                  [87256] 
A tall cast-iron streetlight arcs high overhead.
A thug from the Triad RedStone is here looking for trouble. (x3)
The leader of the RedStone Triad is standing here alertly.

< 772h/772H 114v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std >

In a Heavily Buttressed Mansion of Red Brick
   This large house has been made of red clay brick.  The large vertical
walls seemed to be held up by long thick buttresses, likely far more than what
is needed.  Likely an architectural choice it is meant to convey strength.  The
inside of the mansion is only sparsely furnished, either a work in progress or
a reflection of the austere nature of its resident.  What is present is
made of stone and ill suited to comfort.
Exits: - East          [87257] 
Splattered droplets of blood cover the area.
[2] Corpse of an Ashstone noble is lying here.
A flat-looking longsword has been discarded here.
Bago  (RP) (Ogre) stands here.
Rodhal  (Half-Orc) stands here.
Ritel  (Halfling) stands here.

< 772h/772H 113v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 

[Reached train station: (87257) Ashstone noble]

[Players in room - Moving to next station]

* [Ran] Gurkz           : 94.1% (3946)

gcc * ............... Heal F-Heal G-Heal Aura Vit
gcc * ...............

gcc * ... DEATH Top 20 ...
gcc * Gurkz          0
gcc * Bago           0

[Moving to: BankDeposit (87415)  <.e4n4e2sen>]
< 772h/772H 113v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 

A wave of pain tears at Rodhal's body as he falls from a mindless cycle of rage.

< 772h/772H 114v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 

Ritel leaves east.
Rodhal leaves east.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std > 
@resettrain
[Setting statname to unset]
[Setting rescuetype to off]
[All train triggers disabled]
@starttrain tank
[Setting statname to unset]
[Setting rescuetype to off]
[All train triggers disabled]
[Laying train tracks...]
[Setting autoloot to coins]
[Setting flee to off]
[Setting autocast to true]
[Setting rescuetype to all]
[Setting auto_heal to true]
[Setting rantr to true]
[Setting ranks to true]
[Setting ransp to true]
[Setting rancn to true]
[Setting ranha to true]
[Setting rants to true]
[Setting ranss to true]
[Setting ranap to true]
[Setting ranev to true]
[Setting ranbs to true]
[Setting ranhm to true]
[Setting ranlita to true]
[Setting ranbof to true]
[Setting ranhot to true]
[Setting raneld to true]
[Setting rangrf to true]
[Setting ranab to true]
[Setting ranclw to true]

[Resetting stats counters.]
[Sending starting movement]

[Moving to: BankDeposit (87415)  <.e4n4e2sen>]
You now feel like a true hero, no auto-fleeing here! :-)

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std >

You will no longer auto-assist after being rescued.

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std >

But you are a member of no group?!

< 772h/772H 115v/115V |bds +|ts +|ss +|ap +|ev +|bs +| |3|3|3|3|2| P: std >

**Comment by Nyyrazzilyss** [comment]
Re-open if this happens again with 9/16 dev
