### ISSUE TITLE
Dev Script - @starttrain tank did not resume after killing nightwatch member

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#194]
lectric Discharge)]

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev +|bs 9| |0|1|1|2|1| T: Gurkz TC: excellent E: noble
EC: few wounds EP: rcl P: std > 

You complete your spell... [ ELD (Electric Discharge) ]
Static fills the air as your weapons are wreathed in crackling electricity.

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev +|bs 9| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: few wounds EP: rcl P: std > 

Strands of darkness shroud Kuparodad's form as he lands a wicked strike upon an Ashstone noble.
An Ashstone noble cowers in fear!

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev +|bs 9| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: nasty wounds EP: rcl P: std > 

[MELEE: Armor Splinter] AP

Kuparodad starts casting a spell called 'Aura of Death'

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev +|bs 9| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: nasty wounds EP: rcl P: std > 

Kuparodad completes his spell...
A dark mist surrounds Kuparodad.

[Kuparodad : the mystical circlet of the coiled serpent]
Kuparodad misses an Ashstone noble with his slash.
Kuparodad's Unholy Avenger glows jet black, and plunges itself into
an Ashstone noble's body, causing it to writhe in pain.
Kuparodad badly wounds an Ashstone noble with his massive slash.
Kuparodad slightly wounds an Ashstone noble with his massive slash. (x2)
Kuparodad's Unholy Avenger glows jet black, and plunges itself into
an Ashstone noble's body, causing it to writhe in pain.
Kuparodad severely wounds an Ashstone noble with his massive slash.
Kuparodad slightly wounds an Ashstone noble with his massive slash.
< 748h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev +|bs 8| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: nasty wounds EP: rcl P: std >

You strike the weak spots in an Ashstone noble's armor, leaving him vulnerable.
Your weapon disharges a massive blast of crackling electricity!
An Ashstone noble is stunned!
An Ashstone noble trembles and appears vulnerable!

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap 6|ev +|bs 7| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: pretty hurt EP: rcl P: std >

You group-say '[Ashstone Noble has nasty wounds!]'

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap 6|ev +|bs 7| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: pretty hurt EP: rcl P: std > 
Kuparodad badly wounds an Ashstone noble with his massive slash.
Kuparodad misses an Ashstone noble with his slash.
Kuparodad badly wounds an Ashstone noble with his massive slash.
Your massive slash severely wounds an Ashstone noble. (x3)
Your massive slash brutally wounds an Ashstone noble.
Your massive slash wounds an Ashstone noble harshly.
An Ashstone noble misses you with his hit.
An Ashstone noble staggers about, but manages to get to his feet.

< 748h/748H 116v/116V |bds +|ts +|ss 1|ap 6|ev +|bs 7| |0|1|1|1|1| T: Gurkz TC: excellent E: noble
EC: awful EP: std P: std > 

A member of the Nightwatch yells, 'To battle one of us, is to battle us all!'
You partially deflect a member of the Nightwatch's lunge at you.
A member of the Nightwatch slightly wounds you with her powerful slash.
Kuparodad's weapon unleashes a torrent of dark power as he strikes an Ashstone noble, knocking him
to the ground.

< 715h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev +|bs 7| |0|1|1|1|1| T: Gurkz TC: few scratches E:
noble EC: awful EP: rcl P: std > 
You are rescued by Kuparodad, you are confused, but grateful!

< 715h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev +|bs 7| |0|1|1|1|1| T: Gurkz TC: few scratches E:
noble EC: awful EP: rcl P: std > 

[Gurkz : the mystical circlet of the coiled serpent]
Your longsword glows dark and bites into an Ashstone noble's neck.
Nothing seems to happen.
You critically wound an Ashstone noble with a massive slash!
You enshroud an Ashstone noble in a mist of blood with your massive slash!
You score a CRITICAL HIT!
You beautifully slash an Ashstone noble into two parts - both dead.
an Ashstone noble is dead! R.I.P.
You receive 104,381 XP (0.35%) experience.
Your blood freezes as you hear the rattling death cry of an Ashstone noble.

[Calling function: NextTrainStop()]

< 723h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev +|bs 7| |0|1|1|1|1| P: std > 

Kuparodad parries a member of the Nightwatch's lunge at him.
A member of the Nightwatch's attack only grazes Kuparodad as he dodges aside!
A member of the Nightwatch slightly wounds Kuparodad with her mighty slash.
[ Rescue: Kuparodad ]

< 724h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev +|bs 7| |0|1|1|1|1| P: std > 
< 725h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std >

You get a small pile of coins from corpse of an Ashstone noble.
There were: 12 platinum coins, 21 gold coins, 6 silver coins, 4 copper coins.

< 725h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std >

You fail the rescue.
Kuparodad starts casting an offensive spell called 'Sigil of Pain'

< 726h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std > 

Kuparodad completes his spell...
Kuparodad summons a blood-red ray to sear a sigil of pain into a member of the Nightwatch's flesh!

< 726h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std > 

Kuparodad barely wounds a member of the Nightwatch with his massive slash.
[KILL Nightwatch]
A member of the Nightwatch partially deflects Kuparodad's lunge at her.
Kuparodad barely wounds a member of the Nightwatch with his powerful slash.
Kuparodad's attack only grazes a member of the Nightwatch as she dodges aside!
Kuparodad barely wounds a member of the Nightwatch with his powerful slash.
Kuparodad deflects a member of the Nightwatch's blow, and strikes back at a member of the
Nightwatch!
A member of the Nightwatch parries Kuparodad's lunge at her.
Kuparodad deflects a member of the Nightwatch's blow, and strikes back at a member of the
Nightwatch!
Kuparodad misses a member of the Nightwatch with his slash.
A member of the Nightwatch attemps a shieldpunch at Kuparodad, but falls short.

< 727h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std > 

[Kuparodad : the mystical circlet of the coiled serpent]
A member of the Nightwatch partially blocks Kuparodad's attack with her shield!
Kuparodad barely wounds a member of the Nightwatch with his powerful slash.
A member of the Nightwatch dodges Kuparodad's attack.
A member of the Nightwatch blocks Kuparodad's attack with her shield!

< 728h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev +|bs 6| |0|1|1|1|1| P: std > 
< 729h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| P: std > 

< 729h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| P: std >

< 730h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| P: std >

Your massive slash barely wounds a member of the Nightwatch.

< 732h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: few scratches EP: std P: std > 

[MELEE: Sweeping Strike] SS

@fwalk 87253
[Can't fwalk while in combat]
A member of the Nightwatch dodges your futile attack.
Your massive slash barely wounds a member of the Nightwatch.
A member of the Nightwatch blocks your futile attempt with her shield! (x2)
Your massive slash barely wounds a member of the Nightwatch.
Kuparodad's eyes glow blood red as power from his sword courses through his
body. Bloody wounds close before your eyes as they are healed by his
Unholy Avenger.
Kuparodad barely wounds a member of the Nightwatch with his massive slash.
Kuparodad's attack only grazes a member of the Nightwatch as she dodges aside!
Kuparodad barely wounds a member of the Nightwatch with his powerful slash.
A member of the Nightwatch deflects Kuparodad's blow, and strikes back at Kuparodad!
Kuparodad parries a member of the Nightwatch's lunge at him.
Kuparodad deflects a member of the Nightwatch's blow, and strikes back at a member of the
Nightwatch!
A member of the Nightwatch parries Kuparodad's lunge at her.
A member of the Nightwatch's attack only grazes Kuparodad as he dodges aside!
A member of the Nightwatch slightly wounds Kuparodad with her powerful slash.

< 746h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: few scratches EP: std P: std > 
Kuparodad's weapon begins to pulse with a sinister glow as his soul fills with vengeance.
Kuparodad's weapon flares with purifying dark flames as he strikes a member of the Nightwatch.

< 747h/748H 116v/116V |bds +|ts +|ss +|ap 3|ev +|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: few scratches EP: std P: std > 

A member of the Nightwatch parries your futile lunge at her. (x2)
A member of the Nightwatch blocks your futile attempt with her shield!
Your attack only grazes a member of the Nightwatch as she dodges aside!
Your powerful slash barely wounds a member of the Nightwatch.
A member of the Nightwatch parries your futile lunge at her.
A member of the Nightwatch parries Kuparodad's lunge at her.
A member of the Nightwatch deflects Kuparodad's blow, and strikes back at Kuparodad!
A member of the Nightwatch misses Kuparodad with her slash.
Kuparodad's attack only grazes a member of the Nightwatch as she dodges aside!
Kuparodad barely wounds a member of the Nightwatch with his powerful slash.
A member of the Nightwatch misses Kuparodad with her slash.
A member of the Nightwatch's attack only grazes Kuparodad as he dodges aside!
A member of the Nightwatch slightly wounds Kuparodad with her mighty slash.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 2|ev +|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: small wounds EP: std P: std >

You group-say '[Moving to: Ashstone Noble (87253)  <.w2ne>]'

[Currently moving. Spellcasting is temporarily paused.]

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 2|ev +|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: small wounds EP: std P: std >

Banzai! To the rescue...

[No longer moving. Spellcasting has resumed]

[ Rescue: Kuparodad ]
Kuparodad's weapon unleashes a torrent of dark power as he strikes a member of the Nightwatch,
knocking her to the ground.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 2|ev +|bs 4| |0|1|1|1|1| T: Gurkz TC: excellent E:
nightwatch EC: small wounds EP: rcl P: std > 

You partially deflect a member of the Nightwatch's lunge at you.
A member of the Nightwatch slightly wounds you with her powerful slash.
A member of the Nightwatch misses you with her slash.
Your attack only grazes a member of the Nightwatch as she dodges aside!
Your massive slash barely wounds a member of the Nightwatch.
You miss a member of the Nightwatch with your slash.
Your massive slash barely wounds a member of the Nightwatch. (x3)
A member of the Nightwatch partially blocks Kuparodad's attack with her shield!
Kuparodad barely wounds a member of the Nightwatch with his awesome slash.
Kuparodad barely wounds a member of the Nightwatch with his massive slash. (x2)

< 734h/748H 116v/116V |bds +|ts +|ss +|ap 1|ev +|bs 3| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: small wounds EP: rcl P: std > 
You sweep attack a member of the Nightwatch with unbound fury, knocking her off balance!

< 734h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: small wounds EP: rcl P: std > 

[MELEE: Eviscerate] EV
You are rescued by Kuparodad!
You immediately assist Kuparodad in the fight!

< 734h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: small wounds EP: rcl P: std > 

< 734h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: small wounds EP: rcl P: std >

< 734h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: small wounds EP: rcl P: std >

Banzai! To the rescue...
[ Rescue: Kuparodad ]

< 734h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: small wounds EP: rcl P: std > 

[Gurkz : the mystical circlet of the coiled serpent]
A member of the Nightwatch parries your futile lunge at her.
A member of the Nightwatch blocks your futile attempt with her shield!
Your attack glances off a member of the Nightwatch's shield, but finds its mark!
Your awesome slash barely wounds a member of the Nightwatch.

< 739h/748H 116v/116V |bds +|ts +|ss 3|ap 1|ev +|bs 2| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: small wounds EP: rcl P: std > 

You parry a member of the Nightwatch's lunge at you.
A member of the Nightwatch severely wounds you with her massive slash.
Your massive slash barely wounds a member of the Nightwatch.
You miss a member of the Nightwatch with your slash.
A member of the Nightwatch partially deflects your lunge at her.
Your mighty slash barely wounds a member of the Nightwatch.
Your massive slash barely wounds a member of the Nightwatch.
You miss a member of the Nightwatch with your slash.
A member of the Nightwatch parries Kuparodad's lunge at her.
Kuparodad's Unholy Avenger glows jet black, and plunges itself into
a member of the Nightwatch's body, causing it to writhe in pain.
A member of the Nightwatch seems to be blinded!
Kuparodad barely wounds a member of the Nightwatch with his massive slash.
Kuparodad's Unholy Avenger glows jet black, and plunges itself into
a member of the Nightwatch's body, causing it to writhe in pain.
A member of the Nightwatch seems to be blinded!
Kuparodad barely wounds a member of the Nightwatch with his massive slash.

< 687h/748H 116v/116V |bds +|ts +|ss 2|ap +|ev +|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std > 

Kuparodad raises his weapon menacingly as it fades out, becoming smoky and grey.
Kuparodad's grim strike cuts through the air next to a member of the Nightwatch, who shivers in pain
.

< 688h/748H 116v/116V |bds +|ts +|ss 2|ap +|ev +|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std > 
You swing your weapons in lethal arcs, dousing the area with a member of the Nightwatch's blood.
A member of the Nightwatch is weakened!

< 688h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 9|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std >

But nobody is fighting him?

< 688h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 9|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std >

< 688h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 9|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std > 

A member of the Nightwatch misses you with her slash. (x2)
Your massive slash barely wounds a member of the Nightwatch. (x2)
Your attack only grazes a member of the Nightwatch as she dodges aside!
Your mighty slash barely wounds a member of the Nightwatch.
Your massive slash slightly wounds a member of the Nightwatch.
Kuparodad barely wounds a member of the Nightwatch with his massive slash. (x2)
A member of the Nightwatch blocks Kuparodad's attack with her shield!

< 702h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 9|bs 1| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: rcl P: std > 

A member of the Nightwatch misses you with her slash. (x2)
A member of the Nightwatch clambers to her feet.

[MELEE: Sweeping Strike] SS
Your attack only grazes a member of the Nightwatch as she dodges aside!
Your powerful slash barely wounds a member of the Nightwatch.
You miss a member of the Nightwatch with your slash.
A member of the Nightwatch parries your futile lunge at her. (x2)
Your massive slash barely wounds a member of the Nightwatch.
A member of the Nightwatch parries Kuparodad's lunge at her. (x2)
Kuparodad barely wounds a member of the Nightwatch with his massive slash.

< 715h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 7|bs +| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: few wounds EP: std P: std >

That power hasn't recharged yet!

Kuparodad's weapon unleashes a torrent of dark power as he strikes a member of the Nightwatch,
knocking her to the ground.

< 715h/748H 116v/116V |bds +|ts +|ss 1|ap +|ev 7|bs +| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

[MELEE: Bladestorm] BS

You spin and leap through the fray, unleashing a torrent of steel on your enemies!
You rain a series of deadly blows on a member of the Nightwatch!
Kuparodad starts casting a spell called 'Aspect of Domination'

< 715h/748H 116v/116V |bds +|ts +|ss +|ap +|ev 7|bs 9| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

Kuparodad completes his spell...
Shadowy black wings sprout from Kuparodad's back as he starts emanating a wave of seething hatred.

< 715h/748H 116v/116V |bds +|ts +|ss +|ap +|ev 7|bs 9| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

A member of the Nightwatch misses you with her slash.
You parry a member of the Nightwatch's lunge at you.
Your massive slash barely wounds a member of the Nightwatch. (x4)
Your massive slash slightly wounds a member of the Nightwatch.
A member of the Nightwatch deflects Kuparodad's blow, and strikes back at Kuparodad!
A member of the Nightwatch misses Kuparodad with her slash.
Kuparodad barely wounds a member of the Nightwatch with his massive slash. (x2)

< 739h/748H 116v/116V |bds +|ts +|ss +|ap +|ev 7|bs 9| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 
Kuparodad fails miserably in his attempt to rescue you.

< 740h/748H 116v/116V |bds +|ts +|ss +|ap +|ev 7|bs 9| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

A member of the Nightwatch looks strong again.

< 740h/748H 116v/116V |bds +|ts +|ss +|ap +|ev 6|bs 8| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

[MELEE: Armor Splinter] AP
You strike the weak spots in a member of the Nightwatch's armor, leaving her vulnerable.
A member of the Nightwatch trembles and appears vulnerable!

< 740h/748H 116v/116V |bds +|ts +|ss +|ap 6|ev 5|bs 7| |0|1|1|1|1| T: Gurkz TC: few scratches E:
nightwatch EC: nasty wounds EP: rcl P: std > 

You dodge a member of the Nightwatch's vicious attack.
A member of the Nightwatch misses you with her slash.
Your attack glances off a member of the Nightwatch's shield, but finds its mark!
Your awesome slash barely wounds a member of the Nightwatch.
Your massive slash slightly wounds a member of the Nightwatch. (x2)
You miss a member of the Nightwatch with your slash. (x2)
A member of the Nightwatch dodges Kuparodad's attack.
Kuparodad slightly wounds a member of the Nightwatch with his massive slash. (x2)

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 6|ev 5|bs 7| |0|1|1|1|1| T: Gurkz TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std > 

Kuparodad radiates a powerful sense of crushing dread as he confronts a member of the Nightwatch.
A member of the Nightwatch turns her attention to Kuparodad.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 6|ev 5|bs 7| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std >

[ Rescue: Kuparodad ]
< 748h/748H 116v/116V |bds +|ts +|ss +|ap 6|ev 5|bs 7| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std >

You fail the rescue.
[ Rescue: Kuparodad ]

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 6|ev 5|bs 7| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std > 

A member of the Nightwatch misses Kuparodad with her slash. (x2)
Your massive slash slightly wounds a member of the Nightwatch. (x2)
You miss a member of the Nightwatch with your slash.
Your massive slash slightly wounds a member of the Nightwatch.
A member of the Nightwatch parries your futile lunge at her.
Kuparodad badly wounds a member of the Nightwatch with his massive slash.
Kuparodad's Unholy Avenger glows jet black, and plunges itself into
a member of the Nightwatch's body, causing it to writhe in pain.
Kuparodad wounds a member of the Nightwatch harshly with his massive slash.
Kuparodad badly wounds a member of the Nightwatch with his massive slash.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev 4|bs 6| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std > 

[MELEE: Twin Strike] TS

Kuparodad lands a glancing blow upon a member of the Nightwatch with his dread weapon.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev 4|bs 6| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std > 
You fail the rescue.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 5|ev 4|bs 6| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: pretty hurt EP: rcl P: std > 
[ Rescue: Kuparodad ]

[Kuparodad : the mystical circlet of the coiled serpent]
Kuparodad severely wounds a member of the Nightwatch with his massive slash. (x2)
A member of the Nightwatch deflects Kuparodad's blow, and strikes back at Kuparodad!
A member of the Nightwatch misses Kuparodad with her slash.
Kuparodad misses a member of the Nightwatch with his slash.
Kuparodad severely wounds a member of the Nightwatch with his massive slash.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev 3|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std > 

A member of the Nightwatch misses Kuparodad with her slash.
Kuparodad partially deflects a member of the Nightwatch's lunge at him.
A member of the Nightwatch badly wounds Kuparodad with her awesome slash.
A member of the Nightwatch clambers to her feet.
You miss a member of the Nightwatch with your slash.
Your massive slash wounds a member of the Nightwatch harshly.
A member of the Nightwatch blocks your futile attempt with her shield!
Your longsword glows dark and bites into a member of the Nightwatch's neck.
Nothing seems to happen.
Your massive slash badly wounds a member of the Nightwatch.
Kuparodad badly wounds a member of the Nightwatch with his massive slash.
A member of the Nightwatch parries Kuparodad's lunge at her.
Kuparodad badly wounds a member of the Nightwatch with his massive slash.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev 3|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: std P: std > 

Kuparodad's weapon unleashes a torrent of dark power as he strikes a member of the Nightwatch,
knocking her to the ground.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap 4|ev 3|bs 5| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std > 
You strike at a member of the Nightwatch with both weapons, landing glancing blows.

< 748h/748H 116v/116V |bds +|ts 3|ss +|ap 3|ev 3|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std >

< 748h/748H 116v/116V |bds +|ts 3|ss +|ap 3|ev 3|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std >

You fail the rescue.
[ Rescue: Kuparodad ]

< 748h/748H 116v/116V |bds +|ts 3|ss +|ap 3|ev 3|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std > 

A member of the Nightwatch closes the gap in her defenses.

< 748h/748H 116v/116V |bds +|ts 3|ss +|ap 3|ev 3|bs 4| |0|1|1|1|1| T: Kuparodad TC: excellent E:
nightwatch EC: awful EP: rcl P: std > 

A member of the Nightwatch misses Kuparodad with her slash. (x2)
You enshroud a member of the Nightwatch in a mist of blood with your massive slash!
A member of the Nightwatch is nearly slain by the force of your massive slash!
You beautifully slash a member of the Nightwatch into two parts - both dead.
a member of the Nightwatch is dead! R.I.P.
You receive 169,596 XP (0.57%) experience.
Your blood freezes as you hear the rattling death cry of a member of the Nightwatch.

< 748h/748H 116v/116V |bds +|ts 3|ss +|ap 3|ev 3|bs 4| |0|1|1|1|1| P: std > 
< 748h/748H 116v/116V |bds +|ts 2|ss +|ap 2|ev 2|bs 3| |0|1|1|1|1| P: std > 

< 748h/748H 116v/116V |bds +|ts 2|ss +|ap 2|ev 2|bs 3| |0|1|1|1|1| P: std >

But nobody is fighting him?

< 748h/748H 116v/116V |bds +|ts 2|ss +|ap 2|ev 2|bs 3| |0|1|1|1|1| P: std >

You get a few coins from corpse of a member of the Nightwatch.
There were: 3 platinum coins, 14 gold coins, 1 silver coin, 2 copper coins.

< 748h/748H 116v/116V |bds +|ts 1|ss +|ap 2|ev 1|bs 3| |0|1|1|1|1| P: std > 

Lonetorile ASSOC:: 'worm me'

< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |0|2|2|1|1| P: std > 

Sodat ASSOC:: 'lf another enchanter!'

< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |0|2|2|1|1| P: std > 
l
An Airy Building of Light Stonework
Exits: - West          [87249] 
A flat-looking longsword has been discarded here.
[3] A slender and curved sword has been discarded.
A tightly woven chain hauberk has been cast aside.
A cap with a blue feather is lying here.
An iron shield, studded with small spikes lies on the ground.
Corpse of a member of the Nightwatch is lying here.
[2] Corpse of an Ashstone noble is lying here.
An Ashstone noble stands here flitting about.
Kuparodad  (Duergar) stands here.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |2|2|2|2|1| P: std > 
l me
You see nothing special about him.
Gurkz is a medium-sized level 50 Barbarian.
He is in excellent condition.

<worn as a badge>    a tattoo of three bolts of lightning over a cutlass (glowing)
<worn on head>       the mystical circlet of the coiled serpent
<worn on eyes>       an eyepatch of the Githzerai Cenobite (illuminating)
<worn in ear>        a tiny mithril stud with a single glowing rune (x2)
<worn on face>       the severed face of a marilith demon
<worn around neck>   a thick titanium band of volance (x2)
<worn on body>       a lightweight suit of linked mail body armor
<worn about body>    a cloak of the Fay
<worn as quiver>     an ancient tooled dragonhide quiver
<worn about waist>   a thick girdle of silver dragonhide with adamantine bolsters
<worn on arms>       matte black drow chainmail sleeves
<worn around wrist>  a runed enamel bracer (x2)
<worn on hands>      a pair of gauntlets wreathed in electricity (glowing)
<worn on finger>     a flaming ring of the efreeti (x2)
<primary weapon>     a rune graven adamantine longsword (glowing)
<secondary weapon>   a rune graven adamantine longsword (glowing)
<worn on legs>       some silver scaled leggings of attack
<worn on feet>       the mystical boots of stability
< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |2|2|2|2|1| P: std > 
l
An Airy Building of Light Stonework
Exits: - West          [87249] 
A flat-looking longsword has been discarded here.
[3] A slender and curved sword has been discarded.
A tightly woven chain hauberk has been cast aside.
A cap with a blue feather is lying here.
An iron shield, studded with small spikes lies on the ground.
Corpse of a member of the Nightwatch is lying here.
[2] Corpse of an Ashstone noble is lying here.
An Ashstone noble stands here flitting about.
Kuparodad  (Duergar) stands here.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |2|2|2|2|1| P: std > 
pond
You detach from reality for a moment, pondering.

< 748h/748H 116v/116V |bds +|ts +|ss +|ap +|ev +|bs +| |2|2|2|2|1| P: std > 
l room
An Airy Building of Light Stonework
   This stone mansion seems to rise up out of the earth and reach towards
the heavens.  The light stonework and elegant buttresses lend it strength
without blocking any of the light that generously flows into the interior
through its many arcade windows.  Inside columns line the walls holding up the
vaulted ceilings.  Ornate wooden furniture is generously distributed through
the rooms providing places to enjoy the sunlight.
Exits: - West 
A flat-looking longsword has been discarded here.
[3] A slender and curved sword has been discarded.
A tightly woven chain hauberk has been cast aside.
A cap with a blue feather is lying here.
An iron shield, studded with small spikes lies on

**Comment by Nyyrazzilyss** [comment]
9/16 dev
