### ISSUE TITLE
Muspelheim - Map issues (four currently listed)

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#195]
**1st issue: uncaught teleporter on 4th grid**

Moving east on 4th grid from 78463 teleports me to room number 78455:

                                                     
               

A Sheltered Valley
   The ground beneath your feet feels much more stable
then it was on the eastern side of the citadel.  It still
rumbles and vibrates every time one of the volcanoes erupts
or lets lose a shower of pyroclastic debris, but it doesn't
feel like its moments from breaking apart beneath your feet
and plunging you head first into a fiery pit.  West of you
a great copse of ironwoods stands tall, its arching branches
shading the ground all around.  South of this the same small
forest has been chopped down for use in building supplies.
The sky above you bears ominous storm clouds, thick black
roiling clouds arching with bolts of lightning, they seem
to be cover this valley, spewing forth from the mouth of
Mount Firb to your south.
Exits: - East  - South - West          [78463]  [Hidden]

< 623h/569H 227v/228V |3|3|3|3|2| P: std > 
e
               

At the Base of Mount Firb
   Mount Firb rises up behind you, all gloomy smoke and
spitting lava, it shakes as though it were trying to rip
itself apart.  Lava spits out of its top, and rolls its
way down the western side forming a huge lake.
The smoke curling out the top forms a massive cloud that
shadows almost the entire valley, it seems to be drawn
towards the great castle to the northwest.  From here
you can see the small ironwood forest to your northwest,
and the great citadel to your northeast.  Just to your
west a large geyser spits water high into the air, a mist
hangs in the air from the spray.
**Exits: - North - East  - West  [Error: mud 'At the Base of Mount Firb' doesn't match mapper 'At the
 Base of Mount Nueib' at '78462']          [78462]  [Hidden]**

< 623h/569H 226v/228V |3|3|3|3|2| P: std > 

[Globe of Invulnerability has expired on Manorak.]

Your globe shimmers, and fades into the air.

< 622h/569H 228v/228V |3|3|3|3|2| P: std >

You group-say '[[ GLOBE OUT ]]'

< 622h/569H 228v/228V |3|3|3|3|2| P: std > 

High above you the sky is a dark blue.  Looking through the ever present smoke from the volcanoes
you can see brightly twinkling stars.

< 617h/569H 228v/228V |3|3|3|3|2| P: std > 
e
               

At the Base of Mount Firb
   Mount Firb rises up behind you, all gloomy smoke and
spitting lava, it shakes as though it were trying to rip
itself apart.  Lava spits out of its top, and rolls its
way down the western side forming a huge lake.
The smoke curling out the top forms a massive cloud that
shadows almost the entire valley, it seems to be drawn
towards the great castle to the northwest.  From here
you can see the small ironwood forest to your northwest,
and the great citadel to your northeast.
**Exits: - North - West  [Error: mud 'At the Base of Mount Firb' doesn't match mapper 'At the Base of
 Mount Nueib' at '78461']   [78461]  [Hidden]**

< 611h/569H 227v/228V |3|3|3|3|2| P: std > 
@find

[Searching... Multiple (3) matches found: At the Base of Mount Firb]

You scan north...
A Well Traveled Path
Exits: -N -E -S -W

You scan west...
At the Base of Mount Firb
Exits: -N -E -W

< 611h/569H 228v/228V |3|3|3|3|2| P: std > 
w
               

At the Base of Mount Firb
   Mount Firb rises up behind you, all gloomy smoke and
spitting lava, it shakes as though it were trying to rip
itself apart.  Lava spits out of its top, and rolls its
way down the western side forming a huge lake.
The smoke curling out the top forms a massive cloud that
shadows almost the entire valley, it seems to be drawn
towards the great castle to the northwest.  From here
you can see the small ironwood forest to your northwest,
and the great citadel to your northeast.  Just to your
west a large geyser spits water high into the air, a mist
hangs in the air from the spray.
Exits: - North - East  - West          [78455]  [Hidden]

< 610h/569H 227v/228V |3|3|3|3|2| P: std > 

========================================
**2nd issue:** Two rooms are not properly colored on the minimap to indicate they are the lava bridges, between 1st and 2nd grid are colored white, when they should be colored light blue like the other lava rooms.  These are rooms where an elementalist/invoker need to c 'icewave' (not powers version) to get the lava bridge to appear. I sus

Not sure how to denote the need to c 'icewave', but it would be a good note on the minimap for all players to have.  Some are stuck trying to use powers icewave, while others have no idea how to get the rooms to reveal.  Having the minimap white gives the impression users can simply walk between 1st and 2nd grid, which isn't the case.

**Rooms:
94664 - Over a River of Lava
94663**

=====
### 3rd issue: 94663 room is missing room name, which should be Over a River of Lava (burning) (Water)

                                
At the Base of Mount Nueib
   On the western side of the great river of lava you
are almost close enough to see the troop movements
on the parapets of the small guard citadel to the west.
Fire giants pace around it from south to north at
a tightly regimented pace.  Up the side of Mount Nueib
ash sprinkles down like a bizarre form of snow.  You
can see below you the flowing river of lava as it courses
southwards underground. For the moment the heat is
tolerable, but if it gets any hotter, you'll have to do
something to cool the area down some.
Exits: - East  - South - West          [78351]  [Hidden]

< 692h/569H 223v/228V |3|3|3|3|2| P: std > 
e
               

**Over a River of Lava (burning) (Water)**
   The abrupt freezing of the surrounding area has
caused a bridge to form over the surface of the lava
but the heat is melting it, already wisps of steam pour out
of the icey bridge you've formed, and water drips
hissing into the river, evaporating before if ever reaches it.
Below you the terrible current of liquid hot magma courses
belching and bubbling.  The heat is intense and you have
to shield your eyes to look at it, steam spits out of
the ground all around you, and chunks of rock crumble
off and fall into the river below.  The ground seems to
vibrate with the force of the currents swirling past
underneath you.
Exits: - East  - West  [Error: mud 'Over a River of Lava (burning) (Water)' doesn't match mapper ''
 at '94663']   [94663]  [Hidden]

< 691h/569H 222v/228V |3|3|3|3|2| P: std > 
e
               

At the Base of Mount Nueib
   Standing at the base of Mount Nueib you have a better
view of the surrounding area.  Immediately below you
a river of lava flows out from the base of the mountain
and travels south, far below the surface.  Having just
cleared the southern tip of the mountain you can see a
stone fortress through the valley to the northwest. A
light sprinkling of grey ash covers the ground around
here, evidence of the constant volcanic eruptions.
Heat rises from the flowing river of lava to your west,
and you can feel it radiate even at this distance, for
the moment tolerable, but if it gets any hotter, you'll
have to do something to cool the area down some.
Exits: - East  - South - West          [78311]  [Hidden]

=======

**4th issue**: 1st grid, the mud is missing a line break after the room description and before the exits, which breaks the map.  I believe we have talked about this before, not sure if there is a fix you can implement while waiting for mud to fix the room or if we just need to bug the mud again to fix the issue.

                         
< 670h/569H 228v/228V |3|3|3|3|2| P: std > 
l
At the Base of Mount Siva
Exits: - North - South - West          [78295]  [Hidden]

< 668h/569H 228v/228V |3|3|3|3|2| P: std > 
n
               

**A Charred Valley in Muspelheim
   You can still see the heavy branches of Yggdrasil high
up to the east from here.  The valley of Muspelheim
is very dark, black glassy obsidian covers most of the
ground around here, ancient lava flows attest to the
brutality of this area.  Volcanoes surround the area on
all sides, belching smoke and spitting lava, you can
see movement in the valley, although from this distance
you can't make out exactly what it could be.  High above you
creatures circle in the air, flying higher then the tops of
the mountains.Exits: - North - East  - South - West** 
An enormous bird circles about.

< 666h/569H 227v/228V |3|3|3|3|2| P: std > 
e
               

At the Base of Mount Siva
   The valley of Muspelheim is very dark, black glassy
obsidian covers most of the ground around here, ancient
lava flows attest to the brutality of this area.
Volcanoes surround the area on all sides, belching smoke
and spitting lava, you can see movement in the valley,
although from this distance you can't make out exactly
what it could be.  You can also make out several circling
forms high above in the sky.
Exits: - North - West  [Error: mud 'At the Base of Mount Siva' doesn't match mapper 'A Charred
 Valley in Muspelheim' at '78296']   [78296]  [Hidden]

< 665h/569H 227v/228V |3|3|3|3|2| P: std >

**Comment by Gyrx** [comment]
For issue #4, the missing break line between room descrip and exits here is the torilmud github issue: https://github.com/torilmud/issues/issues/465

**Comment by Nyyrazzilyss** [comment]
9/16 dev
