### ISSUE TITLE
Map Error - Labyrinth of No Return

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#196]
My map didn't lose sync, but I did notice a map error while running through.  Typo in room name maybe?

                                        

Along an Underground Stream (Water)
   The underground stream slows in its pace here, and the bed of the
stream is more shallow. It would appear that the stream comes to an
end somewhere to the north of here, while it possibly contines on to
its source further south.
Exits: - North - South  [14194]  [Hidden]

< 591h/591H 41v/146V P: std >

At the Foot of an Underground Stream (Water)
   The chamber here is the foot of an underground stream. Drapery
consisting of thin sheets of rock hangs from the ceiling. Some
helictites can also be seen along the walls, their strange twisted
shape lending to the eerie quiet in these labyrinthian caves.
**Exits: - East  - South [Error: mud 'At the Foot of an Underground Stream (Water)' doesn't match
 mapper 'Exits: -E -S' at '14193']   [14193]  [Hidden]**
A hairy sasquatch is here, howling with savage glee.(Red Aura)

< 591h/591H 40v/146V P: std >

Passage in the Labyrinth of No Return
   This is a dark passageway in the labyrinth. The air is thick and
heavy, stale with the odor of death and decay. There are hardly any
sounds audible, but some sinister creature must reside within, for
there are bones strewn along the corridor, some of them humanoid. All
the passageways seem to look alike, making it very easy to get lost.
Exits: - North - South - West          [14108]  [Hidd

**Comment by Nyyrazzilyss** [comment]
9/16 dev
