### ISSUE TITLE
@starttrain tank - script did not resume when Ashstone holyman worded at awful condition

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#197]
Your massive slash severely wounds an Ashstone holyman. (x2)
You miss an Ashstone holyman with your slash.

< 428h/540H 120v/120V |vs +|ds 47|dc 9|lh +|ts +|brs 4|trs 1|tn +|wws +| |3|3|1|1|1| T: Ishidin TC:
small wounds E: holy EC: nasty wounds EP: std P: std > 

Your massive slash severely wounds an Ashstone holyman.
Your attack only grazes an Ashstone holyman as he dodges aside!
Your awesome slash severely wounds an Ashstone holyman.
You score a CRITICAL HIT!
You enshroud an Ashstone holyman in a mist of blood with your massive slash!
You critically wound an Ashstone holyman with a massive slash!

< 428h/540H 120v/120V |vs +|ds 46|dc 7|lh +|ts +|brs 3|trs +|tn +|wws +| |3|3|1|1|1| T: Ishidin TC:
small wounds E: holy EC: awful EP: std P: std > 

An Ashstone holyman completes his spell...
An Ashstone holyman utters the words, 'vitality'.

< 428h/540H 120v/120V |vs +|ds 45|dc 6|lh +|ts +|brs 2|trs +|tn +|wws +| |3|3|1|1|1| T: Ishidin TC:
small wounds E: holy EC: pretty hurt EP: std P: std > 

Your massive slash brutally wounds an Ashstone holyman.
An Ashstone holyman staggers from your massive slash!
You critically wound an Ashstone holyman with a massive slash!
An Ashstone holyman misses you with his slash.

< 428h/540H 120v/120V |vs +|ds 45|dc 6|lh +|ts +|brs 2|trs +|tn +|wws +| |3|3|1|1|1| T: Ishidin TC:
small wounds E: holy EC: awful EP: std P: std > 

An Ashstone holyman starts casting a spell.
An Ashstone holyman completes his spell...
An Ashstone holyman utters the words, 'xafe ay candusqarr'.
An Ashstone holyman utters a single word and disappears.

< 428h/540H 120v/120V |vs +|ds 44|dc 5|lh +|ts +|brs 1|trs +|tn +|wws +| |3|3|1|1|1| P: std > 

Pale blue light emanates from a holy avenger enshrouded in light, washing across
your hands and mending your wounds.

< 517h/540H 120v/120V |vs +|ds 42|dc 3|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|1| P: std > 

Autosaving...

< 540h/540H 120v/120V |vs +|ds 18|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|2| P: std > 

An Ashstone noble wanders about ignoring you.

< 540h/540H 120v/120V |vs +|ds 13|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|1|1|2| P: std > 
acc hah - just had ashstone holyman break train due to wording at awful ehe
You ASSOC: 'hah - just had ashstone holyman break train due to wording at awful ehe'
l

< 540h/540H 120v/120V |vs +|ds +|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|3|1|2| P: std >

A Stately Home with Flowing Woodwork
Exits: -E              [87251] 
Corpse of an Ashstone noble is lying here.
An Ashstone noble moves about the room fluidly.(Red Aura)

< 540h/540H 120v/120V |vs +|ds +|dc +|lh +|ts +|brs +|trs +|tn +|wws +| |3|3|3|1|2| P: std > 
l
A Stately Home with Flowing Woodwork
Exits: -E              [87251] 
Corpse of an Ashstone noble is lying here.
An Ashstone noble moves about the room fluidly.(Red Aura)

**Comment by Nyyrazzilyss** [comment]
9/16 dev
