### ISSUE TITLE
Who do I resize minimap window?

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#198]
How would I resize the minimap window? This is my 10" tablet (1280x800).

![minisizing](https://user-images.githubusercontent.com/28542037/45712154-93259f80-bb59-11e8-8b0f-3d24b8561427.JPG)

**Comment by Nyyrazzilyss** [comment]
function miniMap:resizeFont()
local WindowWidth, WindowHeight = getMainWindowSize()
local fontsize= maxfont(33, math.floor(.2 * WindowWidth) )

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
