### ISSUE TITLE
Extra blank lines in 7-20

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#20]
I copied/pasted a log but it takes the extra lines out. I'm getting 5 or 6 blank lines between prompts from time to time in this version (7/20). I don't remember seeing them in 6/20. Happens in and out of combat.

**Comment by CountVooku** [comment]
[URL=http://s28.photobucket.com/user/Storm4Ever/media/Blanklines_zpsi4y9xvqk.jpg.html][IMG]http://i28.photobucket.com/albums/c246/Storm4Ever/Blanklines_zpsi4y9xvqk.jpg[/IMG][/URL]

**Comment by Nyyrazzilyss** [comment]
This would be having 'condensed duplicate' turned off
