### ISSUE TITLE
@starttrain tank - blackguard skills did not automatically execute after killing a mob and staying in combat "still in combat - not leaving room"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#200]
A lithe commoner misses you with her hit. (x2)

< 297h/395H 105v/105V |vs +|sot 44|bc +|drs 18|ss 1|md 2| |3|1|1| T: Khronikazen TC: small wounds E:
lithe EC: awful EP: rcl P: std > 

Hetheta misses a lithe commoner with her slash.
Your unholy avenger starts to wail in your hands, emitting a fearsome shriek,
blasting your enemies with words of power.
A lithe commoner is stunned!
You send a lithe commoner reeling with your word of power.
You send a graceful commoner reeling with your word of power.
Your final slash sends a lithe commoner's head bouncing along the ground.
a lithe commoner is dead! R.I.P.
You receive 37,344 XP (4.15%) experience.
Your blood freezes as you hear the rattling death cry of a lithe commoner.

[Calling function: NextTrainStop()]

< 298h/395H 105v/105V |vs +|sot 43|bc +|drs 17|ss 1|md 1| |3|1|1| P: std >

You get a few coins from corpse of a lithe commoner.
There were: 1 platinum coin, 10 gold coins, 2 silver coins, 3 copper coins.

< 298h/395H 105v/105V |vs +|sot 43|bc +|drs 17|ss +|md 1| |3|1|1| P: std > 

A graceful commoner misses you with his hit. (x2)
You're hit in the solar plexus.  Wow, this is breathtaking!!

< 279h/395H 105v/105V |vs +|sot 42|bc +|drs 16|ss +|md +| |3|1|1| T: Khronikazen TC: few wounds E:
graceful EC: few scratches EP: std P: std > 
[Still in combat - not leaving room]

Your attack only grazes a graceful commoner as he dodges aside!
Your mighty slash barely wounds a graceful commoner.
Your Unholy Avenger glows with a blood red aura as it strikes
a graceful commoner a fearsome blow, rending flesh and bone. Blood rushes
up the blade, entering your body with stunning force.  Your wounds begin
to heal with the stolen lifeforce!
Your massive slash badly wounds a graceful commoner.
A graceful commoner misses you with his hit. (x2)

< 320h/395H 105v/105V |vs +|sot 41|bc +|drs 15|ss +|md +| |3|1|1| T: Khronikazen TC: small wounds E:
graceful EC: small wounds EP: std P: std >

**Comment by Nyyrazzilyss** [comment]
I would guess this would be related to the last powers attack that was used, which unfortunately you don't have captured in your log.

**Comment by Nyyrazzilyss** [comment]
Going to assume this doesn't still happen.
