### ISSUE TITLE
Blackguard - trying to sph at level 23 (level 25 skill) & trying to UF at level 26 (level 30 skill)  Also possible uncaught exception, "Pardon?"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#201]
Observations:
1. Blackguard at level 23 is using SPH when it should not, and as a result no other skills execute.
2. Blackguard at level 26 is using UF when it should not, and as a result no other skill execute.
3. "Pardon?" shouldn't stop the skills from executing that are turned on.

Workaround:
After typing @starttrain tank, if I type @set blkuf false or @set blksph false, the issue does not reproduce.

Problem statement:
What is setting blkuf / blksph to true when the level condition for the skills isn't being met?

=========================
SPH Log

< 363h/440H 105v/105V |vs 2|sot +|bc 4|drs 72|ss 3|md 4| |3|1|1| T: Khronikazen TC: small wounds E:
bugbear EC: pretty hurt EP: rcl P: std > 

[MELEE: Spirit Harrow] SPH
Pardon?

< 363h/440H 105v/105V |vs 1|sot +|bc 3|drs 71|ss 2|md 3| |3|1|1| T: Khronikazen TC: small wounds E:
bugbear EC: pretty hurt EP: rcl P: std > 

A scarred bugbear wounds you harshly with his mighty strike.
A scarred bugbear misses you with his strike.
Hetheta misses a scarred bugbear with her slash.
You miss a scarred bugbear with your slash. (x2)

< 318h/440H 105v/105V |vs 1|sot +|bc 3|drs 71|ss 2|md 3| |3|1|1| T: Khronikazen TC: few wounds E:
bugbear EC: pretty hurt EP: rcl P: std > 

You parry a scarred bugbear's lunge at you.
You dodge a scarred bugbear's vicious attack.
Hetheta misses a scarred bugbear with her slash. (x2)
You miss a scarred bugbear with your slash. (x2)

< 319h/440H 105v/105V |vs +|sot +|bc 2|drs 70|ss 1|md 1| |3|1|1| T: Khronikazen TC: few wounds E:
bugbear EC: pretty hurt EP: rcl P: std > 

You parry a scarred bugbear's lunge at you.
A scarred bugbear wounds you harshly with his awesome strike.
OUCH!  That really did HURT!
A scarred bugbear clambers to his feet.
Hetheta misses a scarred bugbear with her slash.
You miss a scarred bugbear with your slash. (x3)

< 264h/440H 105v/105V |vs +|sot +|bc 1|drs 69|ss +|md 1| |3|1|1| T: Khronikazen TC: few wounds E:
bugbear EC: pretty hurt EP: std P: std > 

< 264h/440H 105v/105V |vs +|sot +|bc 1|drs 69|ss +|md 1| |3|1|1| T: Khronikazen TC: few wounds E:
bugbear EC: pretty hurt EP: std P: std > 

< 264h/440H 105v/105V |vs +|sot +|bc 1|drs 68|ss +|md 1| |3|1|1| T: Khronikazen TC: few wounds E:
bugbear EC: pretty hurt EP: std P: std > 

You dodge a scarred bugbear's vicious attack.
A scarred bugbear brutally wounds you with his massive strike.
OUCH!  That really did HURT!
Hetheta's Unholy Avenger glows jet black, and plunges itself into
a scarred bugbear's body, causing it to writhe in pain.
A scarred bugbear seems to be blinded!
Hetheta severely wounds a scarred bugbear with her massive slash.
Hetheta's Unholy Avenger glows jet black, and plunges itself into
a scarred bugbear's body, causing it to writhe in pain.
A scarred bugbear seems to be blinded!
Hetheta severely wounds a scarred bugbear with her massive slash.
You miss a scarred bugbear with your slash. (x2)

< 203h/440H 105v/105V |vs +|sot +|bc +|drs 67|ss +|md +| |3|1|1| T: Khronikazen TC: nasty wounds E:
bugbear EC: pretty hurt EP: std P: std > 

< 203h/440H 105v/105V |vs +|sot +|bc +|drs 67|ss +|md +| |3|1|1| T: Khronikazen TC: nasty wounds E:
bugbear EC: pretty hurt EP: std P: std > 

Hetheta throws back her head and cackles with insane glee!

< 204h/440H 105v/105V |vs +|sot +|bc +|drs 67|ss +|md +| |3|1|1| T: Khronikazen TC: nasty wounds E:
bugbear EC: pretty hurt EP: std P: std > 
Hetheta throws back her head and cackles with insane glee!

< 204h/440H 105v/105V |vs +|sot +|bc +|drs 67|ss +|md +| |3|1|1| T: Khronikazen TC: nasty wounds E:
bugbear EC: pretty hurt EP: std P: std > 
att

          Character attributes for Khronikazen

Level: 23   Race: Duergar   Class: Blackguard  

=====================

At level 26, I am now seeing the same problem with Uncontrolled Fury, which is a level 30 skills.  Same outcome of skills not automatically executing after this.

                                             
< 448h/478H 105v/105V |vs 3|sot +|bc 12|drs 46|ss 1|md 4|sph +| |3|1|1| T: Khronikazen TC: few
scratches E: bugbear EC: nasty wounds EP: rcl P: std > 

[MELEE: Spirit Harrow] SPH
Your raise your weapon menacingly as it fades out, becoming smoky and grey.
You strike a crafty bugbear, cutting through flesh and armor to the animating spirit within.
A crafty bugbear is stunned!

< 448h/478H 105v/105V |vs 2|sot +|bc 11|drs 45|ss 1|md 3|sph 6| |3|1|1| T: Khronikazen TC: few
scratches E: bugbear EC: nasty wounds EP: rcl P: std > 

[Baleful Challenge has expired on Khronikazen.]

A crafty bugbear badly wounds you with his powerful strike.
Hetheta misses a crafty bugbear with her slash.
A crafty bugbear dodges your futile attack.
Your attack only grazes a crafty bugbear as he dodges aside!
Your mighty slash slightly wounds a crafty bugbear.

< 412h/478H 105v/105V |vs 2|sot +|bc 11|drs 45|ss 1|md 3|sph 6| |3|1|1| T: Khronikazen TC: small
wounds E: bugbear EC: nasty wounds EP: rcl P: std > 

[MELEE: Uncontrolled Fury] UF
Pardon?

< 413h/478H 105v/105V |vs 1|sot +|bc 10|drs 44|ss +|md 2|sph 5| |3|1|1| T: Khronikazen TC: small
wounds E: bugbear EC: nasty wounds EP: rcl P: std > 

A crafty bugbear severely wounds you with his mighty strike.
Hetheta misses a crafty bugbear with her slash.
Your attack only grazes a crafty bugbear as he dodges aside!
Your mighty slash slightly wounds a crafty bugbear.
Your massive slash badly wounds a crafty bugbear.
Your massive slash severely wounds a crafty bugbear.

< 369h/478H 105v/105V |vs 1|sot +|bc 10|drs 44|ss +|md 2|sph 5| |3|1|1| T: Khronikazen TC: small
wounds E: bugbear EC: pretty hurt EP: rcl P: std > 

A crafty bugbear's senses seem to clear again!

< 369h/478H 105v/105V |vs 1|sot +|bc 9|drs 43|ss +|md 1|sph 4| |3|1|1| T: Khronikazen TC: small
wounds E: bugbear EC: pretty hurt EP: rcl P: std > 

A crafty bugbear misses you with his strike.
A crafty bugbear clambers to his feet.
Hetheta misses a crafty bugbear with her slash.
Your massive slash badly wounds a crafty bugbear. (x2)

< 369h/478H 105v/105V |vs +|sot +|bc 9|drs 43|ss +|md 1|sph 3| |3|1|1| T: Khronikazen TC: small
wounds E: bugbear EC: pretty hurt EP: std P: std >

**Comment by Nyyrazzilyss** [comment]
While a level was being passed to check, it never looked at it :) 



function buttons:change(xchardata, xvalue, xbutton, xlevel)
	if xlevel == nil then
		xlevel=1
	end
	
	if charData:get("level") >= xlevel then
		cecho("<red>[Setting " .. xchardata .. " to " .. tostring(xvalue) .. "]\n")
		charData:set(xchardata, xvalue)
	else
		charData:set(xchardata, nil)
	end

	buttons:sync()
end
