### ISSUE TITLE
9/18/2018 dev - shaman is not praying gheal when out of gheal's

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#203]
Satac assists Walican heroically.
Satac crushes a baby red dragon's skull.  a baby red dragon instantly collapses.
a baby red dragon is dead! R.I.P.
You receive 340 XP (0.00%) experience.
Your blood freezes as you hear the rattling death cry of a baby red dragon.

< 546h/1095H 265v/265V P: std >

That person is not fighting anyone.
Rodhal gets a small pile of coins from corpse of a baby red dragon.

< 546h/1095H 265v/265V P: std >

Rrissun completes his spell...
Rrissun surrounds Rrissun in a brilliant aura of holy power.
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]
< 546h/1095H 265v/265V P: std >

That person is not fighting anyone.
[onNetworkOutput: LOOK]

< 546h/1095H 265v/265V P: std >

Pid completes his spell...
Pid summons a healing light that surround the entire group.
Your body warms as your wounds are healed.

< 658h/1095H 265v/265V P: std > 

Lilabipple enters from the north.
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]
Vatuk enters from the north.
Ordak enters from the north.
Mapnanemar enters from the north.
Jarex enters from the north.
Zaduk enters from the north.

< 659h/1095H 265v/265V P: std > 
Mapnanemar leaves south.

< 659h/1095H 265v/265V P: std > 
Walican lumbers north.
Rrissun starts casting a spell called 'Full Heal'

< 659h/1095H 265v/265V P: std > 

Mapnanemar enters from the south.
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]

< 660h/1095H 265v/265V P: std > 
< 661h/1095H 265v/265V P: std > 

Nilan group-says 'holy crap i was dead instantly what was that....'

< 661h/1095H 265v/265V P: std > 

Rrissun's wounds continue to bleed uncontrollably!
Rrissun completes his spell...
Rrissun summons a holy light to surround Rrissun and close his wounds.
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]

< 662h/1095H 265v/265V P: std > 
Togrendlsnapt skulks in from the north.

< 662h/1095H 265v/265V P: std > 
Walican lumbers in from the north.
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]

< 662h/1095H 265v/265V P: std > 

Rrissun starts casting a spell called 'Full Heal'

< 663h/1095H 265v/265V P: std > 

Lilabipple group-says 'go kill consort if you're healthy'

< 664h/1095H 265v/265V P: std > 
prep
[onNetworkOutput: prep]
You continue your praying.
Lilabipple manages to stop the flow of blood in Rrissun.

**Comment by Nyyrazzilyss** [comment]
Various updates have been made since this bug was posted somewhat related to it. It might even be fixed! Repost if still occuring with current dev (12/16 at this time)
