### ISSUE TITLE
Trying to pray while fighting

### ISSUE THREAD

**Issue by Jado4444** [Nyyrazzilyss/NyyLIB#208]
The Bloodied Foyer of an Abandoned Temple
Exits: - North - East  - South# - West 
A fine longsword has been tossed on the ground here.
A suit of studded leather lies here abandoned.
A pile of skulls has been carefully placed here, warding off intruders
A grimy orc stands here, fighting YOU!
An orc guard stands here bored and half asleep.

< 83h/83H 120v/120V P: std > 
[Spellqueue cleared.]
Resting now will most likely lead to your final rest!

< 83h/83H 120v/120V P: std >

You have memorized the following spells:
[Spellqueue cleared.]
( 2nd circle)  1 - Sticks To Snakes
( 1st circle)  5 - Shillelagh

And you are currently praying for the following spells:
   11 seconds:  ( 1st) Shillelagh

You can pray for no more spells.

< 83h/83H 120v/120V P: std >

Resting now will most likely lead to your final rest!
[Spellqueue cleared.]

< 83h/83H 120v/120V P: std >

A grimy orc misses you with his punch.
[Spellqueue cleared.]
You have memorized the following spells:
( 2nd circle)  1 - Sticks To Snakes
( 1st circle)  5 - Shillelagh

And you are currently praying for the following spells:
   11 seconds:  ( 1st) Shillelagh

You can pray for no more spells.

< 83h/83H 120v/120V T: Ilonwyn TC: excellent E: grimy EC: pretty hurt EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 83h/83H 120v/120V T: Ilonwyn TC: excellent E: grimy EC: pretty hurt EP: std P: std >

You have memorized the following spells:
( 2nd circle)  1 - Sticks To Snakes
( 1st circle)  5 - Shillelagh

And you are currently praying for the following spells:
   11 seconds:  ( 1st) Shillelagh

You can pray for no more spells.

< 83h/83H 120v/120V T: Ilonwyn TC: excellent E: grimy EC: pretty hurt EP: std P: std >

Sorry, you aren't allowed to do that in combat.

< 83h/83H 120v/120V T: Ilonwyn TC: excellent E: grimy EC: pretty hurt EP: std P: std >

You have memorized the following spells:
( 2nd circle)  1 - Sticks To Snakes
( 1st circle)  5 - Shillelagh

And you are currently praying for the following spells:
   11 seconds:  ( 1st) Shillelagh

You can pray for no more spells.

< 83h/83H 120v/120V T: Ilonwyn TC: excellent E: grimy EC: pretty hurt EP: std P: std > 

A grimy orc is nearly slain by the force of your average bludgeon!
A grimy orc is mortally wounded, and will die soon, if not aided.

**Comment by Nyyrazzilyss** [comment]
This should not be happening, but would need to see what was happening before the bug started occuring (i.e. while it was working properly) + when the bug occurs.

Ideally, echosend should be enabled also (@set condensed echosend)

**Comment by Jado4444** [comment]
I found something else you might find interesting:
You have finished praying for Call Lightning.
[addbutton: nil xid : non-existant button: call_lightning]
Your prayers are complete.


I don't know what it means but it looks like an error message of some sort

**Comment by Nyyrazzilyss** [comment]
Call lightning was fixed at some time in the past and ticket never closed. Assuming the other bug listed does not occur with current versions
