### ISSUE TITLE
Weird mudlet behavior after reading berserker gauntlets apprentice note

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#221]
Wayward House Inn (Shadowed)
Exits: -N -U           [48603] 
A gaping hole in the ground leads into darkness.
Corpse of a dapper noble is lying here.
Corpse of an opulent merchant is lying here.
Corpse of a dapper noble is lying here.
Corpse of an opulent merchant is lying here.
Corpse of a dapper noble is lying here.
Corpse of an opulent merchant is lying here.
Corpse of a dapper noble is lying here.
A ghostly spellbook lies here.
A simple wooden box sits here.
A wooden club lies here.
An adamantium key lies here.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A showy merchant sits here looking smug.
A dapper noble is here socializing.
A dapper noble is here socializing.
Tonga  (RP) (Ogre) stands here.
Mapnanemar  (Moon Elf) stands here.
Lolilela  (AFK) (Moon Elf) stands here.
Nyyrazzilyss - Head Jailer of the Valkurian Blades (Illithid) sits resting in mid-air.
Ynndchiarhlizz - The Nexus (Illithid) sits resting.
Havorr Merendil stands behind the counter ready to serve.

< 432h/525H 118v/125V |0|1|1|1|1| P: std > 
exam note
Scrawled in messy script is the following message.

The bearer of this note is the owner of four magical items in my
chest. Please disassemble these items as follows:

githyanki gauntlets         - Use the these gauntlets as the basic
                              form.

gloves of tanar'ri skin     - Use the skin from these gloves to
                              line the inside of the gauntlets.

gauntlets of troll strength - Remove the fingernails from these
                              magical gloves. Attach them to the
                              inside of the new pair of gauntlets
                              behind the wrists so that they will
                              pierce the wearer when in battle.

solid adamantite bar         - Melt this bar down and use it to 
                              augment the outside of the gantlets. 
                              Form the metal into sharp spikes and 
                     meld them to the fists.

l           [48603] 

l           [48603] 

l           [48603] 

l           [48603] 

i

eq

sc

Have to restart mudlet whenever i read the note -

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
