### ISSUE TITLE
Minimap doesn't fill the frame  

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#222]
<img width="1273" alt="screen shot 2018-12-15 at 10 29 51 am" src="https://user-images.githubusercontent.com/29266187/50044646-79aacb80-0054-11e9-9d5c-ad5d6a1cee1d.png">

**Comment by Nyyrazzilyss** [comment]
function miniMap:resizeFont()
	local WindowWidth, WindowHeight = getMainWindowSize()
	local fontsize= maxfont(33, math.floor(.2 * WindowWidth) )

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
