### ISSUE TITLE
Bard/Battlechanter should auto-sing and HBL after being resurrected

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#223]
Battlechanter just was resurrected, but did not automatically sing or cast HBL once I was alive.

My previous song I was singing was heal, and I had auto-bless enabled for HBL.  Before I had died I was stunned.

Log:
                                                
< 614h/1287H 300p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std > 

< 614h/1287H 300p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std >

Vesad completes his spell...
A holy light radiates from Vesad as his wounds begin to mend.

< 614h/1287H 301p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std > 
A draconian warrior completes its spell...
A draconian warrior utters the words, 'hpjioculofbragh'.
A massive thunder clap originating from a draconian warrior rocks the surroundings!
Pidibeple is stunned!
The spell cast by a draconian warrior is partially absorbed!
You shudder in agony as a draconian warrior's thunderblast jolts you!
OUCH!  That really did HURT![onNetworkOutput: GROUP]
[onNetworkOutput: FOLLOWERS]
With no one to accompany you, your song ends!
You stop your song.
The world starts spinning, and your ears are ringing!
[Spellqueue cleared.]
[onNetworkOutput: STATUS]
Vesad is stunned!
Namassa is stunned!
Jani is stunned!
Lilabipple attempts to flee.
Lilabipple flies east.

< 521h/1287H 301p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std > 

[Namassa : the mystical circlet of the coiled serpent]
Namassa slightly wounds a draconian warrior with her massive pierce.
Namassa's attack only grazes a draconian warrior as it dodges aside!
Namassa barely wounds a draconian warrior with her powerful pierce.
Namassa badly wounds a draconian warrior with her massive pierce. (x3)
Pidibeple stops invoking abruptly!

< 521h/1287H 301p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std >

Jani stops invoking abruptly!

< 521h/1287H 301p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std > 
A draconian warrior misses Vesad with its pierce. (x3)
Jani misses a skeletal dragon with her hit.
You miss a skeletal dragon with your pierce.
Pidibeple misses a skeletal dragon with his flaming bludgeon.
Drogbezran barely wounds a skeletal dragon with her massive slash.
Drogbezran barely wounds a skeletal dragon with her mighty slash.
Drogbezran barely wounds a skeletal dragon with her massive slash.
A draconian assassin misses Vesad with its pierce. (x4)
A draconian warrior misses Vesad with its pierce. (x3)
A skeletal dragon misses Vesad with its claw. (x2)
A skeletal dragon rears back and buffets its wings violently!
You are slammed by the powerful blast of air!
YIKES!  Another hit like that, and you've had it!!
You are knocked down on the ground![onNetworkOutput: ST]
Jani slumps to the ground.
Jani quickly falls silent as a skeletal dragon impales her on a razor-sharp wing talon!
Jani is dead! R.I.P.
Jani slumps to the ground.
Your blood freezes as you hear the rattling death cry of Jani.
Jani has died![onNetworkOutput: GROUP]
[onNetworkOutput: FOLLOWERS]
Azora misses a skeletal dragon with her pierce.
Azora barely wounds a skeletal dragon with her massive pierce. (x2)
Azora barely wounds a skeletal dragon with her mighty pierce.
Azora barely wounds a skeletal dragon with her massive pierce. (x2)
A draconian warrior parries Vesad's lunge at it.
Vesad slightly wounds a draconian warrior with his mighty bludgeon.
Namassa severely wounds a draconian warrior with her massive pierce.
Namassa badly wounds a draconian warrior with her massive pierce. (x2)
A draconian warrior partially deflects Namassa's lunge at it.
Namassa slightly wounds a draconian warrior with her powerful pierce.
Namassa severely wounds a draconian warrior with her massive pierce.

< 198h/1287H 301p/549P 160v/160V T: Vesad TC: nasty wounds E: massive EC: few wounds EP: std P: rcl
> 
Drogbezran group-says 'scale'
[Dragonscales has expired on Drogbezran.]

< 198h/1287H 301p/549P 160v/160V T: Vesad TC: nasty wounds E: massive EC: few wounds EP: std P: rcl
> 
One of the draconian warriors spots something moving in the distance!
A draconian warrior completes its spell...
A draconian warrior utters the words, 'stoneskin'.
A draconian warrior's skin seems to turn to stone.

< 198h/1287H 301p/549P 160v/160V T: Vesad TC: nasty wounds E: massive EC: few wounds EP: std P: rcl
> 
Lilabipple group-says 'regroup'
Vesad group-says 'amber potion is just armor/bless, pretty much all the same'

< 198h/1287H 301p/549P 160v/160V T: Vesad TC: nasty wounds E: massive EC: few wounds EP: std P: rcl
> 
Lilabipple group-says 'regroup'

< 198h/1287H 301p/549P 160v/160V T: Vesad TC: nasty wounds E: massive EC: few wounds EP: std P: rcl
> 
A draconian warrior completes its spell...
A draconian warrior utters the words, 'uiqzieuabral qraje'.
Billowing clouds of incendiary gases pour from a draconian warrior's fingertips!
You partially evade the spell!
The spell cast by a draconian warrior is partially absorbed!
You are enveloped in a cloud of incendiary gasses sent by a draconian warrior!
OUCH!  That really did HURT!
Namassa slumps to the ground.
The incendiary cloud from a draconian warrior turns Namassa into a charred corpse
Namassa is dead! R.I.P.
Namassa slumps to the ground.
Your blood freezes as you hear the rattling death cry of Namassa.
Namassa has died!

< 119h/1287H 301p/549P 160v/160V T: Vesad TC: pretty hurt E: massive EC: few wounds EP: std P: rcl >
A draconian warrior heroically rescues a draconian warrior.

< 119h/1287H 301p/549P 160v/160V T: Vesad TC: pretty hurt E: massive EC: few wounds EP: std P: rcl >
Drogbezran starts casting a spell called 'Shroud of Shadow'

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: pretty hurt E: massive EC: few wounds EP: std P: rcl >

[Drogbezran : the mystical circlet of the coiled serpent]
Drogbezran barely wounds a skeletal dragon with her massive slash.
Drogbezran barely wounds a skeletal dragon with her awesome slash.
Drogbezran barely wounds a skeletal dragon with her massive slash. (x2)

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: pretty hurt E: massive EC: few wounds EP: std P: rcl >
Drogbezran completes her spell...
A misty cloud of gloom swirls about Drogbezran.

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: pretty hurt E: massive EC: few wounds EP: std P: rcl >
Vesad lays his blessed hands upon Vesad.
Vesad glows with a holy light as his wounds begin to close.

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl > 

Lilabipple group-says 'all out'

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl > 
Azora's face finally loses its magical intensity, her body visibly relaxing as the mystical rage
departs.
A draconian warrior deflects Vesad's blow, and strikes back at Vesad!
A draconian warrior misses Vesad with its pierce.
Vesad misses a draconian warrior with his bludgeon.
A draconian warrior misses Vesad with its pierce. (x3)
Your strong pierce barely wounds a skeletal dragon.
The globe around your body flares as it bears the brunt of a skeletal dragon's assault!
You miss a skeletal dragon with your pierce.
Pidibeple misses a skeletal dragon with his flaming bludgeon.
Drogbezran's Unholy Avenger glows jet black, and plunges itself into
a skeletal dragon's body, causing it to writhe in pain.
Drogbezran barely wounds a skeletal dragon with her massive slash. (x2)
A draconian assassin misses Vesad with its pierce. (x4)
A draconian warrior misses Vesad with its pierce. (x3)
A draconian warrior starts casting an offensive spell.
A skeletal dragon misses Vesad with its claw. (x2)
A skeletal dragon flings its mighty tail into Pidibeple with tremendous force!
Azora barely wounds a skeletal dragon with her massive pierce.
Azora barely wounds a skeletal dragon with her powerful pierce.
Azora barely wounds a skeletal dragon with her massive pierce.
Drogbezran dodges a draconian warrior's attack.
A draconian warrior misses Drogbezran with its pierce. (x2)
You stagger about, then fall sprawling![onNetworkOutput: ST]

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl > 

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl >

A draconian warrior starts casting a spell called 'invisibility'.

< 119h/1287H 302p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl >

You stagger about, then fall sprawling![onNetworkOutput: ST]

< 119h/1287H 303p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: rcl >

A draconian warrior completes its spell...
A draconian warrior utters the words, 'uiqzieuabral qraje'.
Billowing clouds of incendiary gases pour from a draconian warrior's fingertips!
Pidibeple is incapacitated and will slowly die, if not aided.
You partially evade the spell!
The spell cast by a draconian warrior is partially absorbed!
You are enveloped in a cloud of incendiary gasses sent by a draconian warrior!
YIKES!  Another hit like that, and you've had it!!
You wish that your wounds would stop BLEEDING so much!

A cloud of buring gasses from a draconian warrior misses Drogbezran!
You manage to unsteadily get to your feet.

< 38h/1287H 303p/549P 160v/160V T: Vesad TC: few wounds E: massive EC: few wounds EP: std P: std > 

Vesad attempts to flee.
Vesad flies east.

< 38h/1287H 303p/549P 160v/160V E: massive EC: few wounds EP: std P: std > 
Lilabipple enters from the east.[onNetworkOutput: GROUP]
[onNetworkOutput: FOLLOWERS]
Azora scrambles madly to her feet!

< 38h/1287H 303p/549P 160v/160V E: massive EC: few wounds EP: std P: std >

Lilabipple tries to drag corpse of Jani out of the room.
Lilabipple leaves east.

                         112/112  move     -4/810   hit - Pidibeple

< 38h/1287H 303p/549P 160v/160V E: massive EC: few wounds EP: std P: std > 
Drogbezran raises her weapon menacingly as it fades out, becoming smoky and grey.
Drogbezran strikes a skeletal dragon, cutting through flesh and armor to the animating spirit within
.
Drogbezran strikes a draconian assassin, cutting through flesh and armor to the animating spirit
within.
A draconian assassin is stunned!
Drogbezran strikes a draconian warrior, cutting through flesh and armor to the animating spirit
within.
A draconian warrior is stunned!
Drogbezran strikes a draconian warrior, cutting through flesh and armor to the animating spirit
within.
A draconian warrior is stunned!
Drogbezran strikes a draconian warrior, cutting through flesh and armor to the animating spirit
within.
A draconian warrior is stunned!
a draconian warrior strikes out wildly about the area in a mighty burst of power!
A draconian warrior misses Drogbezran with its pierce.

[Stun has expired on Tronik.]
< 38h/1287H 303p/549P 160v/160V T: Drogbezran TC: few wounds E: massive EC: few wounds EP: std P:
std > 
The world stops spinning.[onNetworkOutput: sing 'song of healing']
A draconian warrior stops chanting abruptly!
Azora attempts to escape.
Azora flies east.

< 38h/1287H 303p/549P 160v/160V T: Drogbezran TC: few wounds E: massive EC: few wounds EP: std P:
std >

Kayos group-says 'blind'
You begin singing.

< 38h/1287H 303p/549P 160v/160V T: Drogbezran TC: few wounds E: massive EC: few wounds EP: std P:
std > 
A draconian warrior starts casting a spell.
A draconian warrior stops chanting abruptly!

< 38h/1287H 303p/549P 160v/160V T: Drogbezran TC: few wounds E: massive EC: few wounds EP: std P:
std > 
Namassa group-says 'Wow, lag sucks.'

[Healing Aura has expired on Drogbezran.]
< 38h/1287H 303p/549P 160v/160V T: Drogbezran TC: few wounds E: massive EC: few wounds EP: std P:
std > 
Drogbezran parries a draconian warrior's lunge at her.
A draconian warrior misses Drogbezran with its pierce. (x5)
A skeletal dragon misses Drogbezran with its claw. (x2)
A skeletal dragon breathes a cone of frost!
Pidibeple is frozen into a solid block of ice by the deadly frost!
Pidibeple is dead! R.I.P.
Your blood freezes as you hear the rattling death cry of Pidibeple.
Pidibeple has died!
You partially evade the breath!
You are frozen into a solid block of ice by the deadly frost!
With a final blow, you feel yourself falling to the ground.
Your soul leaves your body in the cold sleep of death...
With no one to accompany you, your song ends!
You stop your song.
               

You are dead!

Your soul is transported to The Fugue Plane as your crumbling body succumbs85308

[Currently moving. Spellcasting is temporarily paused.]

[Clearing memorized spells]

[Spellqueue cleared.]
[onNetworkOutput: GROUP]
[onNetworkOutput: FOLLOWERS]
to the cold sleep of death. Here in Kelemvor's realm all dead souls await
either judgement or escape from this timeless prison.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.
Pidibeple  (Gnome) stands here.
Namassa  (Yuan-Ti) stands here.(Red Aura)
Jani  (Human) stands here.
Edgaz  (AFK) (Drow Elf) stands here.(Red Aura)

From here you may either re-enter the game by typing enter portal, or wait
to be resurrected by another player. Type help death for more information.

< 211h/847H 137p/549P 40v/160V P: std > 

[Bless has expired on Muzovaple.]
< 211h/947H 137p/549P 40v/160V P: std > 
l
[onNetworkOutput: L]
The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.
Pidibeple  (Gnome) stands here.
Namassa  (Yuan-Ti) stands here.(Red Aura)
Jani  (Human) stands here.
Edgaz  (AFK) (Drow Elf) stands here.(Red Aura)

< 211h/947H 137p/549P 40v/160V P: std > 
gsay bleg
[onNetworkOutput: GSAY bleg]
You group-say 'bleg'

< 211h/947H 138p/549P 40v/160V P: std > 

Lilabipple group-says 'consent me for drag'

< 211h/947H 138p/549P 40v/160V P: std > 
consent Lilabipple
[onNetworkOutput: consent Lilabipple]
You were already consenting to Lilabipple.

< 211h/947H 138p/549P 40v/160V P: std > 

[Greenfire has expired on Kayos.]

[Globe of Invulnerability has expired on Drogbezran.]

[Blur has expired on Lilabipple.]

Lilabipple group-says 'all dragged'

< 211h/947H 137p/549P 40v/160V P: std > 

[Globe of Invulnerability has expired on Azora.]

Lilabipple group-says 'consent Muzovaple'

< 211h/947H 137p/549P 40v/160V P: std > 

Jani sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
consent Muzovaple
[onNetworkOutput: consent Muzovaple]
You no longer consent to Lilabipple.
You give your consent to Muzovaple.[onNetworkOutput: T Muzovaple Muzovaple now has consent.]

< 211h/947H 137p/549P 40v/160V P: std >

You tell Muzovaple 'Muzovaple now has consent.'

< 211h/947H 137p/549P 40v/160V P: std > 

[Globe of Invulnerability has expired on Nilan.]

Drogbezran group-says 'nice'

< 211h/947H 137p/549P 40v/160V P: std > 

Jani sits down in a comfortable spot.

< 211h/847H 137p/549P 40v/160V P: std > 

Muzovaple group-says 'im feebled'

< 211h/947H 137p/549P 40v/160V P: std > 
Jani opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

[Dragonscales has expired on Vesad.]
Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

[No longer moving. Spellcasting has resumed]

< 211h/947H 137p/549P 40v/160V P: std > 

Lilabipple group-says 'i can't imagine how many would have died if i had said die instead of don't
die'
Vesad group-says '[[ SCALE OUT ]]'
[Dragonscales has expired on Vesad.]

< 211h/947H 137p/549P 40v/160V P: std > 

Drogbezran group-says 'globe'

< 211h/947H 137p/549P 40v/160V P: std > 

[Globe of Invulnerability has expired on Vesad.]

Pidibeple, looking very frustrated, packs up his book.
Jani, looking very frustrated, packs up her book.

< 211h/847H 137p/549P 40v/160V P: std > 
Kayos group-says 'someone plz tell me Nilan died'
Drogbezran group-says 'its good that this place can still make a few corpses'

< 211h/947H 137p/549P 40v/160V P: std > 
Vesad group-says '[[ GLOBE OUT ]]'
[Globe of Invulnerability has expired on Vesad.]

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Azora group-says 'Globe of Invulnerability Out!!'
[Globe of Invulnerability has expired on Azora.]

< 211h/947H 137p/549P 40v/160V P: std > 

[Globe of Invulnerability has expired on Kayos.]

Muzovaple group-says '-=Blur ouT=-'

< 211h/947H 137p/549P 40v/160V P: std > 
Muzovaple group-says '-=Blur ouT=-'

< 211h/947H 137p/549P 40v/160V P: std > 
Kayos group-says 'Kayos Globe has Expired!'
[Globe of Invulnerability has expired on Kayos.]
Muzovaple group-says '-=Vit ouT=-'
[Vitality has expired on Muzovaple.]

< 211h/947H 137p/549P 40v/160V P: std > 

Nilan group-says 'nope'

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Nilan group-says '[[ GLOBE OUT ]]'
[Globe of Invulnerability has expired on Nilan.]

< 211h/947H 137p/549P 40v/160V P: std > 

Nilan group-says 'did you die kayos'

< 211h/947H 137p/549P 40v/160V P: std > 
l
[onNetworkOutput: L]
The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.
Pidibeple  (Gnome) sits resting.
Namassa  (Yuan-Ti) stands here.(Red Aura)
Jani  (Human) stands here.
Edgaz  (AFK) (Drow Elf) stands here.(Red Aura)

hbl
[onNetworkOutput: hbl]
< 211h/947H 137p/549P 40v/160V P: std > 
You can't do that on the Fugue Plane.

< 211h/947H 137p/549P 40v/160V P: std > 

Muzovaple group-says 'need band'

< 211h/947H 137p/549P 40v/160V P: std > 

Kayos group-says 'naw just blind'

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Vesad group-says 'you weren't supposed to die tronik, I need my house music soundtrack'

< 211h/947H 137p/549P 40v/160V P: std > 

[Detect Invisibility has expired on Azora.]

Azora group-says 'Detect Invis faded.'

< 211h/947H 137p/549P 40v/160V P: std > 

[Vitality has expired on Azora.]

Lilabipple group-says 'so we need to discuss the details of plan A'
Azora group-says 'Vitality has faded!!'
[Vitality has expired on Azora.]

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Drogbezran group-says 'lol'

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 
gsay droppin' dem beats!
[onNetworkOutput: GSAY droppin' dem beats!]
You group-say 'droppin' dem beats!'

< 211h/947H 137p/549P 40v/160V P: std > 

Lilabipple group-says 'it was throw nilan in front of the dragon'

< 211h/947H 137p/549P 40v/160V P: std > 

[Blind has expired on Kayos.]

[Blind has expired on Vesad.]

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 
l
[onNetworkOutput: L]
Lilabipple group-says 'what happened people?!'
The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.
Pidibeple  (Gnome) stands here.
Namassa  (Yuan-Ti) stands here.(Red Aura)
Jani  (Human) stands here.
Edgaz  (AFK) (Drow Elf) stands here.(Red Aura)

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Nilan group-says 'plan a is working fine'

< 211h/947H 137p/549P 40v/160V P: std > 
l
[onNetworkOutput: L]
The Top of the Crystal Spire on the Fugue Plane
Exits: None!           [93848] 
A wispy smoke colored portal hovers just above the center of the room.
Pidibeple  (Gnome) sits resting.
Namassa  (Yuan-Ti) stands here.(Red Aura)
Jani  (Human) stands here.
Edgaz  (AFK) (Drow Elf) stands here.(Red Aura)

< 211h/947H 137p/549P 40v/160V P: std > 

Nilan group-says 'lets do it again'

< 211h/947H 137p/549P 40v/160V P: std > 

Drogbezran group-says 'cant believe nilan survived that!'

< 211h/947H 137p/549P 40v/160V P: std > 

Vesad group-says 'it's like the club scene from tron'

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 
t Muzovaple res on?
[onNetworkOutput: T Muzovaple res on?]
You tell Muzovaple 'res on?'

< 211h/947H 137p/549P 40v/160V P: std > 

Muzovaple group-says '[TIMESTOP UP]'

< 211h/947H 137p/549P 40v/160V P: std > 

Jani departs this plane in a brilliant white flash of light.

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

Pidibeple, looking very frustrated, packs up his book.

< 211h/847H 137p/549P 40v/160V P: std > 

Pidibeple sits down in a comfortable spot.

< 211h/947H 137p/549P 40v/160V P: std > 
Pidibeple opens an ancient tome and begins studying it intently.

< 211h/947H 137p/549P 40v/160V P: std > 

[Blur has expired on Drogbezran.]

Pidibeple departs this plane in a brilliant white flash of light.

< 211h/947H 137p/549P 40v/160V P: std > 

Autosaving...

< 211h/847H 137p/549P 40v/160V P: std > 

You feel a Presence touch you, its divine hand cupping itself
around your soul and drawing it forth from your current body. For
one brief instant, you witness the enormity of the universe before
your soul is gently deposited into your previous body, at the feet of Muzovaple.

               

An Intersection of Fire (On Fire!)
Exits: -N -E -S -W     [93848] 
Corpse of 'Shadow', the blade of Vhaeraun's chosen assassin is lying here.
Corpse of a draconian assassin is lying here.
Corpse of Namassa is lying here.
[3] Corpse of a shady orc is lying here.
Corpse of 'Shadow', the blade of Vhaeraun's chosen assassin is lying here.
[2] Corpse of a shady orc is lying here.
[2] Corpse of a fire bat is lying here.
Pidibeple  (Gnome) sits resting.
Jani  (Human) sits resting.
Muzovaple  (Gnome) stands in mid-air here.(Gold Aura)
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]
Lilabipple  (Gnome) stands here.
Drogbezran  (Duergar) hovers in mid-air here.(Red Aura)
Azora  (Human) stands in mid-air here.(Red Aura)
Vesad  (Half-Orc) stands in mid-air here.(Gold Aura)
Nilan  (RP) (Drow Elf) stands in mid-air here.(Red Aura)
Kayos  (RP) (Moon Elf) stands in mid-air here.(Gold Aura)

< 423h/847H 274p/549P 80v/160V P: std > 

[Searching... Match found: Calimport Palace Vault : An Intersection of Fire : 86687]

[Currently moving. Spellcasting is temporarily paused.]

Drogbezran group-says 'blur'

< 424h/847H 274p/549P 81v/160V P: std > 

Muzovaple takes out his holy symbol and begins praying intently.

< 424h/847H 275p/549P 81v/160V P: std > 

Drogbezran group-says 'DJ Tronik back to lyfe'

< 426h/847H 276p/549P 83v/160V P: std > 

Vesad group-says '[[ BLUR OUT ]]'

< 426h/847H 276p/549P 83v/160V P: std > 

Pidibeple stops using a crimson cloak of flaming meteors.

< 426h/847H 276p/549P 84v/160V P: std > 

[Bless has expired on Vesad.]

Pidibeple wears a mantle of swirling shadows about his body.

< 427h/847H 277p/549P 85v/160V P: std > 

Nilan says 'hah is that what it said azora when i tried trip that assassin'

< 429h/847H 278p/549P 87v/160V P: std > 
Muzovaple clambers to his feet.
Muzovaple, looking very frustrated, packs up his holy symbol.

< 429h/847H 278p/549P 87v/160V P: std > 

Vesad does a Snoopy-Like dance of joy!!
Muzovaple starts casting a spell called 'Resurrect'

< 430h/847H 279p/549P 87v/160V P: std > 

[onNetworkOutput: play]

[onNetworkOutput: sing 'song of healing']
Muzovaple completes his spell...
Muzovaple completes his chant, and stares rapturously into space.
his body seems to shimmer as a great Power enters the room, and
a divine radiance engulfs the body at Muzovaple's feet. After a
brief moment, the body twitches and convulses, before the eyes snap
open and Namassa takes a deep breath. The radiance dissipates, leaving
[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]
Muzovaple standing disoriented and exhausted.

< 430h/847H 279p/549P 87v/160V P: std >

Sing and play what song?

< 430h/847H 279p/549P 88v/160V P: std >

Drogbezran group-says 'thats the name of his 2nd albumb'

**Comment by Nyyrazzilyss** [comment]
12/7/19 012dev
