### ISSUE TITLE
autotank isn't automatically entering portals on leader gsay "tanks enter portal"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#225]
My autotank is on
My auto-enter special exits is on
I properly go a direction when leader gsay "tanks s", but am not entering any portals.
Zone: IXP
@version: Script version: 12/22/2018 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

                                     
Nilan sneaks east.
You follow Lilabipple east.

A Curving Prison Hallway
Exits: -S -W           [84049] 
A buckler composed of deepstone is here.
Corpse of a highborn drow justicar is lying here.
Corpse of a drow sentry is lying here.
[2] Corpse of a drow sentry is shimmering here.
[2] Corpse of a drow sentry is lying here.
Corpse of a drow sentry is shimmering here.
Corpse of 'Shadow', the blade of Vhaeraun's chosen assassin is lying here.
Corpse of a drow sentry is lying here.
An ocular portal is here.
Nilan  (RP) (Drow Elf) stands here.(Red Aura)
Erivar  (RP) (Human) stands here.
The spectre of a tzakandi guard stands here.(Red Aura)
The ghost of a drow sentry stands here.(Red Aura)
Tashareree  (Drow Elf) stands here.(Red Aura)
Vomicopol  (Gnome) stands here.
Jooku  (Barbarian) stands in mid-air here.
Darwellyn  (RP) (Human) stands here.
Kayos  (RP) (Moon Elf) stands here.
Lilabipple  (Gnome) stands in mid-air here.
Afu flies in from the west.
Pidibeple enters from the west.

< 1311h/1272H 116v/120V |bs +|ds +|dc +|lh +|rc +|ss +|es +|tn +|ws +| |3|3|3|3|0| P: std > 

Lilabipple group-says 'tanks enter portal'

< 1310h/1272H 118v/120V |bs +|ds +|dc +|lh +|rc +|ss +|es +|tn +|ws +| |3|3|3|3|0| P: std > 

Nilan group-says '[[ VIT OUT ]]'
[Vitality has expired on Nilan.]

< 1310h/1272H 119v/120V |bs +|ds +|dc +|lh +|rc +|ss +|es +|tn +|ws +| |3|3|3|3|0| P: std > 

Nilan sneers in contempt of Azora.

< 1310h/1272H 120v/120V |bs +|ds +|dc +|lh +|rc +|ss +|es +|tn +|ws +| |3|3|3|3|1| P: std > 

A harmonious combination of notes from Erivar soothes your wounds.[onNetworkOutput: GROUP]

[onNetworkOutput: FOLLOWERS]
an ocular portal suddenly glows brightly!
Afu slowly fades out of existence.

< 1310h/1272H 120v/120V |bs +|ds +|dc +|lh +|rc +|ss +|es +|tn +|ws +| |3|3|3|3|1| P: std > 
enter portal
[onNetworkOutput: ENTER portal]
Lilabipple group-says 'all in'
               

A Stairway Tunnel Spirals Downward
Exits: -S -D

**Comment by Nyyrazzilyss** [comment]
The if statement was only matching 'en', didn't match 'enter'. Changed.

if matches[4] == "en" or matches[4] == "enter" then

**Comment by Nyyrazzilyss** [comment]
012dev
