### ISSUE TITLE
hiding without saving vs. hiding with saving (using autohide)

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#23]
An Elegant Home
Exits: -S              [48605] 
A lithe commoner wanders about gracefully.
A graceful commoner stands here proudly.

< 568h/568H 168v/170V P: std > 
flee
Ghostwalk
Exits: -N -E -S -W     [48605] 
A black-capped chickadee chases insects here.
You flee southward!
hide

< 568h/568H 168v/170V P: std >

You attempt to hide yourself.

< 568h/568H 168v/170V P: std > 
status

Status of Nonog
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
farsee                    haste                     hide                      
infravision               no summon                 sense life                

< 568h/568H 170v/170V P: std > 

< 568h/568H 170v/170V P: std > 

A black-capped chickadee flutters west.

w
< 568h/568H 170v/170V P: std > 
Ghostwalk
Exits: -N -E -S -W     [48606]  [Hidden]
A black-capped chickadee chases insects here.
An austere commoner struts about.

< 568h/568H 169v/170V P: std > 
hop
You hop around on one foot.

< 568h/568H 170v/170V P: std > 
flee
Ghostwalk
Exits: -N -E -S -W     [48606]  [Hidden]
You flee eastward!
hide

< 568h/568H 169v/170V P: std > 
You attempt to hide yourself.

save
< 568h/568H 169v/170V P: std > 

The sun vanishes below the western horizon.

< 568h/568H 169v/170V P: std > 
status
w

Status of Nonog
---------------------------------------------------------------------------

Effects
---------------------------------------------------------------------------
farsee                    haste                     hide                      
infravision               no summon                 sense life                

< 568h/568H 170v/170V P: std > 
Saving...

< 568h/568H 170v/170V P: std > 
< 568h/568H 170v/170V P: std >

Ghostwalk
Exits: -N -E -S -W     [48606]  [Hidden]
A black-capped chickadee chases insects here.
An austere commoner struts about.

hop

< 568h/568H 169v/170V P: std >

You stop trying to hide.
You hop around on one foot.

< 568h/568H 169v/170V P: std >

**Comment by Nyyrazzilyss** [comment]
Corrected 7/29 dev
