### ISSUE TITLE
Spellcast: vt

### ISSUE THREAD

**Issue by CountVooku** [Nyyrazzilyss/NyyLIB#235]
Still happens a lot. Here is a log where it sends GROUP but doesn't after it. I kept casting group-heal when everyone was healed.
[GroupNotSending2.txt](https://github.com/Nyyrazzilyss/NyyLIB/files/2825081/GroupNotSending2.txt)

**Comment by Nyyrazzilyss** [comment]
vt
[onNetworkOutput: vt]
< 919h/919H 127v/127V T: Edgad TC: excellent E: faerie EC: awful EP: knl P: std >

Gilal's mighty shot decapitates a patrolling faerie scout with its concussive impact!
[SPELL: Group Heal] gh
gh

[onNetworkOutput: gh]
a patrolling faerie scout is dead! R.I.P.
You receive 23,635 XP (0.07%) experience.
Your blood freezes as you hear the rattling death cry of a patrolling faerie scout.
A well armed faerie stops following a patrolling faerie scout. (x2)
Pidibeple starts casting an offensive spell called 'Inferno'
You start chanting... [Casting: GH (Group Heal)]

**Comment by Nyyrazzilyss** [comment]
012dev
