### ISSUE TITLE
Bug in Rogue Assist script "singleSendScript"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#237]
I have version of the script from 1/3/2019.

Problem: My new rogue had not been autoassisting in groups from level 20 to 34.  Autoassist was toggled on/off multiple times.

Looking at the script "singleSendScript" I found a typo, the code was:

	if checkMask("rog") then
		local enemytarget = v9getEnemy()

I removed the "v9" from getEnemy() and autoassist then started working successfully.  Working code:

	if checkMask("rog") then
		local enemytarget = getEnemy()

Note: I don't think I introduced this locally but uh, maybe I did :)  Sharing in case it's in the root library and hasn't been fixed already.

**Comment by Nyyrazzilyss** [comment]
Thanks, not sure if that was a bug present in 1/3 that i'd previously fixed or a typo you'd made yourself. Just checked 1/27, and it's definitely not present there.
