### ISSUE TITLE
problem with Warrior autobash

### ISSUE THREAD

**Issue by dy1974** [Nyyrazzilyss/NyyLIB#239]
[2019-03-26#21-11-01.txt](https://github.com/Nyyrazzilyss/NyyLIB/files/3011460/2019-03-26.21-11-01.txt)
``

**Comment by Nyyrazzilyss** [comment]
missing bash failure message

Sorry, you can't do that while lying around.

**Comment by dy1974** [comment]
interesting...is there something I can fix?

**Comment by Nyyrazzilyss** [comment]
You 'look for the trigger named 'Your bash at a young 
alligator sends him sprawling.' and add the pattern 'Sorry, 
you can't do that while lying around.' to the end of it'
You 'That wasn't listed as a failed possible bash failure 
message'

**Comment by dy1974** [comment]
Thanks.  I'll add that!

**Comment by Nyyrazzilyss** [comment]
012dev
