### ISSUE TITLE
Portal unmapped in ghore (i think)

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#24]
On the Alligator Marsh
Exits: -N -S -W        [41966]
A creaky wooden watch tower rises up above the swamp.
A large alligator chews on a recent catch.

enter tower
On Top of a Watch Tower
Exits: -D              [41966] 
An experienced troll hunter stands here licking his chops.

**Comment by Nyyrazzilyss** [comment]
added dev 7/31
