### ISSUE TITLE
Rogue - @set condensed debug shows the following spam: [Power aliases not assigned for this class]

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#242]
[setLabelImage: TiaCincture TiaCincture-on.png]
[Bar: 1 Number: 3]
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
l
L
[onNetworkOutput: L]
Trader's Tavern
Exits: - North - South[map:update : nil]       [Map not in sync, type @find or scan to attempt
 resync] 
A human in deep blue robes sits alone at a table, sipping wine.
Payton the Tavernkeeper is here behind the bar looking at you.

< 456h/456H 126v/126V P: std > 
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
[Power aliases not assigned for this class]
att
[onNetworkOutput: att]

          Character attributes for Nanimal

Level: 50   Race: Moon Elf   Class: Rogue       
Age: 195 yrs / 0 mths  Size: Medium
STR: 110  AGI: 124  DEX: 107  CON:  89
POW:  47  INT:  88  WIS:  57  CHA:  34
Armor Class: -60  (100 to -100)  Agility Bonus: -31
Magic Resistance: 2 percent
Hitroll: 33   Damroll: 74
Alignment: Chaotic Neutral
Saving Throws: PAR[0]  ROD[0]  PET[0]  BRE[0]  SPE[0]
   Wimpy: not set
Load carried: No Sweat
Damage Resistance:
Unarmd:    0% Slash :    8% Bludgn:    8% Pierce:    8% Range :    8% 
Spells:    0% Fire  :   15% Cold  :   15% Elect :   10% Acid  :   20% 
Sonic :    0% Poison:   10% Pos   :    0% Neg   :    0% Psi   :    0% 
Mental:    0% Good  :    0% Evil  :    0% Law   :    0% Chaos :    0% 
Force :    0% 

[Power aliases not assigned for this class]
< 456h/456H 126v/126V P: std > 
[Power aliases not assigned for this class]

**Comment by Nyyrazzilyss** [comment]
7/28 dev
