### ISSUE TITLE
Warrior - Skullcrusher - Button - Timers

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#244]
There is something going on with **Warrior** skill **Skull Crusher** timers. It sets the cooldown for the triggers to 7 seconds rather than 24. I couldn't find the relevant setting for that myself. Only found one cooldown for that and it was at 24 so no idea what is going on here.

Also the cooldown trigger seem to start sometimes as soon as you queue the skill rather than on actual use.

There might be some sort of typo going on as there are sometimes two timers going at the same time **"skullcrush"** and **"skullcrusher"**. Just couldn't find the culprit myself.

Not versed in mudlet scripting so can't bug hunt this that well myself.

Triggers -> NyyLIB011 -> NyyLIB -> ClassTriggers -> War -> powers -> skullcrush
Line 8 
`timer:set("skullcrush", 24)` to `timer:set("skullcrusher", 24)`

Seemed to get things fixed.

Script version: 1/27/2019 NyyLIB011 https://github.com/Nyyrazzilyss/NyyLIB

**Comment by Nyyrazzilyss** [comment]
7/28 dev
