### ISSUE TITLE
Warrior - Spinning Sweep - !Ground - !Trip

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#245]
It seems that the warriors spinning sweep does not have any sort of no ground check, skill keeps spamming if you are in no ground room.

There was also something going on with the skill with enemies that can not be tripped if I recall correctly.

Script version: 1/27/2019 NyyLIB011 https://github.com/Nyyrazzilyss/NyyLIB

**Comment by Nyyrazzilyss** [comment]
4/13/2020 012dev
