### ISSUE TITLE
Buttons - Tank On/Off - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#249]
Here are my quick tank button suggestions as requested.

![autotank_on 2019v1](https://user-images.githubusercontent.com/1492001/61883840-cf592780-af03-11e9-9f7c-adf2d109d9bc.png)
![autotank-off 2019v1](https://user-images.githubusercontent.com/1492001/61883847-d1bb8180-af03-11e9-92e6-4fbfd069a8c3.png)

**Comment by Nyyrazzilyss** [comment]
Thanks!

**Comment by Nyyrazzilyss** [comment]
7/28 dev
