### ISSUE TITLE
duergar enlarge bug

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#25]
innate enlarge
< 1141h/483H 166v/171V P: std >

Your body grows to gigantic heights!
[  LUA  ] - Object<Your body grows taller as you complete your projection.> Function<Trigger98>
            <[string "Trigger: Your body grows taller as you comp..."]:10: attempt to concatenate a 
nil value>

----

Your body returns to its normal size.
[  LUA  ] - Object<You focus your mind and force your body to return to its natural size.> 
Function<Trigger100>
            <[string "Trigger: You focus your mind and force your..."]:4: attempt to concatenate a 
nil value>

**Comment by Nyyrazzilyss** [comment]
fixed dev 7/31
