### ISSUE TITLE
Buttons - PetRescue On/Off/Other - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#250]
These are pretty quickly made so centering is bothering me a bit on these, But here you go.

![petrescue-on](https://user-images.githubusercontent.com/1492001/61886933-49d87600-af09-11e9-9dde-793bf1b66b75.png)
![petrescue-other](https://user-images.githubusercontent.com/1492001/61886943-4ba23980-af09-11e9-826c-0013c953cb18.png)
![petrescue-off](https://user-images.githubusercontent.com/1492001/61886945-4c3ad000-af09-11e9-873a-0ece793ea485.png)

**Comment by Nyyrazzilyss** [comment]
7/28 dev
