### ISSUE TITLE
Buttons - Loot/Coins/Portal/Assist - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#252]
Just colored up existing buttons to give them more life.

![autoloot-all](https://user-images.githubusercontent.com/1492001/61906476-1a8b2e80-af34-11e9-8a0d-e3299f99759c.png)
![autoassist-on](https://user-images.githubusercontent.com/1492001/61906463-13fcb700-af34-11e9-9493-2b475181cbd4.png)
![autoportal-on](https://user-images.githubusercontent.com/1492001/61906505-2840b400-af34-11e9-8e56-02519a13474e.png)
![autoloot-coins](https://user-images.githubusercontent.com/1492001/61906508-2a0a7780-af34-11e9-8423-8e841922c54a.png)

**Comment by Nyyrazzilyss** [comment]
7/28 dev
