### ISSUE TITLE
Buttons - Magic On/Off + Auto-open - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#253]
Also changed up the magic buttons while I was it.

![SpellsButton-on](https://user-images.githubusercontent.com/1492001/61907307-e31d8180-af35-11e9-8482-3dfb9ad18897.png)
![SpellsButton-off](https://user-images.githubusercontent.com/1492001/61907312-e7499f00-af35-11e9-96a4-5d273e76687d.png)
Trying to emulate all the magic schools and the weave with this image.

![autoopen-on](https://user-images.githubusercontent.com/1492001/61908223-e7e33500-af37-11e9-89b2-bc4d29e8e9b1.png)
Made little explorer looking into the open way with a torch to give this more color.

**Comment by Nyyrazzilyss** [comment]
7/28 dev
