### ISSUE TITLE
Buttons - Check Status + Lich/Dragon Flee - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#254]
Still working on some of the buttons to make them more lively.

![chkstat](https://user-images.githubusercontent.com/1492001/61996070-e4b38a80-b098-11e9-9297-25cd7d60d4b0.png)
![flee-lich](https://user-images.githubusercontent.com/1492001/61996255-fd24a480-b09a-11e9-814f-4db2e3f2cf8f.png)
![flee-dragon](https://user-images.githubusercontent.com/1492001/61996671-8b028e80-b09f-11e9-9237-f19103771cc5.png)

**Comment by Nyyrazzilyss** [comment]
7/28 dev
