### ISSUE TITLE
Buttons - Flee On/Off - Suggestion

### ISSUE THREAD

**Issue by Kukako** [Nyyrazzilyss/NyyLIB#255]
Not sure about this, I just like cactuars as iconic escape artists.

![flee-on](https://user-images.githubusercontent.com/1492001/61996297-8a67f900-b09b-11e9-8a99-25b0f84cda37.png)
![flee-off](https://user-images.githubusercontent.com/1492001/61996302-8dfb8000-b09b-11e9-8ca3-534f3ae222b8.png)

Kind of like these more

![flee-onv2](https://user-images.githubusercontent.com/1492001/62005558-a0c69100-b13d-11e9-8424-5d5f44fac0b8.png)
![flee-off](https://user-images.githubusercontent.com/1492001/62005718-eab07680-b13f-11e9-98d7-2c693eae2e1c.png)

**Comment by Nyyrazzilyss** [comment]
012dev 10/13
