### ISSUE TITLE
Update Rogue Poison Aliases to take advantage of now being able to apply poisons from a bag

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#257]
Background:
Sometime in the last year a change was made to allow poisons to be applied directly from a bag.  It looks like the RogScript already takes this into consideration for autopoison button.  The below changes are needed to update the aliases for manually applying poisons.

**app alias:**
mud:send("apply blind primaryweapon " .. charData:get("poisonbag") )
mud:send("apply slow secondaryweapon " .. charData:get("poisonbag") )

**"apb" alias:**
mud:send("apply blind primaryweapon " .. charData:get("poisonbag") )
mud:send("apply blind secondaryweapon " .. charData:get("poisonbag") )

**"aps" alias:**
mud:send("apply slow primaryweapon " .. charData:get("poisonbag") )
mud:send("apply slow secondaryweapon " .. charData:get("poisonbag") )

**"mpp" alias:**
mud:send("apply milky primaryweapon " .. charData:get("poisonbag") )
mud:send("apply milky secondaryweapon " .. charData:get("poisonbag") )

Lastly, a new alias should be added for applying ray poison (used when fighting Remorhaz dragon's and whatnot) to weapons.
**Alias name:** 
apr - apply poison ray

**Alias pattern:** 
^apr$

**Alias code to execute upon receiving "apr":**
mud:send("apply ray primaryweapon " .. charData:get("poisonbag") )
mud:send("apply ray secondaryweapon " .. charData:get("poisonbag") )

**Tests:**
I tested each alias locally successfully.

**Comment by Nyyrazzilyss** [comment]
Thanks!

**Comment by Nyyrazzilyss** [comment]
12/7/19 012dev
