### ISSUE TITLE
Bard/Battle Autobless Bug

### ISSUE THREAD

**Issue by saerian** [Nyyrazzilyss/NyyLIB#260]
Hey Nyy!

We spoke about this briefly, but I wanted to write it here. There's a bug with @autobless, currently no matter the value, it always treats it as "true". I've manually set @autobless false, turned the button off, etc, and it always re-enables and autocasts. Normally that wouldn't bother me, but it always tends to cast when we are about to move, so I get left behind because of the autocast.

I think it has to do with this code in singerscript ... I commented it out and it stopped .. though I don't think it will work if I try to turn it on.

		-- cast harmonious blessing if down and not moving
		if charData:get("autobless") then
			if not buff:get("harmonious_blessing") then
				if getSpellCount("harmonious_blessing") > 0 then
					if not spell:getMoving() then
						spell:cast("hbl")
					end
				end
			end
		end

**Comment by Nyyrazzilyss** [comment]
function barBless(fname, xcommand)
	if xcommand ~= buttons.INIT then
    shiftSkillButton("barBless", "autobless", xcommand)
  end

	if charData:get("autobless") then
		setLabelImage(fname, fname .. "-on.png")
	else
		setLabelImage(fname, fname .. "-off.png")
	end
end

**Comment by Nyyrazzilyss** [comment]
12/7/19 012dev
