### ISSUE TITLE
bard/bchant circle

### ISSUE THREAD

**Issue by sarelon** [Nyyrazzilyss/NyyLIB#261]
Circle not included in button bar.

Added:
addbutton("Circle",0, 11, 22)

and 

function circle(fname, xcommand)
	shiftSkillButton("circle", "autocircle", xcommand)
end

to the SingerScript and it seems to be working.  Have not tested to see if it actually sends the circle command.

**Comment by Nyyrazzilyss** [comment]
12/7/19 012dev
