### ISSUE TITLE
Ranger Blades of Fire

### ISSUE THREAD

**Issue by sarelon** [Nyyrazzilyss/NyyLIB#262]
Blades of Fire on button bar ended at "1" and never reset.  Trigger missing.

Name: blades of fire (drop)
Pattern: ^The flames around your weapons subside.$ - perl/regex

-- The flames around your weapons subside.
buff:set(whoami(), "blades_of_fire", nil)
timer:set("blades_of_fire", 0)

Tested and working

**Comment by Nyyrazzilyss** [comment]
Corrected in process of adding Hexblade. It wasn't just blades of fire that had the issue, but a number of spells/skills weren't clearing the button when the timer expired (and leaving a 1 behind)

**Comment by Nyyrazzilyss** [comment]
012dev 10/13
