### ISSUE TITLE
auto power use breaks

### ISSUE THREAD

**Issue by Lamnicaes** [Nyyrazzilyss/NyyLIB#265]
If the script attempts to use a power right when you're casting a spell, it can cause the powers to stop firing automatically.

< 485h/520H 129v/129V |0|1|1|0|1| T: Sarberos TC: few scratches E: forell EC: nasty wounds EP: rcl P: std > 
[Forell Luckaun has nasty wounds!]

Your massive bludgeon barely wounds Forell Luckaun.
Your massive vampiric slash barely wounds Forell Luckaun.
Your massive bludgeon barely wounds Forell Luckaun.
Your longsword glows dark and bites into Forell Luckaun's neck.
########## BLIND ##########
Forell Luckaun shivers slightly.
Forell Luckaun seems to be blinded!
Your massive vampiric slash barely wounds Forell Luckaun.
Your massive bludgeon barely wounds Forell Luckaun.
Your massive bludgeon barely wounds Forell Luckaun.
Forell Luckaun misses you with his hit.
Forell Luckaun misses you with his hit.
Forell Luckaun clambers to his feet.

< 516h/520H 129v/129V |1|1|1|1|1| T: Sarberos TC: few scratches E: forell EC: nasty wounds EP: std P: std >

[SPELL: Cloak of Resilience] CLR

< 516h/520H 129v/129V |1|1|1|1|1| T: Sarberos TC: few scratches E: forell EC: nasty wounds EP: std P: std >

You start chanting...

[MELEE: Sweeping Strike] SS
 [Casting: SS ()]

< 516h/520H 129v/129V |1|1|1|1|1| T: Sarberos TC: few scratches E: forell EC: nasty wounds EP: std P: std >

You're busy spellcasting!  [Queing error: SS]

< 516h/520H 129v/129V |1|1|1|1|1| T: Sarberos TC: few scratches E: forell EC: nasty wounds EP: std P: std > 
You complete your spell... [ SS () ]
Wispy bands of shadow clasp about you in a cloak of resilience.

From this point, powers no longer worked until I manually use a power, then it starts back up.

**Comment by Nyyrazzilyss** [comment]
12/7/19 012dev
