### ISSUE TITLE
Command queue sometimes interfers with autoroller, i.e. need to type capital letter to bypass Nyyscript

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#269]
Identified during https://github.com/Nyyrazzilyss/NyyLIB/issues/268

Exit Criteria:
Reset command queue when entering character roller or when at "Characters" login menu

**Comment by Gyrx** [comment]
Could we key clearing the command queue off:

Type the # or name of a character above to login or choose an action below.

**Comment by Nyyrazzilyss** [comment]
In Events->initNyyLIB

function firstPrompt()
 -- Initialization trigger on reconnect to toril.
 -- Enable single letter aliases
 enableAlias("movement commands")
 enableAlias("p")
 enableAlias("g")

function initNyyLIB()
-- Disable single letter aliases
disableAlias("movement commands")
disableAlias("p")
disableAlias("g")


Quick fix, only works on startup (if you haven't logged in). If you logged in then rented to roll a char, the problem would still occur.

**Comment by Nyyrazzilyss** [comment]
4/13/2020 012dev
