### ISSUE TITLE
Add @help fwalk to @help list & reference @path in @help fwalk

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#272]
There's two great commands new script users should be able to self educate on, @fwalk and @path.

I recommend adding these in two places:

1. Under the "@help" command, @help @fwalk should be listed.  @help would then look like:

               NyyLIB Help documentation

Any of the below commands will provide further information. 

@help index      - list all help entries
@help gui        - how to use buttons, window setup
@help sound	     - enabling sound
@help icons	     - instructions for creating icon png files
@help @roll      - auto-roller for creation of new characters
@help @set       - help with use of the 'set' command
@help @map       - information about use of the mapper
@help database   - further information on the Katumi database
@help alias      - various aliases included with the package
@help @bid       - the included bidding script
@help xptrain    - The Adud Train
@help @stats     - a warrior statistics package
**@help @fwalk    - how to fast walk with the script**

2. Under @help @fwalk, there should be a reference to @help @path.  At the bottom of @help @fwalk, append:

**See also: @help @path**

**Comment by Nyyrazzilyss** [comment]
4/13/2020 012dev
