### ISSUE TITLE
Hexblade @rescuetype keeps changing back to basic

### ISSUE THREAD

**Issue by Lamnicaes** [Nyyrazzilyss/NyyLIB#273]
Just making a note for this:

Nyyrazzilyss ASSOC: 'Ah it's in the xp train'
Nyyrazzilyss ASSOC: 'When it turns it off, if you're a ranger it also turns off rescue. Doesn't do that if you're hex'

**Comment by Nyyrazzilyss** [comment]
Aliases->BOTS->@stoptrain

if checkMask("ran") or checkMask("hex") then
buttons:change("rescuetype", "off", "rescue")
end

**Comment by Nyyrazzilyss** [comment]
4/13/2020 012dev
