### ISSUE TITLE
cant see  tells and such

### ISSUE THREAD

**Issue by kalthazz** [Nyyrazzilyss/NyyLIB#275]
some of  the tells i get  are blank or in a different color and  can hear the  ping but cant see some tells and sending some tells i dont see what is typed and also assoc i cant see my name or title

**Comment by Nyyrazzilyss** [comment]
This sounds like either you gagged yourself, or made changes to the script that caused the problem to occur. Create and install an unmodified copy of the script into a new profile, and repost if this can be duplicated with an unmodified script.
