### ISSUE TITLE
[Faang][Mapper] Map doesn't correctly update when moving between 2 specific rooms

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#289]
When I go up or down between these rooms the map breaks, I need to @find to correct. Log below.

           ----------------------
                                  (x5)
               
Below the Eastern Guard
Exits: -E -W -U [Error: mud 'Below the Eastern Guard' doesn't match mapper 'Office of the Biggest,
 Meanest and Ugliest Guard' at '12552']         [12552] 
A boulder sits here, marked with horrible handwriting.
A proud ogre shaman starts to chant as you approach.

< 862h/862H 171v/175V P: std > 
@find

[Searching... Match found: Faang - City of Ogres : Below the Eastern Guard : 79393]
u
[onNetworkOutput: u]
               

                                  (x5)
               ---               
              |.@.|              
              | # |              
              |,<,|              
       ---    | + |-------       
      |.-.|   |, ,|.-. .-.|      
      | + ----- + |       |      
      |,-, ,-, , ,+.-. .-.|      
               
Office of the Biggest, Meanest and Ugliest Guard
Exits: -S -D [Error: mud 'Office of the Biggest, Meanest and Ugliest Guard' doesn't match mapper
 'Below the Eastern Guard' at '79393']            [79393] 
An ogre trapper is here, setting a trap.
A heavily armed orc hobbles here, bounding from rock to rock.
The ghoul of an orog warrior stands here.
The spectre of an orog warrior stands here.
The wight of an orog warrior stands here.
A giant-ogre crossbreed guard is here, totally ignoring you.
An ugly ogre guard glares at you.

**Comment by Nyyrazzilyss** [comment]
Fixed in 013dev
