### ISSUE TITLE
"fly" NyyScript alias causes conflicts with 1) bahamat rogue claw "fly" powers name 2) enchanter "fly" powers spell

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#294]
Bahamut gear "the hollowed claw of a balor demon" has a "fly" powers to grant self fly for 1 hour.  Enchanter "fly" powers spell also conflicts. Neither of these can be used until disabling the "fly" alias.

Combat Powers:
-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=--=-=--=-=-=-=-=-=-=-=-=-=--=-=-=-
Wings of the Balor                  [fly   ]                   Equipment 

NyyScript pattern: ^fly$

if charData:get("container") == nil then
	cecho("<red>[container not set]\n")
	return
end

mud:send("rem swirling")
mud:send( p("swirling") )
mud:send( g("wings") )
mud:send("wear wings")

**Comment by Nyyrazzilyss** [comment]
Changed the alias to ^ffly$
