### ISSUE TITLE
Katumi update

### ISSUE THREAD

**Issue by Nyyrazzilyss** [Nyyrazzilyss/NyyLIB#298]
Download and update katumi database
-----
Alias:

name: @updatedb
pattern: ^@updatedb$

cecho("<red>Downloading current Katumi database.\n")
downloadFile("toril.db", "http://www.grokh.com/toril.db")

--------
Script:

name: katumiUpdate
event: sysDownloadDone

function katumiUpdate(k, v)
  -- k is function name. v is filename
    
  if v == "toril.db" then
    cecho("<green>Katumi download completed.\n")

    copyFile(v, mainpath(v))

    cecho("<green>Connecting to updated database.\n")
 
    sqlOpen()

    -- delete the downloaded file
    os.remove(v)
  end
end

**Comment by Hibbidy** [comment]
cecho("Downloading current Katumi database.\n")
local saveto = getMudletHomeDir().."/toril.db"
local url = "http://www.grokh.com/toril.db"
downloadFile(saveto, url)
cecho("<white>Downloading <green>"..url.."<white> to <green>"..saveto.."\n")

**Comment by Nyyrazzilyss** [comment]
@updatedb

cecho("<red>Downloading current Katumi database.\n")
downloadFile( homepath("toril.db"), "http://www.grokh.com/toril.db")


function katumiUpdate(k, v)
  -- k is function name. v is filename
    
  if string.find(v, "toril.db") then
    cecho("<green>Katumi download completed.\n")

    copyFile(v, mainpath("toril.db"))

    cecho("<green>Connecting to updated database.\n")
 
    sqlOpen()

    -- delete the downloaded file
    os.remove(v)
  end
end
