### ISSUE TITLE
broken map link

### ISSUE THREAD

**Issue by Nyyrazzilyss** [Nyyrazzilyss/NyyLIB#299]
Irune 'Apparently room 78824 doesn't link east to room 78823,

**Comment by Klandan** [comment]
Above comment was in Myth Unnohyr.

These are near Skerttd-Gul.
Rm#18379 should have no south exit

Rm#18400 should have north exit that teleport-links to #18406 (to SE part of this area)
Rm#18406 should have south exit that teleport-links back to #18400

I don't think the room #18432 is reachable (should be deleted).

**Comment by Klandan** [comment]
Nizari
Rm#14365 should have the exit to east as 1-way
Rm#14360 has no west exit (so it can't go back to 14365 directly)

**Comment by Klandan** [comment]
Near Ashstone fixes:
lua setExit(44910,-1,"s")
lua setExit(44910,44911,"s")
lua setExit(44915,-1,"s")

**Comment by Nyyrazzilyss** [comment]
@Lurxx/Lurxx 'found a couple rooms you missed in dark forest'
@Lurxx/Lurxx 'search in room 76030 and there is a secret entrance east'
@Lurxx/Lurxx 'and another east exit from 76008'

**Comment by Nyyrazzilyss** [comment]
@Innova/Mukob 'looks like you don't have a link between room 48467 and 48468 (NW corner of SM)'

**Comment by Nyyrazzilyss** [comment]
Snurgt 'its the set of rooms down from the boulder down exit in southern 
forest'
Snurgt 'vnum 43399'

**Comment by Nyyrazzilyss** [comment]
Innova 'FYI, room 80772 in Skull port isn't connected to anything...should 
be connected to 80771'
