### ISSUE TITLE
Unmapped rooms: Baldur's Gate - Wave Dancer

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#3]
Unable to locate rooms on map for Wave Dancer Ship in BG.

The End of a Long Wooden Shipping Pier
Exits: -E -S           [2985] 
The Barracuda, a small merchant ship, floats gently nearby. (illuminating)
The Wave Dancer, a sleek merchant vessel, rocks gently in the water here. (illuminating)
A fisherman stands here, fishing off the pier.
A burly half-orc sailor stands here, collecting tickets.

< 946h/946H 491p/491P 121v/122V P: std Sat Jul  8 23:54:11 2017

The Loading Deck of the Wave Dancer
Exits: -N                   [Unmapped] 
A burly sailor scrambles about here, checking the rigging.

**Comment by Nyyrazzilyss** [comment]
updated in dev
