### ISSUE TITLE
In the middle of an XP Train fight, why did my abilities (e.g. bash) stop triggering?

### ISSUE THREAD

**Issue by heyches** [Nyyrazzilyss/NyyLIB#308]
[Reached train station: (48681) Corland Deepforge]

[onNetworkOutput: glance Corland]
Corland Deepforge is in an excellent condition. (Medium)

< 903h/719H 154p/154P 149v/155V |ps +|sot +|bc +|drs 49|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
P: std > 

[No longer moving. Spellcasting has resumed]

[Attacking: Corland]

~~~~~~~~~~~~~~~~~~~~~~~~~~
// THIS IS MY FIRST BASH
~~~~~~~~~~~~~~~~~~~~~~~~~~

[MELEE: Dominating Smite] DS CORLAND
[onNetworkOutput: DS CORLAND]
You advance upon Corland Deepforge with a series of devastating blows.
Corland Deepforge&160 is sent crashing to the ground!

< 901h/719H 154p/154P 152v/155V |ps +|sot +|bc +|drs 48|ds 3|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 
[onNetworkOutput: LOOK]
< 900h/719H 154p/154P 152v/155V |ps +|sot +|bc +|drs 48|ds 3|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
You block Corland Deepforge's attack with your shield!

< 897h/719H 154p/154P 155v/155V |ps +|sot +|bc +|drs 48|ds 3|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

[MELEE: Baleful Challenge] BC
[onNetworkOutput: BC]
You radiate a powerful sense of crushing dread as you confront Corland Deepforge.
Corland Deepforge turns his attention to you.
[onNetworkOutput: LOOK]

< 897h/719H 154p/154P 155v/155V |ps +|sot +|bc 15|drs 47|ds 1|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std >

< 896h/719H 154p/154P 155v/155V |ps +|sot +|bc 15|drs 47|ds 1|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

Corland Deepforge's attack only grazes you as you dodge aside!
Corland Deepforge slightly wounds you with his strong hit.
You score a CRITICAL HIT!
Your massive bludgeon barely wounds Corland Deepforge.
Your attack only grazes Corland Deepforge as he dodges aside!
Your powerful bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.

< 866h/719H 154p/154P 155v/155V |ps +|sot +|bc 15|drs 47|ds 1|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

Corland Deepforge misses you with his hit.
You miss Corland Deepforge with your bludgeon.
You miss Corland Deepforge with your bludgeon.
Your massive bludgeon barely wounds Corland Deepforge.

< 863h/719H 154p/154P 155v/155V |ps +|sot +|bc 14|drs 46|ds 1|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

[MELEE: Dark Majesty] DM
[onNetworkOutput: DM]
Dark tendrils crawl forth from your shield and wrap around you as you strike out at Corland
Deepforge.

< 862h/719H 154p/154P 155v/155V |ps +|sot +|bc 13|drs 45|ds +|dm 3|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: rcl P: std > 

Corland Deepforge misses you with his hit.
Corland Deepforge clambers to his feet.
Your mighty bludgeon barely wounds Corland Deepforge.
Your mighty bludgeon barely wounds Corland Deepforge.
Your attack only grazes Corland Deepforge as he dodges aside!
Your strong bludgeon barely wounds Corland Deepforge.

< 860h/719H 154p/154P 155v/155V |ps +|sot +|bc 13|drs 45|ds +|dm 3|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few scratches EP: std P: std > 

Corland Deepforge's attack only grazes you as you dodge aside!
Corland Deepforge barely wounds you with his strong hit.
Corland Deepforge starts casting an offensive spell.
Your awesome bludgeon barely wounds Corland Deepforge.
Your awesome bludgeon barely wounds Corland Deepforge.
Your attack only grazes Corland Deepforge as he dodges aside!
Your powerful bludgeon barely wounds Corland Deepforge.

< 832h/719H 154p/154P 155v/155V |ps +|sot +|bc 12|drs 44|ds +|dm 2|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// THIS IS MY SECOND (AND FOR SOME REASON, MY LAST) BASH
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[MELEE: Dominating Smite] DS
[onNetworkOutput: DS]
You advance upon Corland Deepforge with a series of devastating blows.
Corland Deepforge&160 is sent crashing to the ground!

< 832h/719H 154p/154P 155v/155V |ps +|sot +|bc 11|drs 43|ds 3|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 
Corland Deepforge stops chanting abruptly!

< 832h/719H 154p/154P 155v/155V |ps +|sot +|bc 11|drs 43|ds 3|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

Blood sprays from Corland Deepforge as you deflect his attack.
You block Corland Deepforge's attack with your shield!
Your awesome bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.

< 830h/719H 154p/154P 155v/155V |ps +|sot +|bc 11|drs 43|ds 3|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

[Baleful Challenge has expired on Digu.]

The shadowy tendrils around you slowly unfurl and fade away.

< 829h/719H 154p/154P 155v/155V |ps +|sot +|bc 10|drs 42|ds 2|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

[MELEE: Dark Majesty] DM
[onNetworkOutput: DM]
Dark tendrils crawl forth from your shield and wrap around you as you strike out at Corland
Deepforge.

< 829h/719H 154p/154P 155v/155V |ps +|sot +|bc 9|drs 41|ds 1|dm 3|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

You deflect Corland Deepforge's blow, and strike back at Corland Deepforge!
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.

< 827h/719H 154p/154P 155v/155V |ps +|sot +|bc 9|drs 41|ds 1|dm 3|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

You dodge Corland Deepforge's vicious attack.
Your massive bludgeon barely wounds Corland Deepforge.
Your attack only grazes Corland Deepforge as he dodges aside!
Your powerful bludgeon barely wounds Corland Deepforge.
You miss Corland Deepforge with your bludgeon.

< 825h/719H 154p/154P 155v/155V |ps +|sot +|bc 8|drs 40|ds 1|dm 2|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

[MELEE: Plundering Smite] PS
[onNetworkOutput: PS]
Your strike leaves a vile blight on Corland Deepforge, and some of his life flows into you.

< 862h/719H 154p/154P 155v/155V |ps 3|sot +|bc 8|drs 40|ds +|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: rcl P: std > 

You dodge Corland Deepforge's vicious attack.
Corland Deepforge clambers to his feet.
Your mighty bludgeon barely wounds Corland Deepforge.
Your awesome bludgeon barely wounds Corland Deepforge.
Corland Deepforge dodges your futile attack.

< 860h/719H 154p/154P 155v/155V |ps 3|sot +|bc 8|drs 40|ds +|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 

@Innova/Mubab OOC: 'Level: 50   Race: Barbarian   Class: Warrior'

< 859h/719H 154p/154P 155v/155V |ps 3|sot +|bc 8|drs 40|ds +|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
@Innova/Mubab OOC: 'Playing time: 1 days / 6 hours / 52 minutes'

< 859h/719H 154p/154P 155v/155V |ps 3|sot +|bc 8|drs 40|ds +|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
@Innova/Mubab OOC: 'I think I could get it under 24 hours if I tried harder.....people with
better eq could probably get quite a bit lower :)'

< 859h/719H 154p/154P 155v/155V |ps 2|sot +|bc 7|drs 39|ds +|dm 1|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
The shadowy tendrils around you slowly unfurl and fade away.

< 858h/719H 154p/154P 155v/155V |ps 1|sot +|bc 6|drs 38|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
Corland Deepforge misses you with his hit.
Corland Deepforge starts casting an offensive spell called 'full harm'.
Your mighty bludgeon barely wounds Corland Deepforge.
Corland Deepforge dodges your futile attack.
Your mighty bludgeon barely wounds Corland Deepforge.

< 857h/719H 154p/154P 155v/155V |ps 1|sot +|bc 6|drs 38|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
Your massive bludgeon barely wounds Corland Deepforge.
Corland Deepforge dodges your futile attack.
Your massive bludgeon barely wounds Corland Deepforge.

< 854h/719H 154p/154P 155v/155V |ps 1|sot +|bc 5|drs 37|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 
Corland Deepforge completes his spell...
Corland Deepforge utters the words, 'yjrr pabraw'.
You shriek in agony as Corland Deepforge's righteous fury tears wounds into your body.
OUCH!  That really did HURT!

< 720h/719H 154p/154P 155v/155V |ps +|sot +|bc 5|drs 37|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: small wounds EP: std P: std > 

You dodge Corland Deepforge's vicious attack.
Corland Deepforge starts casting an offensive spell called 'full harm'.
Your mighty bludgeon barely wounds Corland Deepforge.
Your mighty bludgeon barely wounds Corland Deepforge.
Your mighty bludgeon barely wounds Corland Deepforge.

< 719h/719H 154p/154P 155v/155V |ps +|sot +|bc 5|drs 37|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few wounds EP: std P: std > 

Your mighty bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.
Your massive bludgeon barely wounds Corland Deepforge.

< 719h/719H 154p/154P 155v/155V |ps +|sot +|bc 4|drs 36|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: excellent E: corland EC: few wounds EP: std P: std > 

Corland Deepforge completes his spell...
Corland Deepforge utters the words, 'full harm'.
You shriek in agony as Corland Deepforge's righteous fury tears wounds into your body.
OUCH!  That really did HURT!

< 581h/719H 154p/154P 155v/155V |ps +|sot +|bc 3|drs 35|ds +|dm +|rs +|fr +|fs +| |3|1|1|1|0|
T: Digu TC: small wounds E: corland EC: few wounds EP: std P: std >

**Comment by Nyyrazzilyss** [comment]
I don't see any obvious reasons why the script would have stopped triggering.
The final skill used was plundering smite, and the mud response

Your strike leaves a vile blight on Corland Deepforge, and some of his life flows into you.

Matches the plundering smite trigger that should have reset the script for next skill usage. Are you seeing this quite often, or was it a one-off occurance?

**Comment by heyches** [comment]
Ever since I turned off smartprompt days ago, this is probably the first instance, so it's very rare.  Seeing that right after the plundering smite, there were some OOC lines.  Do you think those interjections would affect how the script runs?

**Comment by heyches** [comment]
I think I figured out why.  Whenever there's a hiccup in my internet connection (e.g. switching to a VPN), my XP train will stop, and the abilities will stop -- but I'll still be signed on and still be fighting in the middle of battle until death).

**Comment by Nyyrazzilyss** [comment]
Going to close this at almost a year old at this time. Shev had done various changes recently with the mud and i've posted a couple new versions that hopefully had also addressed this. Resubmit please if train issues still happening.
