### ISSUE TITLE
bug with path using grin grinning

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#31]
grin skull
At a Pillar of Stone Embedded with Skulls
Exits: -E -S           [75824] 
[9] A grinning skull rests here.
An enormous pillar of stone stands here.

< 554h/712H 111v/111V P: std > 
#fwalk 697
[Path: .;grin grinning;3en7en4en2es5e2s4e15uw5us5ue2ne11n2wn2u3e18n]
[  LUA  ] - Object<#fwalk> Function<Alias164>
            <getSpecialExitsSwap: wrong argument type>
grin skull
Beginning of the Main Complex
Exits: -N -E -S        [75824] 
A grinning skull rests here.
An overgrown rat stands here sniffing about.

**Comment by Nyyrazzilyss** [comment]
maybe fixed 011dev 08/21
