### ISSUE TITLE
unable to use train or inittrain commands

### ISSUE THREAD

**Issue by kalthazz** [Nyyrazzilyss/NyyLIB#310]
unable to run the train and inittrain command as keep getting errors when trying to use @find or @inittrain commands

**Comment by kalthazz** [comment]
also cant use scan even if in the inn
                                              .


[Searching... {}
Solve scan failed. Multiple (0) matches found]

**Comment by Nyyrazzilyss** [comment]
This is the only reported issue of this nature. I'd just probably a need to create + reinstall to a new profile.
