### ISSUE TITLE
Chat window font size (NyyLIB013dev)

### ISSUE THREAD

**Issue by Siyooni** [Nyyrazzilyss/NyyLIB#312]
There is no way to change the font size in the new 013 (unlike the previous versions).  @set chatfontsize doesn't seem to work.  

The screen shot is on a 1920x1080 monitor but the chat text gets comparably larger when playing on a laptop monitor.  

Also, I keep getting this below message whenever the mouse cursor goes over the left side bar, or whenever readjusting the Mudlet window size.  

[Error: file C:/Users/dank1/.config/mudlet/profiles/Toril/NyyLIB013dev/buttons/TiaCrescent-on.png not found]

Thanks Nyyrazzilyss!

![image](https://user-images.githubusercontent.com/123522161/214456714-e624532f-bfcd-4500-a058-f930e69c4dcb.png)

**Comment by Nyyrazzilyss** [comment]
Should be fixed in 1/29 013dev

**Comment by Siyooni** [comment]
Thanks Nyyrazzilyss!

The chat window is so much more pleasant to look at now:


![image](https://user-images.githubusercontent.com/123522161/215368276-fc3720cf-3605-4c4c-ae54-8f7675a4c63e.png)


Although that TiaCrescent png error is a bit annoying.  I was able to remove it by just copy/renaming another png file to TiaCrescent-on and -off.  lol.
