### ISSUE TITLE
Bug with rogue auto assist (backstab)

### ISSUE THREAD

**Issue by sekfarok** [Nyyrazzilyss/NyyLIB#32]
it tries to backstab the slaad instead of the mob.

< 719h/719H 119v/119V P: std > 
An elite orc guard partially blocks a gray slaad's attack with his shield!
A gray slaad barely wounds an elite orc guard with its average strike.
A gray slaad misses an elite orc guard with its strike.
An elite orc guard partially deflects Bonble's lunge at him.
Bonble barely wounds an elite orc guard with his strong pierce.
**[bs slaad]**
An elite orc guard deflects Bonble's blow, and strikes back at Bonble!
An elite orc guard misses Bonble with his slash.

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
