### ISSUE TITLE
room missing in faang

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#34]
A Vertical Passage Way (No Ground)
Exits: -U -D           [84511]  [Hidden]

< 572h/572H 203v/204V P: std >

A Vertical Passage Way (No Ground)
Exits: -U -D           [84512]  [Hidden]

< 572h/572H 202v/204V P: std > 
d
A Vertical Passage Way (No Ground)
Exits: -U -D           [84513]  [Hidden]

< 572h/572H 202v/204V P: std > 
d
A Vertical Passage Way (No Ground)
Exits: -U -D           [84513]  [Hidden]

< 572h/572H 202v/204V P: std > 
d
Bottom of a Treacherous Pit
Exits: -U              [84513]  [Hidden]
*A gigantic black widow stands here, motionless in the dark.

< 572h/572H 203v/204V P: std > 
#find

[Searching... No matches found: Bottom of a Treacherous Pit]

**Comment by Nyyrazzilyss** [comment]
added 011dev 08/21
