### ISSUE TITLE
Cleric exp train not working

### ISSUE THREAD

**Issue by TanjiSmanji** [Nyyrazzilyss/NyyLIB#35]
Use starttrain fol command on cleric and nothing happens. I don't flee to remem or use nukes or heal.

starttrain fol
[Setting statname to unset]
[All train triggers disabled]
[Laying train tracks...]
[Starting train car...]
[Setting autoloot to off]
[Setting flee to on]
[Setting autoassist to true]
< 633h/605H 100v/100V P: std >

< 633h/605H 100v/100V P: std > 
You now flee at 605 hit points or less!

< 633h/605H 100v/100V P: std > 

Not fleeing to remem or setting autocast on. If autocast is turned on manually it will cast seletect spells but not flee to remem and return.

**Comment by TanjiSmanji** [comment]
Auto spells don't seem to turn on, just auto assist.

**Comment by Nyyrazzilyss** [comment]
Runecopple tells you 'Script version: 011dev 7/20/2017'

Install the last newer release (011c ) then indicate if problem is still occuring.
