### ISSUE TITLE
Unable to connect map to: Calimport, The Barracuda

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#4]
After entering the Barracuda ship in BG I was unable to sync the map to unlock them in my map.

The zone is listed as undiscovered for me in #map info.

Exploring the four rooms on the ship with #find it looks like the problem is there are other matching rooms.  Scan also has the same problem of not syncing the map (I imagine another ship as the same layout?)

Log:
Atop the Mainmast in the Crow's Nest
Exits: -D                   [Unmapped] 

scan
< 946h/946H 491p/491P 120v/122V P: std Sat Jul  8 23:56:36 2017 > 

You scan down...
On the Maindeck
Exits: -E -W -U
A peg-legged sailor stands here, seeing that the crew doesn't slack off.

< 946h/946H 491p/491P 120v/122V P: std Sat Jul  8 23:56:37 2017 > 
#find

[Searching... Solve scan failed. Multiple (2) matches found]
d
On the Maindeck
Exits: -E -W -U             [Unmapped] 
A peg-legged sailor stands here, seeing that the crew doesn't slack off.

< 946h/946H 491p/491P 121v/122V P: std Sat Jul  8 23:56:41 2017 > 
#find

[Searching... Multiple (2) matches found: On the Maindeck]
e
On the Aft Deck
Exits: -W                   [Unmapped] 
The ship's wheel is bolted firmly in place here, lashed to the railing
A group of sailors stands here, tending to the rigging.
Captain Falnor stands nearby, his fists clenched on the wheel.

#find

[Searching... Multiple (3) matches found: On the Aft Deck]
< 946h/946H 491p/491P 121v/122V P: std Sat Jul  8 23:56:44 2017 > 
w
w
On the Maindeck
Exits: -E -W -U             [Unmapped] 
A peg-legged sailor stands here, seeing that the crew doesn't slack off.

< 946h/946H 491p/491P 120v/122V P: std Sat Jul  8 23:56:46 2017 >

On the Foredeck
Exits: -E                   [Unmapped] 

< 946h/946H 491p/491P 120v/122V P: std Sat Jul  8 23:56:46 2017 > 
#find

[Searching... Multiple (4) matches found: On the Foredeck]
scan

You scan east...
On the Maindeck
Exits: -E -W -U
A peg-legged sailor stands here, seeing that the crew doesn't slack off.

< 946h/946H 491p/491P 122v/122V P: std Sat Jul  8 23:56:49 2017 >

**Comment by Nyyrazzilyss** [comment]
updated in dev
