### ISSUE TITLE
Invoker buttons - autohlarea

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#49]
Ball lightning button is there, but when it casts and the count is 0, it does not move to the next spell - meteorswarm, then incendiary cloud.

I have quested ball lightning and meteorswarm - and it looks like the buttons exist, as do the autohlarea flag for each - though even if I hadn't, i imagine incendiary cloud (non-quest spell) should show up - so not sure whats up.

**Comment by Nyyrazzilyss** [comment]
Meteorswarm was misnamed with a space.

You didn't have incendiary cloud memorized.
