### ISSUE TITLE
Enhancement Idea: Have exp train move to next train stop if another human player is already in the room (and potentially about to engage mob )

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#56]
If I enter a destination trainstop room and another human player is already in the room I could avoid both myself and additional player glancing and engaging the excellent mob if I automatically moved to the next train stop if a human was detected.

Sample zmud script. I adjusted grey elf and added half-orc but could be missing another race:

#TRIGGER {(%1) *({Yuan-ti|Ogre|Orc|Half-Orc|Troll|Duergar|Illithid|Drow Elf|Moon Elf|Barbarian|Human|Dwarf|Gnome|Halfling|Half-Elf})* {stands|sits|sprawled|lying|floats|flies}} {#VAR Examined 1;#if (%ismember( %1, @grouplist)) {} {#MATH PeopleInRoom {@PeopleInRoom+1};#VARIABLE TargetFound 0;#VARIABLE KillMe {};#VARIABLE Examined 0} {stalk}}

**Comment by Nyyrazzilyss** [comment]
Will be in next posted dev
