### ISSUE TITLE
kobold settlement issue with newest version?

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#58]
Before a Giant Wooden Fence
Exits: -N# -E -S -W
[Added area: (5) Kobold Settlement
]
[internalid error in room: 41187]
5

"X"

"Likely to crash"

41187

5

"5"

"Kobold Settlement
"

[  LUA  ] - Object<^Exits: (.*)> Function<Trigger1331>
            <[string "Script: MapperScripts"]:422: attempt to call global 'findAreaID' (a nil 
value)>

**Comment by Hibbidy** [comment]
Backed up current profile, created brand new profile, restored from backup, @map updateok - 

Got this output: 


< 598h/598H 171v/171V P: std > 
@map updateok
[  OK  ]  - Map loaded successfully (0s).

[Added area: (34) Mithril Hall - City of Dwarves]

[Added area: (247) The Northern Caravan Trail]

[Added area: (268) IceCrag Castle]

[Added area: (242) The Tarsellian Forest]

[Added area: (221) The Dwarven Mining Settlement]

[Added area: (274) Trade]

[Added area: (63) The Lurkwood]

[Added area: (246) The Northern High Road-2]

[Added area: (245) The Northern High Road]

[Added area: (45) Great Northern Road]

[Added area: (235) Dragonsfall Forest]

[Added area: (59) Lake Skeldrach Shore]

[Added area: (20) Waterdeep Trails]

[Added area: (19) Wilderness Roads]

[Added area: (72) Tower of High Sorcery One]

[Added area: (290) The Evermoor Way]

[Added area: (236) Menden-on-the-Deep]

[Added area: (73) New Cavecity]

[Added area: (64) The Evermoors]

[Added area: (17) Northern Waterdeep Main City]

[Added area: (16) Southern Waterdeep Main City]

[Added area: (18) Central Waterdeep Main City]

[Added area: (25) Alterian Region - Wilderness]

[Added area: (23) Caves of Mt. Skelenak]

[Added area: (29) The Guilds of Waterdeep]

[Added area: (10) Valley of Crushk]

[Added area: (146) The Sedawi Mountain Village]

[Added area: (96) The Roads of the Heartland]

[Added area: (26) Alterian Region - Mountains]

[Added area: (53) Lava Tubes One]

[Added area: (46) Village of Split Shield]

[Added area: (30) The Ashstone Trail]

[Added area: (266) The Greycloak Hills]

[Added area: (70) The_Wildland_Trails]

[Added area: (33) Scornubel]

[Added area: (243) The Dusk Road]

[Added area: (251) Baldur's Gate - Docks]

[Added area: (250) Baldur's Gate - Main City]

[Added area: (31) The Western Realms]

[Added area: (223) Farm of the Undead]

[Added area: (271) Havenport]

[Added area: (163) Calimport, the Docks]

[Added area: (161) Calimport, the City]

[Added area: (241) Calimshan Beach]

[Added area: (164) Calimport, the Palace]

[Added area: (261) Mistywood]

[Added area: (71) Southern Forest]

[Added area: (214) Ashrumite_Village]

[Added area: (9) The Troll Hills]

[Added area: (257) The Trader's Road]

[Added area: (258) The Reaching Woods - Part I]

[Added area: (244) The Fog Enshrouded Wood]

[Added area: (47) Griffon's Nest]

[Added area: (97) The Roads of the Heartland 2]

[Added area: (95) Viperstongue Outpost]

[Added area: (222) Spiderhaunt Woods]

[Added area: (74) Faang - City of Ogres]

[Added area: (38) Leuthilspar - City of Elves]

[Added area: (66) Faerie Realm]

[Added area: (94) The Calimshan Desert]

[Added area: (145) Desert City of Nizari]

[Added area: (76) Beluir - City of Halflings]

[Added area: (226) Zhentil Keep]

[Added area: (230) Roads of Cormanthor]

[Added area: (79) The Ant Farm]

[Added area: (58) Lake Skeldrach Island]

[Added area: (68) The Waterdeep Coast Road]

[Added area: (61) The Citadel]

[Added area: (249) The Abandoned Monastery]

[Added area: (215) The Neverwinter Wood Beta]

[Added area: (270) Swift-Steel Company]

[Added area: (28) The Great Harbor of Waterdeep]

[Added area: (117) Cityguard's Armoury]

[Added area: (172) Caravan Trail to the Ten Towns]

[Added area: (197) Cursed Cemetery]

[Added area: (52) Ghore - City of Trolls]

[Added area: (190) Trollbark]

[Added area: (212) Soulprison of Bhaal]

[Added area: (115) The Plane of Fire Part Two]

[Added area: (7) Ako Village]

[Added area: (340) Grid-Hills-Ashrumite]

[Added area: (162) Calimport, the Sewers]

[Added area: (22) The Elemental Groves]

[Added area: (207) The Druid Forest]

[Added area: (307) The Trade Way]

[Added area: (321) The Rat Hills]

[Added area: (128) Bryn Shander]

[Added area: (27) Labyrinth of No Return]

[Added area: (131) The Basin Wastes]

[Added area: (129) The Eastway]
[Warning: map:findAreaId(areaname) - nil areaname]
[14768 does not exist]

[Added area: (306) Darklake]

[Added area: (333) Grid-Forest-Bloodtusk]

[Added area: (141) The Orcish Hall of Plunder]

[Added area: (312) Wormwrithings]

[Added area: (320) Elg'cahl Niar]

[Added area: (142) Rurrgr T'ohrr]

[Added area: (184) The Curse of Newhaven]

[Added area: (218) Skullport, Port of Shadows]

[Added area: (213) The Golem Forge]

[Added area: (178) Arnd'ir]

[Added area: (337) Grid-Arctic-MH2]

[Added area: (233) Silverymoon, Gem of the North]

[Added area: (302) The Dark Dominion]

[Added area: (260) Bloodtusk]

[Added area: (65) Talthalra Haszakkin]

[Added area: (324) Evermeet- Main Road]

[Added area: (123) Myrloch Vale]

[Added area: (150) Rogath Swamp]

[Added area: (186) The Llyrath Forest]

[Added area: (201) Hulburg]

[Added area: (217) The Drider Cavern]

[Added area: (316) The Fortress of the Dragon Cult]

[Added area: (171) The Darktree]

[Added area: (204) The Para-Elemental Plane of Ice]

[Added area: (24) The Underworld]

[Added area: (273) Skerttd-Gul]

[Added area: (93) New Nhavan Island]

[Added area: (297) Evermeet- Hidden Mine]

[Added area: (185) The Curse of Newhaven_II]

[Added area: (327) Evermeet- Ancient Forest-1]

[Added area: (322) Mithril Hall Palace]

[Added area: (170) Thunderhead Peak]

[Added area: (132) Gloomhaven]

[Added area: (248) The Mirar Ferry]

[Added area: (81) Earth Plane]

[Added area: (328) Evermeet- Misc. Rooms/Mobs]

[Added area: (267) The Brain Stem Tunnel]

[Added area: (120) Troll King]

[Added area: (263) Jotunheim]

[Added area: (198) The Plane of Smoke]

[Added area: (254) The Ruins of Undermountain I]

[Added area: (13) The Conquered Village]

[Added area: (87) Ashstone Refugee Camp]

[Added area: (155) Demiplane of Artimus Nevarlith]

[Added area: (5) Kobold Settlement
]
[internalid error in room: 81127]
5

"X"

"Likely to crash"

81127

5

"5"

"Kobold Settlement
"





< 598h/598H 171v/171V P: std (AFK) > 
@map info
                      Keprum Vhai'rels Design    0/  14  rooms, (  0.00% )
                                      Hulburg    2/ 474  rooms, (  0.42% )
                   Evermeet- Misc. Rooms/Mobs    8/  12  rooms, ( 66.67% )
                                   Muspelhiem    0/ 440  rooms, (  0.00% )
                        Ashstone Refugee Camp    4/   4  rooms, ( 100.00% )
                       The Northern High Road   34/  34  rooms, ( 100.00% )
                      Evermeet- Serene Forest    0/ 100  rooms, (  0.00% )
                         Guildhalls-Triterium    0/  26  rooms, (  0.00% )
                        The Swamps of Meilech    0/ 138  rooms, (  0.00% )
                       Ghore - City of Trolls  243/ 381  rooms, ( 63.78% )
                The Ruins of Undermountain II    0/ 416  rooms, (  0.00% )
                   Skullport, Port of Shadows   88/1455  rooms, (  6.05% )
                   Evermeet- Ancient Forest-1    2/ 100  rooms, (  2.00% )
                          The Elder Anthology    0/  39  rooms, (  0.00% )
                       The Temple of the Moon    0/  70  rooms, (  0.00% )
                        UnderDark River Ruins    0/  95  rooms, (  0.00% )
                           Dragonsfall Forest   12/  12  rooms, ( 100.00% )
                                   Grid-UD-GH    0/ 189  rooms, (  0.00% )
                                 Pirate Isles    0/ 101  rooms, (  0.00% )
                                    Jotunheim    3/ 250  rooms, (  1.20% )
                         Grid-Hills-Bloodtusk    0/ 183  rooms, (  0.00% )
                 Southern Waterdeep Main City  120/ 200  rooms, ( 60.00% )
                       The Temple of Baphomet    0/  65  rooms, (  0.00% )
                                The Dusk Road  238/ 256  rooms, ( 92.97% )
                        The Sunken Slave City    0/  86  rooms, (  0.00% )
                                    Bloodtusk   12/ 287  rooms, (  4.18% )
                                The Blackwood    0/  37  rooms, (  0.00% )
                The Dwarven Mining Settlement   92/ 118  rooms, ( 77.97% )
                           Farm of the Undead   67/  88  rooms, ( 76.14% )
                                  Water Plane    0/ 193  rooms, (  0.00% )
              Evermeet- East Coast Road North    0/ 102  rooms, (  0.00% )
                             The Pit of Souls    0/  22  rooms, (  0.00% )
                          The Tunnel of Dread    0/ 158  rooms, (  0.00% )
                                Castle Drulak    0/ 297  rooms, (  0.00% )
                           The Ethereal Plane    0/ 127  rooms, (  0.00% )
                  The Temple of Blipdoolpoolp    0/  23  rooms, (  0.00% )
                               Choking Palace    0/ 167  rooms, (  0.00% )
            Pride of the Sabertooth Guildhall    0/   7  rooms, (  0.00% )
                        Faang - City of Ogres  502/ 685  rooms, ( 73.28% )
                 The Necromancer's Laboratory    0/  98  rooms, (  0.00% )
                   The Plane of Fire Part One    0/ 105  rooms, (  0.00% )
                       Calimport Palace Vault    0/  99  rooms, (  0.00% )
                         Viperstongue Outpost   27/  29  rooms, ( 93.10% )
                          The Chionthar Ferry    0/   2  rooms, (  0.00% )
                            The Trader's Road  105/ 199  rooms, ( 52.76% )
                               Lava Tubes One  118/ 151  rooms, ( 78.15% )
                              Calimshan Beach   97/ 100  rooms, ( 97.00% )
                               The Underworld   54/ 213  rooms, ( 25.35% )
                    Tower of High Sorcery One    4/  57  rooms, (  7.02% )
                Stronghold of Trahern Oakvale    0/  91  rooms, (  0.00% )
                      Village of Split Shield   93/  98  rooms, ( 94.90% )
                                 Druids Grove    0/  32  rooms, (  0.00% )
                      The Guilds of Waterdeep   14/  30  rooms, ( 46.67% )
                              Grid-UD-Ixarkon    0/ 183  rooms, (  0.00% )
                         Barbarian Encampment    0/  32  rooms, (  0.00% )
                                 Myth Unnohyr    0/  95  rooms, (  0.00% )
                           Ashstone Keep Road    0/  96  rooms, (  0.00% )
                          Swift-Steel Company   85/  95  rooms, ( 89.47% )
    The Nine Hells - Avernus - Bronze Citadel    0/ 167  rooms, (  0.00% )
                Hyssk Ship/Dragon Turtle Path    0/   4  rooms, (  0.00% )
                    The Underdark Trade Route    0/ 151  rooms, (  0.00% )
                              Southern Forest   20/ 174  rooms, ( 11.49% )
                                The Labyrinth    0/ 495  rooms, (  0.00% )
               Caravan Trail to the Ten Towns   87/  87  rooms, ( 100.00% )
                            Herd Island Chasm    0/  19  rooms, (  0.00% )
                                 Bryn Shander  524/ 524  rooms, ( 100.00% )
                              The Ancient Oak    0/  12  rooms, (  0.00% )
                                  Skerttd-Gul   60/ 359  rooms, ( 16.71% )
                        New Moonshae Island I    0/ 169  rooms, (  0.00% )
                        Desert City of Nizari  167/ 187  rooms, ( 89.30% )
                                 Faerie Realm  110/ 197  rooms, ( 55.84% )
                 Northern Waterdeep Main City  127/ 185  rooms, ( 68.65% )
                               The Dread Mist    0/  82  rooms, (  0.00% )
                           Dragonspear Castle    0/ 395  rooms, (  0.00% )
                  Central Waterdeep Main City  102/ 147  rooms, ( 69.39% )
                    The Lost Treasure of Zaor    0/  35  rooms, (  0.00% )
                    Myth Drannor-Central City    0/ 186  rooms, (  0.00% )
                               The Ice Prison    0/  68  rooms, (  0.00% )
                 Alterian Region - Wilderness   99/  99  rooms, ( 100.00% )
                        Grid-Hills-Bloodtusk2    0/ 183  rooms, (  0.00% )
                              The Blood Bayou    0/  39  rooms, (  0.00% )
                    Cloud Realms of Arlurrium    0/ 254  rooms, (  0.00% )
           Evermeet- Road to Elven Settlement    0/  72  rooms, (  0.00% )
                    Tower of the Elementalist    0/ 130  rooms, (  0.00% )
                         Calimport, the Docks   89/  90  rooms, ( 98.89% )
                    The Plane of Air Part One    0/ 124  rooms, (  0.00% )
              The Fortress of the Dragon Cult   31/  37  rooms, ( 83.78% )
                           The Llyrath Forest   34/  83  rooms, ( 40.96% )
                     The Temple of Ghaunadaur    0/ 186  rooms, (  0.00% )
                              Fire Giant Lair    0/  66  rooms, (  0.00% )
                Ashgorrock, the Gargoyle City    0/  97  rooms, (  0.00% )
                           The Western Realms  250/ 271  rooms, ( 92.25% )
                            New Nhavan Island   31/  99  rooms, ( 31.31% )
                             Wilderness Roads   58/  60  rooms, ( 96.67% )
                                  Ako Village   56/  56  rooms, ( 100.00% )
                            Spiderhaunt Woods    3/ 157  rooms, (  1.91% )
                  The Reaching Woods - Part I  170/ 170  rooms, ( 100.00% )
                              Scornubel Ferry    0/   6  rooms, (  0.00% )
                  Leuthilspar - City of Elves  221/ 283  rooms, ( 78.09% )
                   The High Road - Side Areas    0/  15  rooms, (  0.00% )
                          The Greycloak Hills  185/ 191  rooms, ( 96.86% )
                             The Druid Forest   56/  58  rooms, ( 96.55% )
                       The Jungles of Ssrynss    0/ 134  rooms, (  0.00% )
                       Grid-Desert-Calimport2    0/ 183  rooms, (  0.00% )
                           The Comarian Mines    0/ 433  rooms, (  0.00% )
                                The Trade Way  201/ 282  rooms, ( 71.28% )
                                    Trollbark  172/ 298  rooms, ( 57.72% )
                                Elg'cahl Niar   98/  98  rooms, ( 100.00% )
                                   Wyllowwood    0/ 291  rooms, (  0.00% )
                            Alabaster Caverns    0/ 108  rooms, (  0.00% )
                          Roads of Cormanthor   94/  99  rooms, ( 94.95% )
                    Calimport, The Sea Sprite    0/   4  rooms, (  0.00% )
                             The Shadow Swamp    0/  45  rooms, (  0.00% )
                      The Sewers of Waterdeep    0/ 105  rooms, (  0.00% )
                   The Northern Caravan Trail   64/  68  rooms, ( 94.12% )
                        Calimport, the Sewers   79/  79  rooms, ( 100.00% )
                             Valley of Crushk   77/  89  rooms, ( 86.52% )
                        The Brain Stem Tunnel   19/ 185  rooms, ( 10.27% )
                          Ruins of Yath Oloth    0/ 278  rooms, (  0.00% )
                        Evermeet- Hidden Mine   95/ 132  rooms, ( 71.97% )
                              The Golem Forge  108/ 172  rooms, ( 62.79% )
               Mithril Hall - City of Dwarves  262/ 291  rooms, ( 90.03% )
                          Great Northern Road   75/  76  rooms, ( 98.68% )
                      The Fog Enshrouded Wood  203/ 205  rooms, ( 99.02% )
                                Amenth'G'narr    0/  83  rooms, (  0.00% )
                 Pirate Ship, Captain's Fancy    0/   3  rooms, (  0.00% )
                     The Realms Master - Ship    0/  36  rooms, (  0.00% )
                    Myth Drannor-Western City    0/ 199  rooms, (  0.00% )
                  Guildhalls - Warder's Vault    0/   1  rooms, (  0.00% )
                  The Temple of Twisted Flesh    0/  94  rooms, (  0.00% )
                                  Grid-UD-Mir    0/ 183  rooms, (  0.00% )
                    Evermeet- Scorched Forest    0/  28  rooms, (  0.00% )
                          The Tower of Kenjin    0/  23  rooms, (  0.00% )
                        Lake Skeldrach Island   96/  96  rooms, ( 100.00% )
                          The_Wildland_Trails   94/  99  rooms, ( 94.95% )
                                  Earth Plane   10/ 161  rooms, (  6.21% )
                        The Tarsellian Forest   13/ 205  rooms, (  6.34% )
                       The Valley of Graydawn    0/  92  rooms, (  0.00% )
                   The Roads of the Heartland  253/ 358  rooms, ( 70.67% )
                              The Ruined Keep    0/  82  rooms, (  0.00% )
                                 Lizard Marsh    0/ 188  rooms, (  0.00% )
      The Floating Fortress of Izan Frosteyes    0/  87  rooms, (  0.00% )
                          Calimport, the City  261/ 308  rooms, ( 84.74% )
                   Beluir - City of Halflings  337/ 413  rooms, ( 81.60% )
                           Kobold Settlement
    0/  99  rooms, (  0.00% )
                                 The Darktree    5/ 176  rooms, (  2.84% )
                        The Curse of Newhaven   18/  97  rooms, ( 18.56% )
                                    Talenrock    0/  69  rooms, (  0.00% )
                 IceCrag Castle - Lower Level    0/ 171  rooms, (  0.00% )
                  Alterian Region - Mountains   95/ 108  rooms, ( 87.96% )
                     Hive of the Manscorpions    0/ 188  rooms, (  0.00% )
                     Grid-Forest-Leuthilspar2    0/ 183  rooms, (  0.00% )
                   The Orcish Hall of Plunder   43/  81  rooms, ( 53.09% )
                 Jungle Village of the Batiri    0/  90  rooms, (  0.00% )
                                  Dark Forest    0/ 147  rooms, (  0.00% )
                   Evermeet- Elven Settlement    0/  99  rooms, (  0.00% )
                         The Minotaur Outpost    0/  93  rooms, (  0.00% )
                                   Gloomhaven   14/ 262  rooms, (  5.34% )
                Tiamat - The Pillar of Skulls    0/  50  rooms, (  0.00% )
                            The Dark Dominion   53/ 100  rooms, ( 53.00% )
                                   God Rooms
    0/   2  rooms, (  0.00% )
                                The Nightwood    0/  49  rooms, (  0.00% )
                                     Ashstone    0/ 385  rooms, (  0.00% )
                                Klauthen Vale    0/  43  rooms, (  0.00% )
                             The Basin Wastes    4/ 273  rooms, (  1.47% )
                                      Arnd'ir   24/ 104  rooms, ( 23.08% )
               Lost Library of the Seer Kings    0/  87  rooms, (  0.00% )
                              The Troll Hills   48/ 150  rooms, ( 32.00% )
                        The New Trackless Sea    0/   3  rooms, (  0.00% )
                   Neshkal - The Dragon Trail    0/  95  rooms, (  0.00% )
                                Hulburg Trail    0/ 199  rooms, (  0.00% )
                   The Keep of Finn McCumhail    0/  88  rooms, (  0.00% )
                                 Rogath Swamp   37/  77  rooms, ( 48.05% )
         The Headquarters of the Twisted Rune    0/ 117  rooms, (  0.00% )
                       The Marching Mountains    0/  40  rooms, (  0.00% )
                               Ixarkon Prison    0/ 121  rooms, (  0.00% )
                              Grid-Arctic-MH2  147/ 183  rooms, ( 80.33% )
                           The Bandit Hideout    0/  95  rooms, (  0.00% )
                     The Jungle City of Hyssk    0/ 343  rooms, (  0.00% )
                             Mosswood Village    0/ 180  rooms, (  0.00% )
                          Cityguard's Armoury   10/  10  rooms, ( 100.00% )
                               Grid-Arctic-GN    0/ 183  rooms, (  0.00% )
                       Grid-Desert-Calimport1    0/ 183  rooms, (  0.00% )
              The Para-Elemental Plane of Ice   29/ 153  rooms, ( 18.95% )
                        Baldur's Gate - Docks   91/  93  rooms, ( 97.85% )
                           The Luskan Outpost    0/  65  rooms, (  0.00% )
                 The Elemental Plane of Magma    0/ 140  rooms, (  0.00% )
               Deep Within the Toadsquat Mnts    0/ 216  rooms, (  0.00% )
                             Abandoned Temple    0/  47  rooms, (  0.00% )
                                  The Citadel  173/ 200  rooms, ( 86.50% )
              The Plane of Fire -Planar Grid-    0/ 122  rooms, (  0.00% )
                     The River Trail to Hyssk    0/  91  rooms, (  0.00% )
                             Thunderhead Peak    1/  56  rooms, (  1.79% )
                 The Astral Plane - Main Grid    0/ 127  rooms, (  0.00% )
                            Grid-Forest-Faang    0/ 183  rooms, (  0.00% )
                                     Darklake  315/ 403  rooms, ( 78.16% )
                   Valkurian Blades Guildhall    0/  41  rooms, (  0.00% )
                          The Scardale Sewers    0/  49  rooms, (  0.00% )
                              the Deep Jungle    0/  67  rooms, (  0.00% )
                          Seelie Faerie Court    0/  58  rooms, (  0.00% )
                              Crystal Caverns    0/  61  rooms, (  0.00% )
                   The Plane of Fire Part Two   40/ 141  rooms, ( 28.37% )
                          Fire Giants Village    0/ 154  rooms, (  0.00% )
                           Imphras Guild Hall    0/  13  rooms, (  0.00% )
                                  The Way Inn    0/  63  rooms, (  0.00% )
                              Ophidian Jungle    0/  96  rooms, (  0.00% )
                The Cursed City of West Falls    0/  92  rooms, (  0.00% )
                                Seaweed Tribe    0/  33  rooms, (  0.00% )
                        Calimport, the Palace   59/  61  rooms, ( 96.72% )
                                  Settlestone    0/  89  rooms, (  0.00% )
                             The Elder Forest    0/  97  rooms, (  0.00% )
                                Ancient Mines    0/  99  rooms, (  0.00% )
                                   Troll King   27/ 100  rooms, ( 27.00% )
                          The Adamantite Mine    0/  91  rooms, (  0.00% )
                         The Gloomhaven Barge    0/   2  rooms, (  0.00% )
                                Veldrin Z'har    0/  69  rooms, (  0.00% )
                              The Rauvin Ride    0/  99  rooms, (  0.00% )
                      Grid-Forest-Leuthilspar    0/ 183  rooms, (  0.00% )
                   The Onyx Tower of Illusion    0/  44  rooms, (  0.00% )
                              Darkhold Castle    0/ 166  rooms, (  0.00% )
                                Grid-Hills-GN    0/ 183  rooms, (  0.00% )
                                The Stump Bog    0/  91  rooms, (  0.00% )
                                   IX Curtain    0/  40  rooms, (  0.00% )
                         A Halruaan Airship 2    0/   8  rooms, (  0.00% )
                              The Stag Forest    0/  98  rooms, (  0.00% )
                                The Derro Pit    0/  87  rooms, (  0.00% )
                       Evermeet- Rogue's Lair    0/ 102  rooms, (  0.00% )
                             Waterdeep Trails   21/  21  rooms, ( 100.00% )
                             The Evermoor Way    1/ 100  rooms, (  1.00% )
                        The Conquered Village    4/  79  rooms, (  5.06% )
                 The Ruins of Undermountain I   21/ 422  rooms, (  4.98% )
                          Soulprison of Bhaal   70/  70  rooms, ( 100.00% )
                  Baldur's Gate - Wave Dancer    0/   5  rooms, (  0.00% )
                                The Evermoors  106/ 128  rooms, ( 82.81% )
                                    Scornubel  454/ 493  rooms, ( 92.09% )
                     The Waterdeep Coast Road   79/  86  rooms, ( 91.86% )
                             Nightwood Border    0/  31  rooms, (  0.00% )
                       Labyrinth of No Return  171/ 292  rooms, ( 58.56% )
                     The Northern High Road-2   50/  50  rooms, ( 100.00% )
                                Rurrgr T'ohrr    2/  90  rooms, (  2.22% )
                              The Mirar Ferry    1/   5  rooms, ( 20.00% )
                                The Dark Gate    0/  10  rooms, (  0.00% )
               Demiplane of Artimus Nevarlith    7/ 196  rooms, (  3.57% )
                        Caves of Mt. Skelenak  100/ 141  rooms, ( 70.92% )
                            Ashrumite_Village  119/ 147  rooms, ( 80.95% )
                         A Halruaan Airship 1    0/ 153  rooms, (  0.00% )
                            Grid-Jungle-Hyssk    0/ 183  rooms, (  0.00% )
                                 Myrloch Vale   44/ 178  rooms, ( 24.72% )
                           Menden-on-the-Deep   58/  69  rooms, ( 84.06% )
                              RP ZONE - Annam    0/   6  rooms, (  0.00% )
                             Illithid Enclave    0/  83  rooms, (  0.00% )
                     Calimport, The Barracuda    0/   4  rooms, (  0.00% )
                                    Havenport  121/ 126  rooms, ( 96.03% )
                      Lair of the Deep Dragon    0/ 100  rooms, (  0.00% )
                            The Sylvan Glades    0/ 337  rooms, (  0.00% )
                    Myth Drannor-Eastern City    0/ 198  rooms, (  0.00% )
                                    Ogre Lair    0/  99  rooms, (  0.00% )
                            The Forest of Mir    0/  89  rooms, (  0.00% )
                The Great Harbor of Waterdeep  121/ 121  rooms, ( 100.00% )
                        Keprum Vhai'rels Test    0/  14  rooms, (  0.00% )
                            Underdark Tunnels    0/  98  rooms, (  0.00% )
                         Lake Skeldrach Shore  155/ 156  rooms, ( 99.36% )
                               Menzoberranzan    0/ 551  rooms, (  0.00% )
                                The Rat Hills  148/ 148  rooms, ( 100.00% )
                              Randars Hideout    0/  45  rooms, (  0.00% )
                     Dobluth Kyor - Main City    0/ 191  rooms, (  0.00% )
                            Tiamat - The Lair    0/  58  rooms, (  0.00% )
                                 New Cavecity   16/  96  rooms, ( 16.67% )
                               Kobold Caverns    0/  81  rooms, (  0.00% )
                          Evermeet- Main Road   37/ 109  rooms, ( 33.94% )
                                Wormwrithings  187/ 187  rooms, ( 100.00% )
                               Grid-Arctic-MH    0/ 183  rooms, (  0.00% )
                         A'Quarthus Velg'Larn    0/ 126  rooms, (  0.00% )
                              Cursed Cemetery   37/  61  rooms, ( 60.66% )
                           The Ashstone Trail   42/  69  rooms, ( 60.87% )
                           The Plane of Smoke   17/ 105  rooms, ( 16.19% )
                         The Calimshan Desert  524/ 538  rooms, ( 97.40% )
                        Grid-Forest-Bloodtusk  133/ 184  rooms, ( 72.28% )
                                 The Lurkwood   68/  91  rooms, ( 74.73% )
                                     Scardale    0/ 189  rooms, (  0.00% )
                    The Defense of Longhollow    0/ 100  rooms, (  0.00% )
              Evermeet- West Coast Road North    0/  13  rooms, (  0.00% )
                     The Nine Hells - Avernus    0/ 289  rooms, (  0.00% )
                         The Elemental Groves   74/ 165  rooms, ( 44.85% )
                    Baldur's Gate - Main City  583/ 610  rooms, ( 95.57% )
                                    Yggdrasil    0/   9  rooms, (  0.00% )
                                 Zhentil Keep  246/ 381  rooms, ( 64.57% )
                     The Curse of Newhaven_II   37/  49  rooms, ( 75.51% )
                                 The Ant Farm  101/ 102  rooms, ( 99.02% )
                          Mithril Hall Palace   69/  99  rooms, ( 69.70% )
                               Grid-Forest-WD    0/ 183  rooms, (  0.00% )
                Silverymoon, Gem of the North  109/ 753  rooms, ( 14.48% )
                               IceCrag Castle  205/ 219  rooms, ( 93.61% )
                 The Roads of the Heartland 2   83/ 105  rooms, ( 79.05% )
                           Grid-Jungle-Hyssk2    0/ 183  rooms, (  0.00% )
                         Grid-Hills-Ashrumite    1/ 183  rooms, (  0.55% )
                                  The Eastway   96/  96  rooms, ( 100.00% )
                          Temple of Dumathoin    0/ 196  rooms, (  0.00% )
                  The Sedawi Mountain Village  167/ 167  rooms, ( 100.00% )
                Tooth and Maw - Grilled Grawl    0/  19  rooms, (  0.00% )
                                Grid-Hills-WD    0/ 183  rooms, (  0.00% )
                             The Spirit Raven    0/  28  rooms, (  0.00% )
              The Dragonspine Mountains Trail    0/ 189  rooms, (  0.00% )
                      The Abandoned Monastery   16/ 106  rooms, ( 15.09% )
                            The Drider Cavern   19/  76  rooms, ( 25.00% )
                          Talthalra Haszakkin  121/ 281  rooms, ( 43.06% )
                Ixarkon - City of Mindflayers    0/ 201  rooms, (  0.00% )
                    The Neverwinter Wood Beta  154/ 158  rooms, ( 97.47% )
                       The Silver Lady - Ship    0/  36  rooms, (  0.00% )
                               Griffon's Nest  108/ 182  rooms, ( 59.34% )
                                    Mistywood  195/ 197  rooms, ( 98.98% )
                 Ribcage: Gate Town to Baator    0/ 142  rooms, (  0.00% )
                The Astral Plane - Side Areas    0/  59  rooms, (  0.00% )
                                        Trade    3/   3  rooms, ( 100.00% )
                                 Evermeet Bay    0/ 147  rooms, (  0.00% )
                             The Lost Pyramid    0/  84  rooms, (  0.00% )
                  Rimi Greatoath dagger quest    0/   2  rooms, (  0.00% )

             found 317/317 included areas      13649/45002 rooms  ( 30.33% )

**Comment by Nyyrazzilyss** [comment]
Should be fixed 09/23 dev

**Comment by Hibbidy** [comment]
[Added area: (5) Kobold Settlement
]
[internalid error in room: 72774]
5

"Kobold Settlement
"

nil

"X"

"Likely to crash"

72774

5

"5"

"Kobold Settlement
"

nil


Lilabipple GCC: 'we need more on for zone'

< 598h/598H 171v/171V P: std >

**Comment by Nyyrazzilyss** [comment]
fixed
