### ISSUE TITLE
Hide - After selecting a room on the map to move an unexpected followers command un-hide me

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#6]
Log:

< 162h/975H 125v/130V P: std >

You stop trying to hide.

   404/404   HP  105/105  MV   P  + Kovat

< 162h/975H 126v/130V P: std >

**Comment by Nyyrazzilyss** [comment]
This has been (hopefully) corrected in the latest dev. The followers command won't be sent if hidden, it's better at recognizing if a rogue is hidden, and it's also been posted for Shev to request the followers command not break hide.
