### ISSUE TITLE
Room change/flee gagged

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#60]
Mulgate Avenue
Exits: -N -E -S -W     [49066] 
A copper coin.
A ruby-throated humming bird hovers here feeding.
A robin searches for food here.

< 387h/598H 167v/171V P: std >

A Noble's Home
Exits: -W              [49068] 
Corpse of a human noble is lying here.
An ornate gilded metal cage hangs here.
[2] A gilded key rests here attracting attention.
A copper coin.
A human noble stands here haughtily.

< 387h/598H 166v/171V P: std >

bs noble
trip

< 388h/598H 169v/171V P: std >

A human noble makes a strange sound, as you place a glittering dagger of the Nurturing Matriarch in 
his back.
A human noble makes a strange sound, as you place a red dragon fanged dagger in his back.

< 389h/598H 169v/171V T: Nonog TC: few wounds E: noble EC: few wounds EP: std P: std > 
You strike at a human noble's belly, causing him to double over in agony and drop to his knees!
You attack a human noble, landing three hits.
A human noble attacks you, landing a single hit.

< 343h/598H 171v/171V T: Nonog TC: few wounds E: noble EC: nasty wounds EP: knl P: std >

But they're already on the ground!

< 343h/598H 171v/171V T: Nonog TC: few wounds E: noble EC: nasty wounds EP: knl P: std >

< 343h/598H 170v/171V P: std > 
A wagon rumbles along nearby, wooden wheels clattering on the stones.

< 343h/598H 171v/171V P: std > 

A robin searches a small patch of grass for worms.

< 375h/598H 171v/171V P: std > 
l
Mulgate Avenue
Exits: -N -E -S -W     [49066] 
A copper coin.
A ruby-throated humming bird hovers here feeding.
A robin searches for food here.

< 383h/598H 171v/171V P: std >

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
