### ISSUE TITLE
During "Reorder" on character list screen...

### ISSUE THREAD

**Issue by Gogk** [Nyyrazzilyss/NyyLIB#62]
I went to reorder my characters and I believe that I accidentally logged out and instead of using my log in and pword, I think I tried to log in with one of my characters. Now on my character list, there's 3 of the same character and I can't remove the two extra ones.

**Comment by Nyyrazzilyss** [comment]
This would be a mud related error, not script error. You'll want to repost this on the toril github: 

https://github.com/torilmud/issues
