### ISSUE TITLE
Gag issue - The room I land in is not fully being displayed when i "w;cr dragon;escape e"

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#64]
**@version**
Script version: 10/4/2017 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

Log with issue in **bold:**

< 814h/814H 131v/131V P: std > 
Afu group-says '<2>'
< 814h/814H 131v/131V P: std > 
A harmonious combination of notes from Hirple soothes your wounds.

< 814h/814H 131v/131V P: std > 
Erarim gets a necklace of copper dragon scales from his portable hole.
Beern sits down in a comfortable spot.

< 814h/814H 131v/131V P: std > 
Erarim recites a necklace of copper dragon scales while looking at Erarim.

< 814h/814H 131v/131V P: std > 

Beern takes out his holy symbol and begins praying intently.
Afu group-says '<1>'
< 814h/814H 131v/131V P: std > 

Afu prowls west.

< 814h/814H 131v/131V P: std > 
w;bs dragon;escape e
A Cavernous Moss Covered Lair
   Lush moist moss of the deepest green covers nearly every surface in this
entire cavern. The same kind of jagged ironite and obsidian deposits found
in the spiral shaped shaft can be seen reflecting the flashes of light which
sporadically pulse through this entire lair and its adjoined tunnel entrance.
A large series of boulders, worn and etched smooth over the years encompass
a huge depression in the vegitated ground directly in the center of the 
cavern. Towards the east, the humid forest-like tunnel continues.
Exits: - East          [75711] 
A pool of blood covers the ground.
Afu Eat Babies (RP) (Troll) stands here, fighting an ancient green dragon.
An ancient green dragon stands here, fighting Afu. (x2)
The green dragon consort stands here, fighting Afu.
Hirple sneaks in from the east.
Jibbi enters from the east.

< 814h/814H 129v/131V P: std >

Your wonderful glittering dagger glows brightly as your body starts to flicker, in
and out of visibility! You spring to the side, dodging an ancient green dragon's attack.
the holy blessing of Yondalla has taken hold upon you! an ancient green dragon cries
out as you plunge your dagger perfectly into the center of his back. You grin
as your dagger draws the very lifeforce out of him.
Erarim enters from the east.

< 1014h/814H 129v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 

Azralek enters from the east.
Madeodrormerat enters from the east.

< 1014h/814H 129v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 
Lilabipple group-says 'go w'

< 1014h/814H 129v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 

Misi enters from the east.

< 1014h/814H 130v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 
Adriork flies in from the east.

< 1014h/814H 130v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 

[Madeodrormerat : the mystical circlet of the coiled serpent]
Lulaz enters from the east.
Hammen enters from the east.
Awlan enters from the east.

< 1014h/814H 130v/131V T: Afu TC: small wounds E: green EC: few scratches EP: std P: std > 
< 1014h/814H 131v/131V T: Afu TC: small wounds E: green EC: small wounds EP: std P: std > 
Lulaz attempts to flee.
Lulaz leaves east.
Tutenef enters from the east.

< 1014h/814H 131v/131V T: Afu TC: small wounds E: green EC: small wounds EP: std P: std > 
Tutenef's eyes glaze as he is overtaken by a berserker fury!  All else
is forgotten as he visciously and repeatedly smashes the mighty scepter of valhalla
into an ancient green dragon, attempting to utterly destroy him!
Breathing heavily and covered in blood, Tutenef spins to a halt in the
center of the fray, pausing for a moment to gather his strength.
Your attack glances harmlessly off of an ancient green dragon's scales!
Your wonderful glittering dagger glows brightly as your body starts to flicker, in
and out of visibility! You spring to the side, dodging an ancient green dragon's attack.
the holy blessing of Yondalla has taken hold upon you! an ancient green dragon cries
out as you plunge your dagger perfectly into the center of his back. You grin
as your dagger draws the very lifeforce out of him.
Your attack glances harmlessly off of an ancient green dragon's scales!
An ancient green dragon lunges towards Tutenef and bites him savagely!
Tutenef is stunned!
An ancient green dragon flings his mighty tail into Afu with tremendous force!
Afu is slammed down on the ground!
The green dragon consort slashes Afu brutally with a fearsome claw!
Lilabipple group-says 'kill moar dragons'

< 1214h/814H 131v/131V T: Afu TC: pretty hurt E: green EC: few wounds EP: std P: std > 
Lulaz enters from the east.

< 1214h/814H 131v/131V T: Afu TC: pretty hurt E: green EC: few wounds EP: std P: std > 
Hirple attempts to escape.
Hirple leaves east.

**< 1214h/814H 131v/131V T: Afu TC: pretty hurt E: green EC: few wounds EP: std P: std > 
Within a Broad Moss Covered Tunnel
   A huge broad cylindrical tunnel in the ground continues down the tunnels
with jagged walls of obsidian, stone and ironite. Moss covers nearly every
surface on the ground here, most of it facing towards the shaft of the tunnel.
Hot moist air blasts around you, travelling quickly through the uneven surfaces
of the tunnel walls. On the floor of this cavern, the wet muddy ground has been
trampled by feet of incredible sizes. Towards the east, the tunnel heads toward
< 1214h/814H 129v/131V P: std >**

Adriork flies in from the west.
You don't see them here!

**Comment by Nyyrazzilyss** [comment]
12/16/18 dev
