### ISSUE TITLE
Leveling a ranger - currently level 27 - loop issue

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#65]
This is after i recently logged in and doesn't happen on my 50 ranger:

< 384h/384H 121v/121V T: Fakitte TC: excellent E: young EC: nasty wounds EP: rcl P: std > 
You don't have any more spells available at that circle! [Casting: bof (Blades of Fire)]
Momippiruppol starts casting an offensive spell called 'Earth Stones'

< 384h/384H 121v/121V T: Fakitte TC: excellent E: young EC: nasty wounds EP: rcl P: std > 
You don't have any more spells available at that circle! [Casting: bof (Blades of Fire)]

< 384h/384H 121v/121V T: Fakitte TC: excellent E: young EC: nasty wounds EP: rcl P: std > 

[armor_splinter]
You strike the weak spots in a young man's armor, leaving him vulnerable.

< 384h/384H 121v/121V T: Fakitte TC: excellent E: young EC: nasty wounds EP: rcl P: std >

You don't have any more spells available at that circle! [Casting: bof (Blades of Fire)]

< 384h/384H 121v/121V T: Fakitte TC: excellent E: young EC: nasty wounds EP: rcl P: std > 
You don't have any more spells available at that circle! [Casting: bof (Blades of Fire)]

**Comment by Nyyrazzilyss** [comment]
'display slots' hasn't been used in this prompt. In the short term, just type 'display slots' to enable it.
Next dev posted has this changed to be force enabled.
