### ISSUE TITLE
Chat Window: Clickable URLs

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#66]
Found on mudlet forums if helpful to anyone:  the below works from the main window, at least for webpages - i haven't tested ftp, etc - also does not work from the chat window, which would probably be ideal -    

Trigger:
`\b(?:(?:(?:https?|ftp|telnet)://[\w\d:#@%/;$()~_?\+\-=&amp;]+|www|ftp)(?:\.[\w\d:#@%/;$()~_?\+\-=&amp;]+)+|[\w\d._%+\-]+@[\w\d.\-]+\.[\w]{2,4})\b`

Script:

for i,v in ipairs(matches) do
  selectString(matches[i], 1)
  setLink([[openUrl("]]..matches[i]..[[")]], matches[i])
end

**Comment by Nyyrazzilyss** [comment]
added to dev 10/14/17

**Comment by Nyyrazzilyss** [comment]
"also does not work from the chat window, which would probably be ideal"

**Comment by Nyyrazzilyss** [comment]
02/11c dev
