### ISSUE TITLE
Stop Train

### ISSUE THREAD

**Issue by sekfarok** [Nyyrazzilyss/NyyLIB#67]
< 461h/707H 91v/111V |0|0|1|1|1| P: std > 
A human noble is in an excellent condition. (Medium)

< 462h/707H 92v/111V |0|0|1|1|1| P: std > 
Pardon?

After glancing, it seems cant to find the correct command. I got auto hunter's mark on.

**Comment by Nyyrazzilyss** [comment]
The command to terminate the train was changed from stoptrain to @stoptrain
