### ISSUE TITLE
Ranger Buttons Checked but skills unused.

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#71]
for some reason the blade of fire circle just dosnt use the entire tier sits unused. restarted and everything i know to do. i dont touch your script so i dont know what the cause is.

**Comment by i982** [comment]
further inspection shows none of the skills are being used either. evis blades of fire electric discharge twin strikes armor splinter blade storm and sweeping strikes none of them are firing.

**Comment by Nyyrazzilyss** [comment]
Version?

**Comment by Nyyrazzilyss** [comment]
I'm not having any problems myself with ranger, and no-one else is reporting major issues. Closing this ticket.

If the problem persists, make sure you're using the current version posted and open a new ticket. Include the version being used with it, and as much information as possible.
