### ISSUE TITLE
@help autoloot

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#72]
I couldnt get the hyphens to justify/align in the "Usage:" section -

@help autoloot

“Autoloot” refers to automatically getting (or “looting”) items from the corpse of a monster (also called a “mob” or “mobile”), after you’ve killed it.  

There are two ways to set your autoloot options. 

1) Click the icon on the bottom button bar, furthest to the right, which cycles between looting coins only, looting all items (including coins), or turning autoloot off completely.

2) Using the ‘@set autoloot’ command.

Usage:

@set autoloot coins - loots coins only.
@set autoloot all - loots all items (including coins).
@set autoloot off - turns off autoloot.

See also: @help @set, @set, @help index

**Comment by Nyyrazzilyss** [comment]
added 11/3/17 dev
