### ISSUE TITLE
warrior shield punch

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#73]
Script version: 10/27/2017 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

shield punch causes a problem that locks warriors up,

and unmapped rooms starting west of room number 19333

**Comment by Nyyrazzilyss** [comment]
shield punch + silence person had the same alias - fixed 11/3/17 dev
unmapped rooms added 11/3/17 dev
