### ISSUE TITLE
Problem with keeping map in sync

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#74]
if you are in anywhere and lets say for example. you hit up in a east west room like 5 times fast then hit east without waiting for those 5 ups to return a cannot go that way the mapper will lose you and sometimes scan will fix it alot of the time it doesnt. in ribcage today the mapper would NOT leave the astral plane until we got to the grid outside tiamat. thats 2 problems. wish i could help. sorry

**Comment by Nyyrazzilyss** [comment]
Attempting to type .wn from a room that doesn't have a west exit will desync the map

**Comment by Nyyrazzilyss** [comment]
fixed 11/7 dev
