### ISSUE TITLE
Ranger Sweeping Strikes

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#78]
for some reason sometimes you cannot click it. sometimes it changes from sweeping strikes to bash. on ranger no idea.

Script version: 11/4/2017 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

**Comment by Nyyrazzilyss** [comment]
possibly fixed 11/7 dev, it would need more specific information to identify the problem cause
