### ISSUE TITLE
Map can lose sync when paging mode enabled

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#79]
if you are using room # assignments to go from room to room the mapper just cant keep up. it gets confused on where you are and then tries to go to the next room number assuming its in one room when it is in another.

sometimes the mapper gets confused and stops following you altogether and goes in random directions. like you go north it goes east you go north again it moves south. @find works sometimes but if there are multiple rooms with same name its hopeless.

**Comment by Nyyrazzilyss** [comment]
Example? Exact commands?

Ideally, enable vnum display (@set vnum true) so it's showing room numbers, then post a log of the problem occuring that includes 

1) The map in sync with the correct vnum
2) The commands you're sending
3) The map showing out of sync (the wrong vnum would show)

Also, include the version in use (type '@version')

**Comment by i982** [comment]
vnum is true.. it use them to run my trains. (which gets lost as well)

the image is of me in the inn.. the mapper thinks im one north. to duplicate i just randomly hit directions 5 times. i ended up in the inn and but mapper couldnt keep up.

![broken mapper](https://user-images.githubusercontent.com/33096956/32682713-17521d56-c63c-11e7-93fe-b8d93e33d6ea.png)

**Comment by Nyyrazzilyss** [comment]
Version?

Rather then a screenshot, scroll up to just prior to the problem occuring, and highlight the lines until the problem occurs. Right click/select copy, then paste the log. That would show it working, commands sent, and then it not working :)

Thanks

**Comment by i982** [comment]
here is another easy break for the mapper. anywhere, doesnt matter, type news. then try to move. then actually move in any direction. mapper broken. then it starts making random moves. even though you are going one direction it may go north south up down any direction. this has been a 100 percent breaker for me.

**Comment by Nyyrazzilyss** [comment]
Version?

**Comment by i982** [comment]
Script version: 11/13/2017 NyyLIB011dev https://github.com/Nyyrazzilyss/NyyLIB

seriously dude? 

"here is another easy break for the mapper. anywhere, doesnt matter, type news. then try to move. then actually move in any direction. mapper broken. then it starts making random moves. even though you are going one direction it may go north south up down any direction. this has been a 100 percent breaker for me."

do you see me say 'news' is a movement command anywhere?

i also didn't say type news then 'l' as you did above.

nor did i say type '.news' as you did above.

ok let me break it down.

any command that results in the following:

------------------->[RETURN for more, q to quit]<-------------------

as the current option on your screen as a prompt FOLLOWED by a "MOVEMENT"  in any direction will confuse the mapper.

SO

[RETURN for more, q to quit] + north(or any direction) = glitched mapper.

so do you want me to start streaming the issues so you can watch videos with commentary?

**Comment by Nyyrazzilyss** [comment]
Thanks, that's the answer - You're in paging mode (i'm not = I never see [RETURN for more, q to quit])

Will fix

**Comment by Nyyrazzilyss** [comment]
fixed 11/14 dev
