### ISSUE TITLE
Rogue starttrain tank issues

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#8]
**#1 If a mob lands a trip on me I don't resume automatically tripping when I stand.  If I manually trip the autotrip resumes as expected.**

Log:
[Reached train station: (87254) Ashstone noble]

An Ashstone noble is in an excellent condition. (Medium)

< 1160h/440H 120v/130V P: std > 
But you are a member of no group?!

< 1155h/440H 121v/130V P: std >

You get a vial of black liquid from a portable hole.

< 1154h/440H 122v/130V P: std >

You use the last of the poison.
You generously apply poison to a glittering dagger of the Nurturing Matriarch.

< 1153h/440H 122v/130V P: std >

You don't have the blind.

< 1152h/440H 122v/130V P: std >

You get a vial of slimy liquid from a portable hole.

< 1151h/440H 122v/130V P: std >

You use the last of the poison.
You generously apply poison to a red dragon fanged dagger.

< 1150h/440H 122v/130V P: std >

You don't have the slow.

< 1149h/440H 123v/130V P: std >

An Ashstone noble dodges your futile attack.

< 1148h/440H 123v/130V T: Ezdad TC: excellent E: noble EC: excellent EP: std P: std > 

An Ashstone noble misses you with his hit. (x2)
An Ashstone noble does an acrobatic maneuver in battle, tripping you.
However, you take an Ashstone noble down with you!
Your massive pierce barely wounds an Ashstone noble.
As your poison takes effect, an Ashstone noble appears to go blind!
Your mighty pierce barely wounds an Ashstone noble.
Your massive pierce barely wounds an Ashstone noble. (x2)
As your poison takes effect, an Ashstone noble begins to sllooowwww down.
Your massive pierce barely wounds an Ashstone noble.

< 1140h/440H 125v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: sit P: rcl > 

An Ashstone noble badly wounds you with his massive hit.
OUCH!  That really did HURT!
You strike at an Ashstone noble's belly, causing him to double over in agony and drop to his knees!
Your massive pierce barely wounds an Ashstone noble. (x3)
The poison on your weapon wears off.
Your massive pierce barely wounds an Ashstone noble.

< 1046h/440H 129v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: knl P: rcl > 
< 1039h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: knl P: rcl >

Sorry, you can't do that while lying around.

< 1039h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: knl P: rcl >

You clamber to your feet.

< 1036h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: knl P: std >  (x2)

An Ashstone noble misses you with his hit.
Your massive pierce barely wounds an Ashstone noble. (x2)
The poison on your weapon wears off.
Your massive pierce barely wounds an Ashstone noble. (x3)

< 1034h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: knl P: std > 

You dodge an Ashstone noble's vicious attack.
An Ashstone noble rises to his feet.
Your wonderful glittering dagger glows brightly as your body starts to flicker, in
and out of visibility! You spring to the side, dodging an Ashstone noble's attack.
the holy blessing of Yondalla has taken hold upon you! an Ashstone noble cries
out as you plunge your dagger perfectly into the center of his back. You grin
as your dagger draws the very lifeforce out of him.
Your massive pierce barely wounds an Ashstone noble. (x3)
An Ashstone noble dodges your futile attack.
Your massive pierce barely wounds an Ashstone noble.

< 1225h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few wounds EP: std P: std > 

An Ashstone noble misses you with his hit.
Your massive pierce barely wounds an Ashstone noble. (x3)
Your massive pierce slightly wounds an Ashstone noble.
You miss an Ashstone noble with your pierce.

< 1196h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few wounds EP: std P: std > 

**#2 If I am solo with starttrain tank and then I form a group the auto-looter is disabled.  I'd expect to still loot coins :)**

Log:
< 873h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: std P: std > 

Dagk has just given you his consent.

< 864h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: std P: std > 

An Ashstone noble misses you with his hit.
An Ashstone noble badly wounds you with his massive hit.
OUCH!  That really did HURT!
Your massive pierce barely wounds an Ashstone noble.
You miss an Ashstone noble with your pierce.
Your massive pierce barely wounds an Ashstone noble.
The poison on your weapon wears off.
Your massive pierce barely wounds an Ashstone noble. (x2)

< 795h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: std P: std >

< 794h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: std P: std >

You do a fancy maneuver, tripping an Ashstone noble.

< 794h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: few scratches EP: rcl P: std > 

You dodge an Ashstone noble's vicious attack.
An Ashstone noble misses you with his hit.
Your massive pierce barely wounds an Ashstone noble.
You miss an Ashstone noble with your pierce.
Your massive pierce barely wounds an Ashstone noble. (x2)
As your poison takes effect, an Ashstone noble begins to sllooowwww down.

< 789h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: rcl P: std > 

An Ashstone noble misses you with his hit.
An Ashstone noble clambers to his feet.
You miss an Ashstone noble with your pierce.
Your massive pierce barely wounds an Ashstone noble. (x4)

< 783h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: std P: std > 
You form a new group.
[Setting autoloot to off]

< 781h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: small wounds EP: std P: std > 

**#3 stoptrain does not work for rogue - it turns off caster train**  I use resettrain, which works fine but this could lead to confusion for others.

Log:

< 1430h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: nasty wounds EP: rcl P: std > 
stoptrain
[Stopping: Caster train trigger]

An Ashstone noble misses you with his hit.
Your wonderful glittering dagger glows brightly as your body starts to flicker, in
and out of visibility! You spring to the side, dodging an Ashstone noble's attack.
the holy blessing of Yondalla has taken hold upon you! an Ashstone noble cries
out as you plunge your dagger perfectly into the center of his back. You grin
as your dagger draws the very lifeforce out of him.
Your massive pierce slightly wounds an Ashstone noble.
An Ashstone noble dodges your futile attack.
Your massive pierce slightly wounds an Ashstone noble. (x2)
Your massive pierce badly wounds an Ashstone noble.

< 1500h/440H 130v/130V T: Ezdad TC: excellent E: noble EC: pretty hurt EP: rcl P: std >

**Comment by Gyrx** [comment]
Regarding #1, the solution that Nyyr shared with me seemed to address the issue:

Solution:
Trigger: You clamber to your feet / setTripping(false)


Log:
< 529h/658H 127v/130V P: std > 

[Reached train station: (87249) Ashstone noble]

An Ashstone noble is in an excellent condition. (Medium)

acc yea i never got why the newbie zone invasion is so hard
< 530h/658H 127v/130V P: std >

Imay ASSOC:: 'fucking rares'
You ASSOC: 'yea i never got why the newbie zone invasion is so hard'

< 530h/658H 128v/130V P: std > 
But you are a member of no group?!

< 531h/658H 129v/130V P: std >

Your massive pierce barely wounds an Ashstone noble.

< 531h/658H 129v/130V T: Ezdad TC: small wounds E: noble EC: few scratches EP: std P: std > 

You dodge an Ashstone noble's vicious attack. (x2)
An Ashstone noble does an acrobatic maneuver in battle, tripping you.
Severely weakened, an Ashstone noble falls to his knees!
Your massive pierce barely wounds an Ashstone noble. (x6)

< 532h/658H 130v/130V T: Ezdad TC: small wounds E: noble EC: small wounds EP: knl P: rcl > 
acc should be easy as shit for a new player

An Ashstone noble wounds you harshly with his massive hit.
OUCH!  That really did HURT!
An Ashstone noble wounds you harshly with his massive hit.
OUCH!  That really did HURT!
Your massive pierce barely wounds an Ashstone noble. (x5)

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: rcl > 

[Ezdad : the mystical circlet of the coiled serpent]
Your massive pierce barely wounds an Ashstone noble.
An Ashstone noble dodges your futile attack.
Blood flies everywhere as you plunge your weapon deep into an Ashstone noble's side.
Your massive pierce slightly wounds an Ashstone noble.
Your massive pierce barely wounds an Ashstone noble.

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: rcl > 
< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: rcl >

Sorry, you can't do that while lying around.

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: rcl >

You clamber to your feet.

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: std >

You ASSOC: 'should be easy as shit for a new player'

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: knl P: std >  (x2)

An Ashstone noble misses you with his hit. (x2)
An Ashstone noble rises to his feet.
Your massive pierce barely wounds an Ashstone noble. (x3)
An Ashstone noble dodges your futile attack.

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: std P: std >

You do a fancy maneuver, tripping an Ashstone noble.

< 377h/658H 130v/130V T: Ezdad TC: few wounds E: noble EC: small wounds EP: rcl P: std >

**Comment by Nyyrazzilyss** [comment]
Fixed dev update posted 7/15/17
