### ISSUE TITLE
hrmm bug on exp train?

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#80]
See bug below while i was following Kayos on his exp train (not nyyrs) - though i had done @starttrain fol

Had done loops of SM without issue but this error happened at least twice, but only when i was at Izolde - the mem also ended with Puppet each time I got the bug, though not sure if relevant.  It would not return me back to the Izolde room, and when i manually went there after the bug it would not autoassist.

This was the only mob where this error happened.

And you are currently praying for the following spells:
    1 seconds:  ( 1st) Totem Darts
    5 seconds:  ( 1st) Totem Darts
   10 seconds:  ( 1st) Totem Darts
   14 seconds:  ( 1st) Totem Darts
   19 seconds:  ( 1st) Totem Darts
   29 seconds:  ( 5th) Puppet

You can pray for no more spells.

< 739h/739H 165v/165V P: sit >

< 739h/739H 165v/165V P: sit > 
save
Saving...

< 739h/739H 165v/165V P: sit > 

You have finished praying for Totem Darts.

< 739h/739H 165v/165V P: sit > 

You have finished praying for Totem Darts.

< 739h/739H 165v/165V P: sit > 
A gentle breeze blows through causing leaves to rustle.

< 739h/739H 165v/165V P: sit > 

You have finished praying for Totem Darts.

< 739h/739H 165v/165V P: sit > 

You have finished praying for Totem Darts.

< 739h/739H 165v/165V P: sit > 

Autosaving...

< 739h/739H 165v/165V P: sit >

It is 2pm, on the Day of the Moon
The 28th Day of the Month of Nightal (the Drawing Down), Year 1003.
Time elapsed since boot-up: 14:30:13
Current time is: Sat Nov 11 07:10:03 2017

< 739h/739H 165v/165V P: sit > 

A wagon rumbles along nearby, wooden wheels clattering on the stones.

< 739h/739H 165v/165V P: sit > 

You have finished praying for Totem Darts.

< 739h/739H 165v/165V P: sit > 

Thomas Birchbell starts casting a spell.

< 739h/739H 165v/165V P: sit > 

You have finished praying for Puppet.
Your prayers are complete."error"true

[  LUA  ] - object:<finish mem/pray return to fight> function:<Trigger412>
            <expandAlias: wrong argument type>

< 739h/739H 165v/165V P: std >

**Comment by Hibbidy** [comment]
Same thing just happened again, but Puppet wasnt being memmed - so guess thats not relevant.

**Comment by Hibbidy** [comment]
Just happened again, this time at Shalyssa -

**Comment by Nyyrazzilyss** [comment]
The error would appear that it didn't know where you were mem'ing in relationship to the fight, possibly from fleeing from a paladin? I've changed the error message slightly to make it clearer, in particular i'd need to see how you moved into that room - updated dev 11/13
