### ISSUE TITLE
boom

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#81]
send("ack " .. matches[2]) 
send("afk " .. matches[2]) 
send("agree " .. matches[2]) 
send("amaze " .. matches[2]) 
send("apologize " .. matches[2]) 
send("applaud " .. matches[2]) 
send("arch " .. matches[2]) 
send("ayt " .. matches[2]) 
send("bang " .. matches[2]) 
send("bark " .. matches[2]) 
send("bathe " .. matches[2]) 
send("bbl " .. matches[2]) 
send("beer " .. matches[2]) 
send("beg " .. matches[2]) 
send("bird " .. matches[2]) 
send("bite " .. matches[2]) 
send("bleed " .. matches[2]) 
send("blink " .. matches[2]) 
send("blow " .. matches[2]) 
send("blush " .. matches[2]) 
send("boggle " .. matches[2]) 
send("bonk " .. matches[2]) 
send("bored " .. matches[2]) 
send("bounce " .. matches[2]) 
send("bow " .. matches[2]) 
send("brb " .. matches[2]) 
send("burp " .. matches[2]) 
send("bye " .. matches[2]) 
send("cackle " .. matches[2]) 
send("calm " .. matches[2]) 
send("caress " .. matches[2]) 
send("censor " .. matches[2]) 
send("cheek " .. matches[2]) 
send("cheer " .. matches[2]) 
send("choke " .. matches[2]) 
send("chuckle " .. matches[2]) 
send("clap " .. matches[2]) 
send("comb " .. matches[2]) 
send("comfort " .. matches[2]) 
send("congratulate " .. matches[2]) 
send("cough " .. matches[2]) 
send("cringe " .. matches[2]) 
send("cry " .. matches[2]) 
send("cuddle " .. matches[2]) 
send("curious " .. matches[2]) 
send("curse " .. matches[2]) 
send("curtsey " .. matches[2]) 
send("dance " .. matches[2]) 
send("doh " .. matches[2]) 
send("dream " .. matches[2]) 
send("drool " .. matches[2]) 
send("dropkick " .. matches[2]) 
send("duck " .. matches[2]) 
send("embrace " .. matches[2]) 
send("envy " .. matches[2]) 
send("eyebrow " .. matches[2]) 
send("fart " .. matches[2]) 
send("fidget " .. matches[2]) 
send("flame " .. matches[2]) 
send("flash " .. matches[2]) 
send("flex " .. matches[2]) 
send("flip " .. matches[2]) 
send("flirt " .. matches[2]) 
send("flutter " .. matches[2]) 
send("fondle " .. matches[2]) 
send("fool " .. matches[2]) 
send("french " .. matches[2]) 
send("frown " .. matches[2]) 
send("full " .. matches[2]) 
send("fume " .. matches[2]) 
send("fuzzy " .. matches[2]) 
send("gag " .. matches[2]) 
send("gape " .. matches[2]) 
send("gasp " .. matches[2]) 
send("giggle " .. matches[2]) 
send("glare " .. matches[2]) 
send("grin " .. matches[2]) 
send("groan " .. matches[2]) 
send("grope " .. matches[2]) 
send("grovel " .. matches[2]) 
send("growl " .. matches[2]) 
send("grumble " .. matches[2]) 
send("grunt " .. matches[2]) 
send("hand " .. matches[2]) 
send("happy " .. matches[2]) 
send("hero " .. matches[2]) 
send("hiccup " .. matches[2]) 
send("hiss " .. matches[2]) 
send("hi5 " .. matches[2]) 
send("holdon " .. matches[2]) 
send("hop " .. matches[2]) 
send("hug " .. matches[2]) 
send("hum " .. matches[2]) 
send("hunger " .. matches[2]) 
send("imitate " .. matches[2]) 
send("impale " .. matches[2]) 
send("insult " .. matches[2]) 
send("introduce " .. matches[2]) 
send("jam " .. matches[2]) 
send("jk " .. matches[2]) 
send("jump " .. matches[2]) 
send("kiss " .. matches[2]) 
send("kneel " .. matches[2]) 
send("stand")
send("laugh " .. matches[2]) 
send("lag " .. matches[2]) 
send("lean " .. matches[2]) 
send("lick " .. matches[2]) 
send("love " .. matches[2]) 
send("lost " .. matches[2]) 
send("lucky " .. matches[2]) 
send("massage " .. matches[2]) 
send("melt " .. matches[2]) 
send("moan " .. matches[2]) 
send("moon " .. matches[2]) 
send("mosh " .. matches[2]) 
send("mourn " .. matches[2]) 
send("mutter " .. matches[2]) 
send("nap " .. matches[2]) 
send("nibble " .. matches[2]) 
send("nod " .. matches[2]) 
send("nog " .. matches[2]) 
send("noogie " .. matches[2]) 
send("nose " .. matches[2]) 
send("nudge " .. matches[2]) 
send("nuzzle " .. matches[2]) 
send("ogle " .. matches[2]) 
send("panic " .. matches[2]) 
send("pant " .. matches[2]) 
send("pat " .. matches[2]) 
send("peer " .. matches[2]) 
send("pet " .. matches[2]) 
send("pillow " .. matches[2]) 
send("pinch " .. matches[2]) 
send("plonk " .. matches[2]) 
send("point " .. matches[2]) 
send("poke " .. matches[2]) 
send("ponder " .. matches[2]) 
send("pose " .. matches[2]) 
send("pounce " .. matches[2]) 
send("pout " .. matches[2]) 
send("protect " .. matches[2]) 
send("pucker " .. matches[2]) 
send("puke " .. matches[2]) 
send("pull " .. matches[2]) 
send("punch " .. matches[2]) 
send("purr " .. matches[2]) 
send("push " .. matches[2]) 
send("puzzle " .. matches[2]) 
send("raise " .. matches[2]) 
send("ready " .. matches[2]) 
send("roar " .. matches[2]) 
send("rofl " .. matches[2]) 
send("roll " .. matches[2]) 
send("rose " .. matches[2]) 
send("rub " .. matches[2]) 
send("ruffle " .. matches[2]) 
send("salute " .. matches[2]) 
send("scare " .. matches[2]) 
send("scold " .. matches[2]) 
send("scratch " .. matches[2]) 
send("scream " .. matches[2]) 
send("seduce " .. matches[2]) 
send("shake " .. matches[2]) 
send("shiver " .. matches[2]) 
send("shove " .. matches[2]) 
send("shrug " .. matches[2]) 
send("shudder " .. matches[2]) 
send("shush " .. matches[2]) 
send("sigh " .. matches[2]) 
send("sing " .. matches[2]) 
send("skip " .. matches[2]) 
send("slap " .. matches[2]) 
send("slobber " .. matches[2]) 
send("smell " .. matches[2]) 
send("smile " .. matches[2]) 
send("smirk " .. matches[2]) 
send("smoke " .. matches[2]) 
send("snap " .. matches[2]) 
send("snarl " .. matches[2]) 
send("sneer " .. matches[2]) 
send("sneeze " .. matches[2]) 
send("snicker " .. matches[2]) 
send("sniff " .. matches[2]) 
send("snoogie " .. matches[2]) 
send("snore " .. matches[2]) 
send("snort " .. matches[2]) 
send("snuggle " .. matches[2]) 
send("spam " .. matches[2]) 
send("spank " .. matches[2]) 
send("spin " .. matches[2]) 
send("spit " .. matches[2]) 
send("squeeze " .. matches[2]) 
send("squirm " .. matches[2]) 
send("stare " .. matches[2]) 
send("steam " .. matches[2]) 
send("stomp " .. matches[2]) 
send("strangle " .. matches[2]) 
send("stretch " .. matches[2]) 
send("strut " .. matches[2]) 
send("sulk " .. matches[2]) 
send("swat " .. matches[2]) 
send("sweat " .. matches[2]) 
send("sweep " .. matches[2]) 
send("tackle " .. matches[2]) 
send("tango " .. matches[2]) 
send("tap " .. matches[2]) 
send("tarzan " .. matches[2]) 
send("taunt " .. matches[2]) 
send("tease " .. matches[2]) 
send("thank " .. matches[2]) 
send("think " .. matches[2]) 
send("thirst " .. matches[2]) 
send("throw " .. matches[2]) 
send("tickle " .. matches[2]) 
send("tip " .. matches[2]) 
send("tiptoe " .. matches[2]) 
send("tongue " .. matches[2]) 
send("toss " .. matches[2]) 
send("touch " .. matches[2]) 
send("trip " .. matches[2]) 
send("tug " .. matches[2]) 
send("tweak " .. matches[2]) 
send("twibble " .. matches[2]) 
send("twiddle " .. matches[2]) 
send("twirl " .. matches[2]) 
send("undress " .. matches[2]) 
send("veto " .. matches[2]) 
send("wait " .. matches[2]) 
send("wave " .. matches[2]) 
send("welcome " .. matches[2]) 
send("wet " .. matches[2]) 
send("whap " .. matches[2]) 
send("whatever " .. matches[2]) 
send("wheeze " .. matches[2]) 
send("whimper " .. matches[2])
send("whine " .. matches[2]) 
send("whistle " .. matches[2]) 
send("wiggle " .. matches[2]) 
send("wince " .. matches[2]) 
send("wink " .. matches[2]) 
send("woops " .. matches[2]) 
send("worship " .. matches[2]) 
send("yawn " .. matches[2]) 
send("yodel " .. matches[2]) 
send("zone " .. matches[2])

**Comment by Nyyrazzilyss** [comment]
Thanks
