### ISSUE TITLE
Paladin mem/moving triggers

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#82]
they arent working or were just removed/disabled.:)
this also happens when you stand while praying
< 1144h/1144H 211v/211V |vs +|brs +|trs +|wws +|ds 41| P: sit > 
st
You clamber to your feet.
You abandon your prayers.
[Error: unable to locate label: MemButton]

< 1144h/1144H 211v/211V |vs +|brs +|trs +|wws +|ds 41| P: std >

**Comment by Nyyrazzilyss** [comment]
The mem/spells triggers have all been removed from paladin with expectation the class is to be switched to ranger style spellcasting in the next week or two.
