### ISSUE TITLE
button bar switches on level

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#84]
Whenever I level, the button bar switches to the 1h buttons, even though im wielding a 2h'er - i need to do an 'eq' to get it to switch back -

**Comment by Gyrx** [comment]
< 536h/536H 110v/110V T: Xiles TC: few scratches E: noble EC: nasty wounds EP: sit P: std > 

[Brilliant Smite]
Xiles ASSOC:: 'crashed b4 dagos and no imms on to clear what we did'
Your weapon detonates in a flash of pure light as you strike an Ashstone noble!

< 536h/536H 110v/110V T: Xiles TC: few scratches E: noble EC: nasty wounds EP: sit P: std > 

Gaimaede slightly wounds an Ashstone noble with her massive bludgeon.
Gaimaede brutally wounds an Ashstone noble with her massive bludgeon.
Gaimaede badly wounds an Ashstone noble with her massive bludgeon.
Your massive slash slightly wounds an Ashstone noble.
You raise a level!
Your massive slash slightly wounds an Ashstone noble.
With a blinding burst, your blade explodes into a brilliant display of solar
energy, erupting around you with intense fury.  The evil in the room begins
to shiver and cringe as the blades searing power disrupts their very existence.

An Ashstone noble cringes from the intense sunburst.
Renur badly wounds an Ashstone noble with his massive bludgeon.
Renur severely wounds an Ashstone noble with his massive slash.
Renur badly wounds an Ashstone noble with his massive bludgeon.
Renur badly wounds an Ashstone noble with his massive slash.
Renur badly wounds an Ashstone noble with his massive bludgeon.
An Ashstone noble clambers to his feet.
Xiles badly wounds an Ashstone noble with his massive slash. (x2)
Xiles severely wounds an Ashstone noble with his massive slash.

< 536h/545H 110v/110V T: Xiles TC: few scratches E: noble EC: awful EP: std P: std >

Xiles sends an Ashstone noble sprawling with a powerful bash.

          Score information for Rocken

Level: 39   Race: Half-Orc   Class: Paladin     
Hit points: 536(545)  Moves: 110(110)
Experience Progress: 0 % 
Coins carried:    0 platinum     0 gold     0 silver     0 copper
Coins in bags:  610 platinum   476 gold    73 silver    78 copper
Coins in bank:  938 platinum     4 gold     6 silver     6 copper
Prestige: 4220   Acheron Kill Count: 0
Citizen of:   Baldur's Gate
Outcast from: Leuthilspar
Playing time: 0 days / 8 hours / 45 minutes
Title: 
Group Name: Xiles and Company
Group Leader: Xiles
Status:  Standing, fighting an Ashstone noble.
Detecting:       Evil Heat
Enchantments:    Farsee Haste No Summon

< 536h/545H 110v/110V T: Xiles TC: few scratches E: noble EC: awful EP: sit P: std >

You group-say '<<< Level 39! >>>'
Rumn strikes the weak spots in an Ashstone noble's armor, leaving him vulnerable.

< 536h/545H 110v/110V T: Xiles TC: few scratches E: noble EC: awful EP: sit P: std > 

[Xiles : the mystical circlet of the coiled serpent]
Xiles wounds an Ashstone noble harshly with his massive slash. (x2)
Xiles brutally wounds an Ashstone noble with his massive slash.
With a blinding burst, Xiles's blade explodes into a brilliant display of solar
energy, erupting around him with intense fury.  The evil in the room begins
to shiver and cringe as the blades searing power disrupts their very existence.

An Ashstone noble cringes from the intense sunburst.
An Ashstone noble staggers from Xiles's massive slash!
Xiles critically wounds an Ashstone noble with a massive slash!
An Ashstone noble is nearly slain by the force of Xiles's massive slash!

< 536h/545H 110v/110V T: Xiles TC: few scratches E: noble EC: awful EP: sit P: std > 
[Shielding Smite]
You need to wear a shield to do that.

< 536h/545H 110v/110V T: Xiles TC: few scratches E: noble EC: awful EP: sit P: std >

**Comment by Nyyrazzilyss** [comment]
fixed 11/22 dev
