### ISSUE TITLE
bolstering strike

### ISSUE THREAD

**Issue by i982** [Nyyrazzilyss/NyyLIB#85]
not really an issue but is there a way you could make it priority over the other abilities if off cooldown if health is at small sounds? or even below max. just and idea.

**Comment by Nyyrazzilyss** [comment]
If you look at function procPromptPal(), usage order is

lay on hands
divine smite
radiant charge
shielding smite
bolstering strike (if damaged)
wrathful smite
enervating smite
bolstering smite (if not damaged, but also not using anything else)
