### ISSUE TITLE
Missing rooms in Seers

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#87]
there are ~10 rooms missing from seers, starting to the west of "Chamber of Choices" #86096.  Room log below.  The missing rooms are along the path up to the room "Entrance to the Forbidden" #86106

Chamber of Choices
   This tunnel ends so abruptly without going anywhere that it is obvious that
a secret tunnel must exist.  In which wall it exists is the question and
perhaps only the three levers attached to the walls can answer that.  To the
east is a tight spiral staircase leading up.  The north, south and east walls
are made of a white flecked black marble and all appear to be very solid.
all three levers are in the up position.  It would seem that anyone entering
the deep vault has to make a decision.
Exits: - East          [86096]  [Hidden]
A brass lever juts from the wall.
A steel lever juts from the wall.
A bronze lever juts from the wall.

**Comment by Nyyrazzilyss** [comment]
Added, will be included next dev
