### ISSUE TITLE
Missing Rooms - Bloodtusk

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#9]
**1) Bloodtusk - Room # 84992 should have say "blood" so that you can unlock gates north to room # 84994 (need to also say blood to exit after pop)**

**2) Unmapped room: 1 up from room #89775**

Northeast Tower of Bloodtusk
Exits: - Down               [Unmapped] 
A mother orc is tending to her children here.
An elite guard stands here watching you intently.
A tower guard stands here at attention. (x2)
A lieutenant of the eastern watch scans the horizon here.

**3) Bloodtusk vault is not mapped: 1 east of room # 92443**
The vault is closed.
You extend your vision through the vault.
The Bloodtusk Vault
   The walls here are very smooth and shiny. Several chests line the
various walls of the room while a single massive mound of gold sits
squarely in the room. Large bookcases adorn the southern wall housing
a multitude of scrolls and tomes. A weapon rack has been placed against
the west wall. A large tapestry hangs in the middle of the room over the
gold displaying the seal of Bloodtusk Keep proudly. Several tripods have
been set up about the vault each supporting a medium sized brass urn. An
intense orange flame burns within the urns filling the air with a thick
pink haze. A strong scent of cinnamon lingers in the air here.
Exits: - West #        [92443] 
You sense a hidden life form in the room.

< 355h/487H 90v/121V P: std > 
l
The King's Chambers
Exits: - East # - West   [92443] 
A member of the King's guard is here.(Red Aura) (x3)
The self proclaimed king of Bloodtusk stands here.(Red Aura)
A huge orc stands guard here.(Red Aura)
A massive ogre stands guard here.(Red Aura)
You sense a hidden life form in the room.
A member of the King's guard is here.(Red Aura)

**4) Unmapped Room: 1 up from room # 89759**

**5) Unmapped room: 1up and 1 north from room # 89753
**6) Unmapped room: 1up from 89746****

**Comment by Nyyrazzilyss** [comment]
These rooms added to 011dev 07-17 (44816 rooms)
