### ISSUE TITLE
Casting while moving?

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#92]
This happened a few times tonight while running a ranger custom xp train - seems to be casting while moving -

You swing your weapons in lethal arcs, dousing the area with a half-elven merchant's blood.
A half-elven merchant slumps to the ground.
You swing your weapons in a killing arc, eviscerating a half-elven merchant in a spray of gore.
a half-elven merchant is dead! R.I.P.
A half-elven merchant is stunned!
A half-elven merchant slumps to the ground.
You receive 38,686 XP (0.10%) experience.
Your blood freezes as you hear the rattling death cry of a half-elven merchant.
look

[Calling function: NextTrainStop()]

< 543h/667H 115v/115V |0|2|0|0|2| P: std >

You get a few coins from corpse of a half-elven merchant.
There were: 4 platinum coins, 18 gold coins, 1 silver coin, 5 copper coins.
pac
put all.coin portable

< 543h/667H 115v/115V |0|2|0|0|2| P: std >

< 543h/667H 115v/115V |0|2|0|0|2| P: std >

A Stately House
Exits: -S              [49082] 
[2] Corpse of a half-elven merchant is lying here.
A wooden key rests here.

< 543h/667H 115v/115V |0|2|0|0|2| P: std >

Ok.
You put some coins into a portable hole.

< 543h/667H 115v/115V |0|2|0|0|2| P: std > 
Fokin GCC: 'who fokin'

< 543h/667H 115v/115V |0|2|0|0|2| P: std > 
Your shadowy cloak of resilience dissolves.

< 547h/667H 115v/115V |0|2|1|0|2| P: std > 
@fwalk 49091
[Path: .s5en]
s

[Currently moving - spellcast is temporarily disabled]
e
e
e
e
e
n

You start chanting... [Casting: clp (Cloak of Protection)]

< 555h/667H 115v/115V |0|2|1|0|2| P: std >

You're busy spellcasting!  [command: n]

< 555h/667H 115v/115V |0|2|1|0|2| P: std > 
You complete your spell...[Completed spell: clp (Cloak of Protection)]
Softly glowing mists wrap around you in an cloak of protection.

< 555h/667H 115v/115V |0|2|0|0|2| P: std >

Alas, you cannot go that way. . . .

< 557h/667H 115v/115V |0|2|0|0|2| P: s

**Comment by Nyyrazzilyss** [comment]
probably fixed 12/6 dev
