### ISSUE TITLE
rescuing non-grouped players while on xp train

### ISSUE THREAD

**Issue by Hibbidy** [Nyyrazzilyss/NyyLIB#94]
I was not grouped, doing sm exp train - I had "Rescue All" toggled, which says:  [All grouped players will be rescued]

Ultrumm's Music Conservatory
Exits: -S -U           [49134] 
An apprentice bard stands here practicing a new song.
An apprentice bard stands here practicing a new song.

< 564h/548H 107v/120V |bs +|rc +|ss +|es +|ws +| P: std >

An Upper Floor Practice Room
Exits: -D              [49135] 
Corpse of Ultrumm is lying here.
Ultrumm stands here listening to his students.

< 564h/548H 106v/120V |bs +|rc +|ss +|es +|ws +| P: std > 

[Reached train station: (49135) Ultrumm]

Usafer enters from below.

< 563h/548H 114v/120V |bs +|rc +|ss +|es +|ws +| P: std >

Ultrumm is in an excellent condition. (Medium)

< 563h/548H 114v/120V |bs +|rc +|ss +|es +|ws +| P: std > 
Usafer sends Ultrumm sprawling with a powerful bash.

< 563h/548H 114v/120V |bs +|rc +|ss +|es +|ws +| P: std > 
Usafer deflects Ultrumm's blow, and strikes back at Ultrumm!
Usafer barely wounds Ultrumm with his massive slash.
Ultrumm slightly wounds Usafer with his strong hit.
Usafer barely wounds Ultrumm with his powerful slash.
Usafer barely wounds Ultrumm with his massive slash.
Usafer barely wounds Ultrumm with his massive slash.

< 563h/548H 117v/120V |bs +|rc +|ss +|es +|ws +| P: std >

Your bash at Ultrumm sends him sprawling.

< 563h/548H 117v/120V |bs +|rc +|ss +|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: few
scratches EP: sit P: std > 
[Shielding Smite]

[ Rescue: Usafer ]
Ultrumm misses Usafer with his hit.
Ultrumm misses Usafer with his hit.
Usafer misses Ultrumm with his slash.
Usafer barely wounds Ultrumm with his massive slash.

< 563h/548H 120v/120V |bs +|rc +|ss +|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: few
scratches EP: sit P: std > 
Usafer's weapon flares with a burst of divine radiance as it strikes Ultrumm!

< 563h/548H 120v/120V |bs +|rc +|ss +|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: small
wounds EP: sit P: std > 
[Usafer : the mystical circlet of the coiled serpent]
Usafer barely wounds Ultrumm with his powerful slash.
Usafer misses Ultrumm with his slash.
Ultrumm dodges Usafer's attack.
Usafer barely wounds Ultrumm with his massive slash.
Usafer misses Ultrumm with his slash.
Usafer barely wounds Ultrumm with his powerful slash.
Usafer barely wounds Ultrumm with his massive slash.

< 562h/548H 120v/120V |bs +|rc +|ss +|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: small
wounds EP: sit P: std > 
Ultrumm misses Usafer with his hit.
Usafer deflects Ultrumm's blow, and strikes back at Ultrumm!
Usafer barely wounds Ultrumm with his massive slash.
Usafer misses Ultrumm with his slash.
Usafer barely wounds Ultrumm with his massive slash.
Usafer barely wounds Ultrumm with his massive slash.

< 562h/548H 120v/120V |bs +|rc +|ss +|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: small
wounds EP: sit P: std >

You strike a glancing blow upon Ultrumm, and your golden shield fails to appear.

< 562h/548H 120v/120V |bs +|rc +|ss 3|es +|ws +| T: Usafer TC: few scratches E: ultrumm EC: small
wounds EP: sit P: std >

Banzai! To the rescue...
[ Rescue: Usafer ]

< 562h/548H 120v/120V |bs +|rc +|ss 3|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: small
wounds EP: sit P: std > 
[Nomginnaen : the mystical circlet of the coiled serpent]

< 562h/548H 120v/120V |bs +|rc +|ss 3|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: sit P: std > 
Ultrumm misses you with his hit.
Ultrumm misses you with his hit.
Ultrumm clambers to his feet.

< 562h/548H 120v/120V |bs +|rc +|ss 3|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: std P: std >

< 562h/548H 120v/120V |bs +|rc +|ss 2|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: std P: std >

But nobody is fighting him?

< 562h/548H 120v/120V |bs +|rc +|ss 2|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: std P: std >

< 562h/548H 120v/120V |bs +|rc +|ss 2|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: std P: std >

Your bash at Ultrumm sends him sprawling.

< 562h/548H 120v/120V |bs +|rc +|ss 2|es +|ws +| T: Nomginnaen TC: excellent E: ultrumm EC: few
wounds EP: sit P: std > 
Ultrumm misses you with his hit.
Ultrumm badly wounds you with his powerful hit.

< 532h/548H 120v/120V |bs +|rc +|ss 2|es +|ws +| T: Nomginnaen TC: few scratches E: ultrumm EC: few
wounds EP: sit P: std > 
[Wrathful Smite]
Ultrumm misses you with his hit.
Ultrumm misses you with his hit.

**Comment by Nyyrazzilyss** [comment]
This is by design.

When rescue is set to all, anything tanking the mob you're attacking (regardless of grouped or ungrouped) will be rescued. Pets for example are rarely grouped.
