### ISSUE TITLE
[Ranger] @starttrain tank broke during a train - sweeping strike killed last mob and was on still CD when attempted to engage next mob

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#97]
This has only happened 1x so far in ~2 hours of use.

I am not sure the script was < second too fast in calculating if sweeping strike was off CD or there is another issue.

Log
-------------------------
< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: few wounds EP: rcl P: std
> 
[Armor Splinter]
Your massive flame-enshrouded slash slightly wounds a muscular bugbear. (x6)

< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: few wounds EP: rcl P: std
>

You strike the weak spots in a muscular bugbear's armor, leaving him vulnerable.

< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: nasty wounds EP: rcl P:
std >

You are already affected by that spell!

< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: nasty wounds EP: rcl P:
std > 
< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: nasty wounds EP: rcl P:
std > 

Your massive flame-enshrouded slash severely wounds a muscular bugbear.
Your massive flame-enshrouded slash wounds a muscular bugbear harshly.
Your massive flame-enshrouded slash severely wounds a muscular bugbear.
Your massive flame-enshrouded slash wounds a muscular bugbear harshly. (x2)
Your massive flame-enshrouded slash brutally wounds a muscular bugbear.
A muscular bugbear clambers to his feet.

< 525h/525H 121v/121V |0|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: pretty hurt EP: std P: std
> 

Your massive flame-enshrouded slash wounds a muscular bugbear harshly.
The runes along your a moonblade with a golden hilt abruptly glow fiercely, emitting
a warm glow that illuminates a muscular bugbear in radiance.  The light settles
across his body, and a loud sizzling sound can be heard as his body
begins to dissolve under the positive energy discharge.
A muscular bugbear staggers from your massive flame-enshrouded slash!
You critically wound a muscular bugbear with a massive flame-enshrouded slash!
A muscular bugbear is nearly slain by the force of your massive flame-enshrouded slash!

< 525h/525H 121v/121V |1|1|2|1|1| T: Manorak TC: excellent E: bugbear EC: awful EP: std P: std > 

[Sweeping Strike]
A muscular bugbear is stunned!
A muscular bugbear slumps to the ground.
You sweep a muscular bugbear to the ground and finish him with a pair of killing blows.
a muscular bugbear is dead! R.I.P.
A muscular bugbear slumps to the ground.
You receive 87,080 XP (0.44%) experience.
Your blood freezes as you hear the rattling death cry of a muscular bugbear.
[Calling function: NextTrainStop()]

< 525h/525H 121v/121V |1|1|2|1|1| P: std >

You don't see them here!

< 525h/525H 121v/121V |1|1|2|1|1| P: std > 
You get a small pile of coins from corpse of a muscular bugbear.
There were: 4 platinum coins, 20 gold coins, 4 silver coins, 2 copper coins.

< 525h/525H 121v/121V |1|1|2|1|1| P: std > 

[Blades of Fire has expired on Manorak.]

@fwalk 44348
[Path: .s]
s

[Currently moving - spellcast is temporarily disabled]

The flames around your weapons subside.

< 525h/525H 121v/121V |1|1|2|2|1| P: std >

An Abandoned Mine Tunnel
   You are in a narrow mining tunnel. Underneath you, secured to the
ground by iron spikes, is a rusting set of cart tracks. Comfort was
obviously not in mind during the construction of this passage. The
tunnel is just wide enough for a large mining cart to pass through
along the tracks. The height of the passage was designed for miners of
less than human height. The passage continues to the north and south.
Exits: - North - South  [44348] 
Hiding in the shadows here is a crafty looking bugbear.
A giant slimy white worm crawls through the passage.

< 525h/525H 120v/121V |1|1|2|2|1| P: std > 

[Reached train station: (44348) bugbear]

A crafty bugbear is in an excellent condition. (Medium)

< 525h/525H 120v/121V |1|1|2|2|1| P: std > 
That power hasn't recharged yet!

< 525h/525H 121v/121V |1|1|2|2|1| P: std >

The following powers are currently recharging:

 - Armor Splinter in 3 seconds 1 pulse 

< 525h/525H 121v/121V |1|1|2|2|1| P: std > 

[Cloak of the Winds has expired on Manorak.]

Your cloak of winds vanishes.

< 525h/525H 121v/121V |1|1|2|2|1| P: std >

**Comment by Gyrx** [comment]
I seem to be running into this fairly regularly, roughly every ~2 hours.  In both CM and Ashstone.

Ashstone log:

< 526h/540H 121v/121V |1|1|1|1|1| T: Manorak TC: few scratches E: bouncer EC: awful EP: std P: std >

[Sweeping Strike]
You sweep attack A burly bouncer with a fury of blows, but he retains his balance.
A burly bouncer slumps to the ground.
A burly bouncer is dead! R.I.P.
A burly bouncer is stunned!
A burly bouncer slumps to the ground.
You receive 298,828 XP (1.00%) experience.
Your blood freezes as you hear the rattling death cry of A burly bouncer.
[Calling function: NextTrainStop()]

< 526h/540H 121v/121V |1|1|1|1|1| P: std > 
You get a few coins from corpse of A burly bouncer.
There were: 9 platinum coins, 15 gold coins, 2 silver coins.

< 526h/540H 121v/121V |1|1|1|1|1| P: std > 
@fwalk 87272
[Path: .2s]
s

[Currently moving - spellcast is temporarily disabled]
s

The House of Pleasure
   The wooden walls of this room bear little decoration.  The windows have 
been covered to keep the room dark no matter the time of day.  It has four 
plain looking beds with white silk sheets that almost seem medical.  The 
room seems to be for customers to sleep off whatever excesses they have 
been involved in.  The air is thick with sweat and body odor from those 
left here.
Exits: - North - South - West          [87271] 
A naked man is sleeping here, looking quite exhausted.

< 532h/540H 120v/121V |1|1|1|1|1| P: std >

The House of Pleasure
   Here at the corner of the building heavy beams hold the upper floor 
aloft.  Only a few curtained windows allow light into this room that is 
best kept in the dark.  This is the cheapest section of the brothel, with 
dirty stained beds; the customers only stay here long enough to get what 
they came for.  A strange smell in the air reminds you of the saddest 
moment of your life.
Exits: - North - West   [87272] 
[81] A dark leather purse is lying here.
A very sharp looking sword lies on the ground.
A prostitute is here strutting her stuff.
A faint nimbus of smoke wafts around the hooves of this fierce nightmare.

< 532h/540H 119v/121V |1|1|1|1|1| P: std > 

[Reached train station: (87272) prostitute]

A prostitute is in an excellent condition. (Medium)

< 532h/540H 119v/121V |1|1|1|1|1| P: std > 
That power hasn't recharged yet!

< 533h/540H 121v/121V |1|1|1|1|1| P: std >

The following powers are currently recharging:

 - Bladestorm in 15 seconds 3 pulses 

< 534h/540H 121v/121V |1|1|1|1|1| P: std > 

The flames around your weapons subside.

**Comment by Nyyrazzilyss** [comment]
function StartFight()
	if prompt:get("tank") == "" then
		tempTimer(2, [[StartFight()]])
	else
		return	
	end

**Comment by Nyyrazzilyss** [comment]
probably fixed 12/6 dev
