### ISSUE TITLE
@starttrain tank script should contain the ability to automatically resume train to next stop if no mob is detected when trying to engage

### ISSUE THREAD

**Issue by Gyrx** [Nyyrazzilyss/NyyLIB#98]
Only applicable to custom train scripts that involve mobs that wander.  This would be great for old exp zones that don't have mobs in static locations (Minotaur Outpost / Havenport / Swift Steel Company / Comarian Mines).

Log:
-------------------------------------------------
< 444h/525H 120v/121V |0|0|1|1|1| P: std > 

[Target is damaged or already dead - Moving to next target]
@fwalk 44335
[Path: .n]
n

A Branch in the Mine Tunnel
   The tunnel expands into a wide chamber here. Huge support beams
reinforce the almost triangular shaped room. Mining tracks enter the
room from passages to the south, east and west, where they converge into
a circular track spinning device. The device is rusted to the point
of beyond repair, but at one time this unit allowed miners to choose
which passage they pushed their cart through.
Exits: - East  - South - West          [44335] 
Hiding in the shadows here is a crafty looking bugbear.

< 447h/525H 120v/121V |0|0|1|1|1| P: std > 

[Reached train station: (44335) bugbear]

A crafty bugbear is in an excellent condition. (Medium)

< 447h/525H 120v/121V |1|0|1|1|1| P: std > 
A crafty bugbear leaves west.

< 447h/525H 120v/121V |1|0|1|1|1| P: std > 

Your cloak of winds vanishes.

< 448h/525H 121v/121V |1|1|1|1|1| P: std >

No target for your power could be found!

**Comment by Nyyrazzilyss** [comment]
this should be fixed in dev
